### ISSUE TITLE
HTML Output on site migration

### ISSUE THREAD

**Issue by landwire** [johnbillion/query-monitor#101]
Hi there,
I migrated my site online (which was just locally on my computer) and suddenly get the below printed right after the body tag with all the body classes in it. Obviously it also appears in the frontend and admin. Could it be related to the symlink? No idea really.

The path below is to the website where it was locally before I moved it online. So, the below only prints in the online version, the offline version works fine. Not sure if this is a bug?

"/Volumes/Work/sites/2014a.landwire.net/wp-content/plugins/query-monitor/wp-content/db.php"

Even after I deleted the plugin the message still remains on both admin and front-end.
Thanks,
Sascha

**Comment by johnbillion** [comment]
Are you also seeing a warning about the db.php symlink at the top of the 'Queries' section?

**Comment by landwire** [comment]
Yes, I see this there:
Extended query information such as the component and affected rows is not available. Query Monitor was unable to symlink its db.php file into place. See this wiki page for more information.

**Comment by johnbillion** [comment]
Yeah what's happened is the symlink has broken with the site move. You should deactivate and reactivate QM, or follow the instructions in that link.

Note that there's nothing that QM can do about this because it's an OS level thing. Any symlink that gets moved in this manner will break (hence the message I added in #5).

**Comment by landwire** [comment]
Sorry to open this again, but how do I get rid of the:
"/Volumes/Work/sites/2014a.landwire.net/wp-content/plugins/query-monitor/wp-content/db.php"
when the plugin is deleted and not active anymore?

Or is it only showing this message when the website is viewed from my computer? I just do not know where the text comes from....

**Comment by johnbillion** [comment]
The text that's showing is the contents of the broken symlink (it looks like your OS is treating it as a plain text file instead of a symlink).

It's located at `wp-content/db.php` on your new site. Delete the file and the text will go away :)

**Comment by landwire** [comment]
Ok, thank you very much!
