### ISSUE TITLE
Conflict problem with Gravity Forms plugin

### ISSUE THREAD

**Issue by sireneweb** [johnbillion/query-monitor#102]
Hi,
with Gravity forms 1.9.2 i get a css display problem
![image](https://cloud.githubusercontent.com/assets/1773161/6501711/183d0e54-c31c-11e4-93b2-414a36961e78.png)

the query monitor doesn't display correctly
![image](https://cloud.githubusercontent.com/assets/1773161/6501720/2c0fc264-c31c-11e4-9eb9-bb870b3d6811.png)

is there a filter to disable Query monitor on specific plugin page ? How i can help you tou fix this bug with gravity forms plugin

**Comment by johnbillion** [comment]
Thanks for the report. It looks like QM's CSS isn't being output on that particular page.

I'll take a look and let you know if I need any more info from you.

**Comment by lumpysimon** [comment]
It looks like you have enabled Gravity Forms "No conflict mode", which prevents other plugins' styles and scripts running on Gravity Forms admin pages (to avoid possible conflicts). If you disable that option, Query Monitor will display correctly on those pages.

![gf-no-conflict](https://cloud.githubusercontent.com/assets/625372/6653931/32266490-ca9d-11e4-96a1-67f51d21322b.png)

**Comment by johnbillion** [comment]
Confirmed!
