### ISSUE TITLE
Query Monitor only showing in WP Admin

### ISSUE THREAD

**Issue by brianjking** [johnbillion/query-monitor#103]
Query Monitor appears to be working properly in WP Admin, however, on the front-end when logged in as administrator I can see it in the WP Admin Menu Bar, nothing occurs when I click on it though.

**Comment by johnbillion** [comment]
This might be the same issue as #96.

Are there a fatal error appearing if you view the page's source code or take a look in PHP's error log?

**Comment by brianjking** [comment]
Yes, I have a 500 fatal error on page load in the Chrome console.log. No details about what though.

**Comment by johnbillion** [comment]
Can you take a look in PHP's error log and let me know what the error is?

**Comment by brianjking** [comment]
So strange, nothing is showing in any of the following files related to the 500 error.

1. error.log (nginx)
2. error_log in the home directory root of "www" for apache
3. WordPress debug.log

Query Monitor used to work fine, I stopped using it for a bit, deactivated and now would like to re-activate and that's what has spurred this.

Any suggestions?

Thanks!

**Comment by johnbillion** [comment]
I've just release an update to QM. Let me know if this fixes your issue. (If it does, you'll hopefully see QM reporting some missing scripts/styles, or some missing dependencies).
