### ISSUE TITLE
Argument 1 passed to QM_Collector_Assets::get_broken_dependencies() must be an instance of _WP_Dependency

### ISSUE THREAD

**Issue by lukasjuhas** [johnbillion/query-monitor#104]
After installing latest update 2.7.0 there is fatal error showing in server log. 

 [error] 1766#0: *78755 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to QM_Collector_Assets::get_broken_dependencies() must be an instance of _WP_Dependency, boolean given, called in /var/www/DOMAIN.com/wp-content/plugins/query-monitor/collectors/assets.php on line 69 and defined in /var/www/DOMAIN.com/wp-content/plugins/query-monitor/collectors/assets.php on line 79" while reading upstream, client: 81.133.209.21, server: DOMAIN.com, request: "GET /basket/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "DOMAIN.com", referrer: "http://DOMAIN.com/basket/"

I have seen one report on the wordpress.org plugin page so I assume it's not just me.

Thank you!

**Comment by johnbillion** [comment]
Thanks for the report Lukas.

Are you able to try deactivating your plugins one by one to see which one is causing the problem? Or, it might well be your theme. Can you try switching to one of the default themes and seeing if the problem disappears?
