### ISSUE TITLE
Debug_Bar_Panel class needs a PHP4 style constructor

### ISSUE THREAD

**Issue by DavidEBrumbaugh** [johnbillion/query-monitor#105]
I got this error when I pulled the latest version of VIP-Quickstart

Fatal error:  Call to undefined method Debug_Bar_Panel::Debug_Bar_Panel() in /srv/www/wp-content/plugins/log-viewer/includes/class-dbpanel.php on line 65

I changed line 65 as follows and now it works on my system:
//parent::Debug_Bar_Panel( 'Log Viewer' );
parent::__construct( 'Log Viewer' );

**Comment by johnbillion** [comment]
Thanks for the report. I had hoped I wouldn't need to keep the old `Debug_Bar_Panel:: Debug_Bar_Panel()` constructor in there, but it looks like I'll need to.
