### ISSUE TITLE
Option debugging

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#107]
Beside using wp-cli `wp option get option-name` you can view/edit/search even a serialized option's value by installing: `Option Inspector`
https://wordpress.org/plugins/options-inspector/

**Comment by szepeviktor** [comment]
Go to Settings / Options.

**Comment by szepeviktor** [comment]
It is much like a *comment request*.

**Comment by crstauf** [comment]
@szepeviktor is there anything wrong with the plugin you mentioned, or you're just wanting to see option debugging implemented into QM?

**Comment by szepeviktor** [comment]
I'd like it mentioned in the FAQ if it is possible.

**Comment by johnbillion** [comment]
I've decided not to implement this at this time.
