### ISSUE TITLE
`WP_DEBUG` broken?

### ISSUE THREAD

**Issue by joshbetz** [johnbillion/query-monitor#108]
It seems like e19f7ae95f1d55d2018be3749e47d9c4d92d4272 breaks `WP_DEBUG`, at least in some cases.

https://github.com/johnbillion/query-monitor/commit/e19f7ae95f1d55d2018be3749e47d9c4d92d4272#commitcomment-10223286

**Comment by OriginalEXE** [comment]
Agreed, same happens here.

**Comment by szepeviktor** [comment]
Do you mean errors are not displayed?

**Comment by OriginalEXE** [comment]
Correct,

for example, if I were to try to call an undefined function, the output of the page would simply stop without any message.

With Query Monitor deactivated, undefined function error normally shows.

**Comment by johnbillion** [comment]
Yikes. This is preventing fatal errors from being displayed (although they are still logged to the PHP error log).

**Comment by szepeviktor** [comment]
It is a good practice to have a terminal open to watch the error log/s.

**Comment by alessandrotesoro** [comment]
I can confirm this too, i've installed the plugin on a local setup, and while i'm developing, errors are suppressed resulting in a white page.

**Comment by johnbillion** [comment]
I have a fix for this which I'll release in the next couple of days.

**Comment by alessandrotesoro** [comment]
No worries, thanks for your hard work :)

**Comment by johnbillion** [comment]
This has been fixed in the latest version of QM. The return value of the error handler remains as `false`, so error logging continues to work, and QM now ensures that the relevant fatal error message gets output on shutdown (including support for Xdebug's enhanced error message output if it's installed).

**Comment by Daronspence** [comment]
Hey @johnbillion I'm finding that this issue is still happening with syntax errors in the latest .org release version of QM (I'm using 2.7.2). Not sure if you've pushed this patch or if this fixes it as well. Cheers mate!

**Comment by johnbillion** [comment]
This should have been fixed in 2.7.2.

Can you let me know the exact output of the following please Daron?

 * `var_dump( ini_get( 'display_errors' ) );`
 * `var_dump( error_reporting() );`
 * `var_dump( phpversion() );`

Also let me know if you have Xdebug installed or not.

**Comment by Daronspence** [comment]
Display with QM active & Xdebug off & on (same results)
`string(1) "0" `
`int(32767)`
`string(16) "5.5.9-1ubuntu4.5" `

QM Inactive and Xdebug off & on (same results)
`string(1) "1"` 
`int(32767)` 
`string(16) "5.5.9-1ubuntu4.5"`

I'm using a stock install of VVV for my dev environment. QM v2.7.2 on WP 4.1.1 MU and 4.1.1 Single Site Install

**Comment by johnbillion** [comment]
This entire thing is a complete pain in the ass.

**Comment by Daronspence** [comment]
Sorry John! :(

**Comment by johnbillion** [comment]
#blamephp

**Comment by johnbillion** [comment]
I have a solution though. I'll probably push an update tonight.
