### ISSUE TITLE
Hide core actions

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#111]
As it is possible to hide QM hooks https://github.com/johnbillion/query-monitor/pull/72, please add a core hook hiding define.

**Comment by johnbillion** [comment]
Thanks for the suggestion Viktor. I'm not sure what benefit this has. If you're debugging plugins or themes, I think it's important that you can see all of the actions attached to a given hook, even if they are actions which you may think aren't relevant.

What particular problem are you having? Too many actions listed in the output?

**Comment by szepeviktor** [comment]
> What particular problem are you having? Too many actions listed in the output?

You are right on my point.

**Comment by szepeviktor** [comment]
This would be the very same as #72

**Comment by Mte90** [comment]
I think that query monitor is fantastic but have the problem to be very verbose so a solution for this will be very appreciated.
I can look on that to improve the actual solution of #72

**Comment by crstauf** [comment]
@szepeviktor @Mte90 consider PR #216

**Comment by johnbillion** [comment]
This was fixed way back in 2.12.0.

**Comment by johnbillion** [comment]
In addition, there's a new `Non-Core` option available in every Component filter as of QM 2.16.0.

**Comment by szepeviktor** [comment]
Great news. Thanks.

**Comment by Mte90** [comment]
Cool, I was thinking that was a constant to define on wp-config. My idea was to disable it on dev sites and left enabled on the wp-dev environment that I use for contribute to wordpress.

**Comment by johnbillion** [comment]
@Mte90 The `QM_HIDE_CORE_HOOKS` constant can be used for that :-)

**Comment by Mte90** [comment]
Added on https://github.com/johnbillion/query-monitor/wiki/How-to-use :-)
