### ISSUE TITLE
WP REST API monitoring

### ISSUE THREAD

**Issue by lamosty** [johnbillion/query-monitor#114]
Hello,

I started using [WP REST API](https://github.com/WP-API/WP-API) lately. What I miss are Query Monitor's monitoring features (queries, profiling, etc). 

I think it is a good idea to add monitoring of REST API requests. The output could be either added to the REST API JSON response (ideal for testing the REST API directly from browser, not JS app) or log the information somewhere (DB or file) and have an UI in the WordPress Admin.

**Comment by johnbillion** [comment]
This is part of my grand plan for Query Monitor :)

I've been altering the way that QM collects, processes, and outputs its data in the last few releases. I'm nearly there with being able to implement an output handler for the REST API (and, should I decide to, the XML-RPC API and RSS feeds too).

The first implementation will probably require a filter to be added to enable it, and it'll add data to the JSON response. Future versions of QM will allow a form of persistent logging.

I'll keep you posted!

**Comment by lamosty** [comment]
Excellent news @johnbillion, thank you :)

**Comment by johnbillion** [comment]
First version of this is now available in QM 2.8.0.

The debugging comes in the form of HTTP headers when performing an authenticated REST API request. Shows PHP errors when relevant, along with an overview of memory usage, processing time, database query number, and database query time.

**Comment by Mte90** [comment]
any news for the rss feed support?
