### ISSUE TITLE
Mute WordPress.org API warnings when Airplane Mode is active

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#115]
Query Monitor's HTTP component already plays nicely with [Airplane Mode](https://github.com/norcross/airplane-mode/). Let's also avoid showing the incessant `Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration` PHP warnings when Airplane Mode is active.

Related: https://github.com/norcross/airplane-mode/issues/39

**Comment by szepeviktor** [comment]
What does it have to do with QM?

**Comment by johnbillion** [comment]
QM normally shows an alert in the toolbar if an HTTP request fails or returns a `WP_Error`, but it's aware of Airplane Mode so mutes them. It should do the same for the PHP warning which gets raised by core.

One could argue either way that this could be an enhancement to Airplane Mode or QM. Personally I like the fact that Airplane Mode doesn't currently try to mess with catching and preventing that PHP warning from being displayed.

**Comment by szepeviktor** [comment]
So this issue is about catching WP core errors?

**Comment by johnbillion** [comment]
Yes, but just those specific errors and only when the HTTP requests to the wordpress.org API have been blocked with Airplane Mode.

**Comment by szepeviktor** [comment]
Is it useful not to catch all core errors?
Do you think displaying a red item in the admin bar is not enough?

**Comment by johnbillion** [comment]
Sorry Viktor, I'm not sure what you're asking. Can you clarify?

QM currently catches all PHP warnings, notices, and deprecated notices, and displays an alert in the admin toolbar. All I\m proposing here is muting the `Warning: An unexpected error...` warnings which get triggered when requests to the wordpress.org API are blocked with Airplane Mode.

**Comment by szepeviktor** [comment]
> QM currently catches all PHP warnings, notices, and deprecated notices

How can this warning slip away? Does QM catch only plugin errors not core ones?

**Comment by johnbillion** [comment]
QM catches all errors on the page. It [overrides PHP's built-in error handler](https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L42) in order to collect errors and display them in its own panel. I'll just filter out the `Warning: An unexpected error...` errors.

**Comment by szepeviktor** [comment]
Why does it appear as a regular PHP warning in the current state of QM?
Why doesn't it get caught?

**Comment by johnbillion** [comment]
It shouldn't do. Can you send a screenshot?

**Comment by szepeviktor** [comment]
Sorry. QM was off all the time.

![warning](https://cloud.githubusercontent.com/assets/952007/6830224/b2a54e6e-d318-11e4-90a1-47c76715960d.jpg)

**Comment by johnbillion** [comment]
No worries!

**Comment by szepeviktor** [comment]
After all it would be better to copy code from my disabler plugin.
