### ISSUE TITLE
W3 Total Cache Incompatibility

### ISSUE THREAD

**Issue by mbitson** [johnbillion/query-monitor#121]
Hey there! 

First up, great tool- loving it. I'm attempting to get the db.php file to be positioned into wp-content correctly via symlink, however the plugin "W3 Total Cache" installs it's own db.php into wp-content. It looks like this:

http://devimg.next-www.com/20150423125725620.png

I'm certain W3 is utilizing this file and W3 is absolutely essential to the speed of my client's site. Would it be possible to rename db.php?

Cheers,
Mike

**Comment by johnbillion** [comment]
You're not the first person to bring this up. Unfortunately there is no way around it at the moment. Any plugin which implements a custom database controller needs to use a file called `wp-content/db.php` (ie. you can't rename it).

See also #68 and https://wordpress.org/support/topic/error-with-w3-total-cache-file-dbphp-is-not-a-w3tc-drop-in.

**Comment by johnbillion** [comment]
It's worth noting that W3TC only needs to use its own `wp-content/db.php` if you explicitly have the database caching component enabled in W3TC. If you're not using that, you can delete the file, then activate QM, and it'll symlink its own `wp-content/db.php` file in place and it'll all work fine.

**Comment by mbitson** [comment]
Thanks for the info, that makes perfect sense! Bummer, but makes sense.

**Comment by mattnraines** [comment]
I realise this is an old ticket but have a workaround for anyone still affected by it. You probably only need W3 Total Cache on production and you probably only need Query Monitor in development. Our composer.json runs `ln -sf plugins/w3-total-cache/wp-content/db.php wp-content/db.php` on prod and `ln -sf plugins/query-monitor/wp-content/db.php wp-content/db.php` on dev and wp-content/db.php is in our .gitignore.
