### ISSUE TITLE
QM_Output_Html_Assets::dependency_row() fatal error

### ISSUE THREAD

**Issue by GaryJones** [johnbillion/query-monitor#122]
Getting the following in the `wp-content/debug.log`:

> PHP Catchable fatal error:  Argument 1 passed to QM_Output_Html_Assets::dependency_row() must be an instance of _WP_Dependency, boolean given, called in /var/www/example.com/wp-content/plugins/query-monitor/output/html/assets.php on line 105 and defined in /var/www/example.com/wp-content/plugins/query-monitor/output/html/assets.php on line 113

**Comment by johnbillion** [comment]
Thanks Gary.

Are you able to narrow down which plugin or theme is causing this?

**Comment by GaryJones** [comment]
Not immediately, but I'll keep an eye out to try and pinpoint.

On the site it was on, I did have a style enqueued that I know was 404 - might that be related?

**Comment by johnbillion** [comment]
A 404 won't affect the dependencies system, no.

Are you running the latest version of QM? #97 #104 fixed some edge cases in the dependencies system in the last couple of releases.

**Comment by GaryJones** [comment]
I've got whatever is latest on WPORG.
