### ISSUE TITLE
Localisation debugging

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#124]
Debugging sites that are loading in translations can be a faff, especially if things aren't working.

Brain dump of stuff I'd like to see:
- [x] Current locale
- [x] List of loaded MO files
- [ ] Available languages (locales)
- [x] Plugins / themes which don't have a translation for the current (or a given) language
- [ ] Strings on the page which don't have a translation in the current locale

**Comment by pdewouters** [comment]
I've used this in the past, might get some ideas from it? https://marketpress.com/product/debug-translations/

**Comment by johnbillion** [comment]
Thanks! That could be handy.

**Comment by johnbillion** [comment]
Here's what this panel now looks like in QM 2.8.0:

<img width="896" alt="" src="https://cloud.githubusercontent.com/assets/208434/10569689/ec990a78-7621-11e5-941f-5f1158c37720.png">

/cc @MPolleke
