### ISSUE TITLE
Showing Blank Page On Woocommerce Account Page

### ISSUE THREAD

**Issue by asisten** [johnbillion/query-monitor#125]
When I tried to examine query from Woocommerce Account Page, this page suddenly stop working and only showing white blank page. It resolved by disabled Query Monitor plugins.

Is this plugins unabled to monitoring private / restricted Wordpress page?

Wordpress 4.2.2
Woocommerce 2.3.11

**Comment by johnbillion** [comment]
Hi asisten,

 * Are there any errors showing in your server's or PHP's error logs?
 * If you view the source of the page, are there any errors shown?
 * Does the problem persist if you deactivate all your other plugins apart from QM and WooCommerce?
