### ISSUE TITLE
Where i can find queries?

### ISSUE THREAD

**Issue by Valonix** [johnbillion/query-monitor#133]
Hello, i install the plugin. Where i can find queries and other?

**Comment by johnbillion** [comment]
In the admin toolbar at the top of the screen.

![Menu](https://camo.githubusercontent.com/cb3dfdca4936b804ce4607acc06c15655c1b3487/68747470733a2f2f7261772e6769746875622e636f6d2f6a6f686e62696c6c696f6e2f51756572794d6f6e69746f722f6d61737465722f6173736574732d77702d7265706f2f73637265656e73686f742d312e706e67)

**Comment by Valonix** [comment]
ohh,, thank. someone disabled toolbar, right now i must find toolbar
