### ISSUE TITLE
Notice: Undefined index: total_time in overview.php on line 37

### ISSUE THREAD

**Issue by bonny** [johnbillion/query-monitor#134]
I added `define("SAVEQUERIES", false);` (because the sql output was to big for me in non-admin-bar mode) to my wp-config.php and after that I got this in the output from Query Monitor: 
`Notice: Undefined index: total_time in overview.php on line 37`

For quick reference this is the section in overview.php:

```
		if ( $db_queries ) {
			# @TODO: make this less derpy:
			$db_queries_data = $db_queries->get_data();
			if ( isset( $db_queries_data['types'] ) ) {
				$db_query_num = $db_queries_data['types'];
				$db_stime = number_format_i18n( $db_queries_data['total_time'], 4 );
			}
		}

```

**Comment by johnbillion** [comment]
Fixed in #141
