### ISSUE TITLE
Symlink for drop-in not possible with drop-in

### ISSUE THREAD

**Issue by franz-josef-kaiser** [johnbillion/query-monitor#135]
The recommendation [in the wiki](https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink) isn't possible if there's already a `db.php` file (the drop in) there. What to do in those cases?

**Comment by johnbillion** [comment]
Unfortunately there's nothing you can do apart from remove the existing `db.php` file and then create the symlink. This is a limitation of WordPress - there can only be one `db.php` file in place at a time.

This comes up quite often. Previous discussions: #68, #85, #121 and https://wordpress.org/support/topic/error-with-w3-total-cache-file-dbphp-is-not-a-w3tc-drop-in

**Comment by franz-josef-kaiser** [comment]
ok, thanks!
