### ISSUE TITLE
Values passed via set_query_var aren't escaped/encoded, and break width.

### ISSUE THREAD

**Issue by jono-alderson** [johnbillion/query-monitor#136]
When using set_query_var($foo,$bar) to pass values to get_template_part($foo,$bar), $bar is output directly to the on-page query monitor debugging section without any kind of encoding or escaping. See screenshot.

Also, for long strings or wide content, this section often extends horizontally beyond the confines of the 'table', and as such extends the horizontal width of the whole page when the debugging section is visible.

![image](https://cloud.githubusercontent.com/assets/11629607/9659029/a50fa43c-5245-11e5-8271-a9d94fde2c55.png)

**Comment by johnbillion** [comment]
Thanks! I'll get this fixed up.

**Comment by johnbillion** [comment]
Fixed in be2ac4b.
