### ISSUE TITLE
Plugin does not work with Cloudflare Flexible SSL

### ISSUE THREAD

**Issue by hubdotcom** [johnbillion/query-monitor#137]
Mixed Content: The page at 'https://x.com/wp-admin/plugins.php' was loaded over HTTPS, but requested an insecure stylesheet 'http://x.com/wp-content/plugins/query-monitor/assets/query-monitor.css'. This request has been blocked; the content must be served over HTTPS.

Mixed Content: The page at 'https://x.com/wp-admin/plugins.php' was loaded over HTTPS, but requested an insecure script 'http://x.com/wp-content/plugins/query-monitor/assets/query-monitor.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by hubdotcom** [comment]
This seems to be a problem with CloudFlare Flexible SSL - as Query Monitor forces itself to load first, the SSL forging is not yet in place. Is it possible to allow this plugin to load before QM?

**Comment by hubdotcom** [comment]
Fixed by moving code from the plugin to wp-config.php - thereby loading first. CloudFlare Flexible SSL does try to load first but seems to be failing on QM - I'll file the bug report with them. Thanks

**Comment by johnbillion** [comment]
Thanks for the report. Query Monitor enqueues its CSS and JavaScript in just the same way as any other plugin, on the `wp_enqueue_scripts` hook, so there's no reason why the CloudFlare Flexible SSL plugin shouldn't work as expected with QM. Let me know if you find out what the problem is.

**Comment by johnbillion** [comment]
Ah, I see the problem. CloudFlare Flexible SSL needs to be the first plugin to load because it sets the `$_SERVER['HTTPS']` variable, but this happens after QM intialises its `QM_Plugin` class.

I might be able to tweak this so it's not a problem.

**Comment by hubdotcom** [comment]
That would be great if so. The plugin does try to force itself to load first (https://plugins.trac.wordpress.org/browser/cloudflare-flexible-ssl/trunk/plugin.php#L35), but somehow this is failing - I've filed a report with the developers too.

**Comment by johnbillion** [comment]
I suspect [Query Monitor beats it to it](https://github.com/johnbillion/query-monitor/blob/2.7.4/query-monitor.php#L214-L249).
