### ISSUE TITLE
No results with Redis Cache

### ISSUE THREAD

**Issue by skynet** [johnbillion/query-monitor#139]
Doesn't show anything when Redis Cache is enabled (https://wordpress.org/plugins/redis-cache/)

**Comment by johnbillion** [comment]
I run the [WP Redis](http://github.com/alleyinteractive/wp-redis/) plugin on my personal site and QM works as expected. Can you temporarily try that plugin and see if it works?

Are you seeing anything at all in the admin toolbar? Any errors in your browser console or in PHP's error log?

**Comment by skynet** [comment]
Yes, I can confirm that it works with your Redis Plugin. Reported: https://github.com/tillkruss/Redis-Object-Cache/issues/13

**Comment by johnbillion** [comment]
Thanks, I'll take a look when I have some free time.

**Comment by imknight** [comment]
Just add the WP_CACHE_KEY_SALT to wp-config file , the query monitor will work with redis cache this plugin
