### ISSUE TITLE
When HTTP requests are blocked requests show up as timed out.

### ISSUE THREAD

**Issue by grappler** [johnbillion/query-monitor#140]
When using `add_filter( 'pre_http_request', '__return_true', 100 );` the update http requests show up as timed out when they are actually blocked. In this case I think it better to mark them in orange then red. You can see this in `/wp-admin/update-core.php?force-check=1#qm-http`

**Comment by johnbillion** [comment]
Thanks for the report, Ulrich.

Returning `true` from the `pre_http_request` filter doesn't make much sense. It should either return a `WP_Error` or an array which mimicks an HTTP API response. In that case, QM _should_ handle it ok.

What are you trying to achieve by returning true?

**Comment by johnbillion** [comment]
If you're blocking HTTP requests, then a `WP_Error` should be returned. [This is what Airplane Mode does](https://github.com/norcross/airplane-mode/blob/master/airplane-mode.php#L416-L433). Query Monitor [silently ignores Airplane Mode errors](https://github.com/johnbillion/query-monitor/blob/9a66bca19a7b7ad205e52ca65fd65f5b6ce4b56e/collectors/http.php#L166-L169).

**Comment by grappler** [comment]
Ok, thanks that makes sense. I was doing some testing for https://core.trac.wordpress.org/ticket/29719 when I came across this.

**Comment by johnbillion** [comment]
It's not the first time I've seen confusion over the use of this filter. Opened https://core.trac.wordpress.org/ticket/33995.
