### ISSUE TITLE
I am not enough - "all" action hook

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#143]
> Warning: The all action is extremely resource intensive. Try to avoid using it.

Could you please help me to get around the `all` action.
This function detects unknown AJAX (and admin-post) actions.
If you have time...

```php
    public function all_action( $tag ) {
        global $wp_filter;
        global $wp_actions;
        $whitelisted_actions = array( 'wp_ajax_nopriv_wp-remove-post-lock' );
        // Actions only, not filters, not registered except whitelisted ones
        if ( is_array( $wp_actions )
            && array_key_exists( $tag, $wp_actions )
            && ( 'admin_post_' === substr( $tag, 0, 11 )
                || 'wp_ajax_' === substr( $tag, 0, 8 )
            )
            && is_array( $wp_filter )
            && ! array_key_exists( $tag, $wp_filter )
            && ! in_array( $tag, $whitelisted_actions )
        ) {
            $this->trigger_instant( 'wpf2b_admin_action_unknown', $tag );
        }
    }
```
https://github.com/szepeviktor/wordpress-fail2ban/blob/master/mu-plugin/wp-fail2ban-mu-instant.php#L541-L560

**Comment by johnbillion** [comment]
I would say that's a valid use of the `all` hook. This warning is in place mostly so developers can see if the `all` hook is in use by a third party plugin on their site which may be slowing things down.

**Comment by szepeviktor** [comment]
Thank you very much for telling me that.

**Comment by szepeviktor** [comment]
Just for the record:
It is unnecessary to hook `all` all the time, it should be hooked only in `admin_init` only as `admin_init` is just before doing the AJAX actions.
