### ISSUE TITLE
Undefined indexs in /output/html/languages.php

### ISSUE THREAD

**Issue by richardsweeney** [johnbillion/query-monitor#144]
I'm getting the following 2 notices with 2.8.0. I'm running an non-english site (Swedish if it makes any difference), which may be the issue?

    PHP message: PHP Notice:  Undefined index: line in /{whatever}/wp-content/plugins/query-monitor/output/html/languages.php on line 56
    PHP message: PHP Notice:  Undefined index: file in //{whatever}/wp-content/plugins/query-monitor/output/html/languages.php on line 56

This is the line causing the issues.

    echo self::output_filename( $mofile['caller']['display'], $mofile['caller']['file'], $mofile['caller']['line'] ); // WPCS: XSS ok.

**Comment by tjuris** [comment]
I've seen the same notices, specifically when showing textdomain loading details for the following two plugins: "yith-plugin-fw", which comes with "yith's woocommerce wishlist" among others, and "acf" aka "advanced custom fields".

**Comment by johnbillion** [comment]
Thanks @richardsweeney and @tjuris . Can you both provide me with a list of the active plugins on your site please? I've so far found that Advanced Custom Fields 5 is causing this error, but there may be others too. I'll get a fix out in the next version of QM.

**Comment by ntwb** [comment]
Here's my list of active plugins:

• bbPress
• Debug Bar
• Debug Bar bbPress
• Debug Bar Console
• Debug Bar Transients
• Debug Objects
• Query Monitor
• Query Monitor bbPress & BuddyPress Conditionals

Turns out bbPress is the only one in the above list causing this error for me :smirk: 

If there's something I can or should do to to fix bbPress let me know :smile:

**Comment by richardsweeney** [comment]
I've got ACF 5 active on my site if it helps :)

**Comment by tjuris** [comment]
Active plugins:
* Advanced Custom Fields Pro
* AJAX Thumbnail Rebuild
* Breadcrumb NavXT
* Estonian Banklinks for WooCommerce
* Query Monitor
* WooCommerce
* WooCommerce Multilingual
* WP Smush
* WP-FB-AutoConnect
* WPML Media
* WPML Multilingual CMS
* WPML String Translation
* WPML Translation Management
* YITH WooCommerce Wishlist

Of those, when looking at languages info in query monitor output, Advanced Custom Fields Pro and YITH WooCommerce Wishlist both show this error. The rest do not.

**Comment by richardsweeney** [comment]
ACF 5
Admin Column View
Airplane Mode
Debug Bar
Google Analytics (Yoast)
Visual Composer (I know, I know, the client insisted!)
Search WP live AJAX search
Simple Page Ordering
Unconfirmed
User switching
W3TC
WooCommerce
Domain Mapping (Donnacha's)
WordPress (SEO)
WP-Crontrol
WP-Fail2ban
WP Mandrill
MailPoet
MailPoet pro

Plus a handful of custom plugins, all of which are translated into 2 languages.

**Comment by Mte90** [comment]
Same error in my case but i have only a plugin that I'm developing.

**Comment by Daronspence** [comment]
I'm seeing this error as well from my error logs only, not in Query monitor.

 `public/wp-content/plugins/query-monitor/output/html/languages.php on line 56`

ACF
ACF Font Awesome
ACF Gravity Forms
Better Font Awesome
Epoch
Yoast Analytics
Gravity Forms
GF Stripe Addon
GF Survey Addon
Members (Justin Tadlock)
No page comment
Query Monitor
Simple Google Maps Shortcode
User Switching
WP All Import Pro & ACF Addon
WPMDB Pro & Media Files Addon
WP Pusher
WP Mandrill
Yoast SEO

**Comment by johnbillion** [comment]
Thanks, ACF is definitely the cause here. I've fixed this and I'll get a release out shortly.

**Comment by Daronspence** [comment]
Awesome! Thanks @johnbillion 

Is there something that we can do in ACF v5 to fix this? I'm in the private Beta for the plugin and can pass this on the Elliot as a bug if need be?

**Comment by johnbillion** [comment]
It's not really a bug, it's just that ACF (and a handful of other plugins) call `load_textdomain()` directly, instead of using `load_plugin_textdomain()`. It's a little like re-inventing the wheel, but it's not really a problem.
