### ISSUE TITLE
PHP warning in ajax - flip STRING and INTEGER

### ISSUE THREAD

**Issue by tjuris** [johnbillion/query-monitor#146]
I'm getting the following error with QM 2.8.0:
    <b>Warning</b>:  array_flip(): Can only flip STRING and INTEGER values! in <b>/.../wp-content/plugins/query-monitor/collectors/request.php</b> on line <b>56</b><br />
This happened while trying to translate attributes with woocommerce multilingual ( WC + WPML ). Since they use ajax to show terms to be translated, these errors effectively break the translating process.
Translation works fine without QM active, no errors in log.

**Comment by johnbillion** [comment]
This sounds like an issue with WPML or the WooCommerce Multilingual plugin. A query variable should only use a string for its name, and if it's using something else then it's most definitely broken (it makes no sense that a query variable name would be anything other than a string).
