### ISSUE TITLE
query-monitor.css:98 "padding: 0 10px" creates horizontal scrollbar at 320px

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#149]
It looks like the icon just doesn't fit on mobile view. The default setup for `.ab-icon`, meaning `width: 52px` is too much, also creates a horizontal scrollbar. `padding: 0` works, but then the QM icon looks disproportional. Thoughts?

**Comment by johnbillion** [comment]
Yeah there's a complete lack of space in the toolbar when you're viewing an individual post, or anything else that gets an 'Edit' button in the toolbar.

I've never really decided what to do with QM's output on such small devices. It's all a bit clunky.

**Comment by johnbillion** [comment]
Actually, which device/browser are you using? Using Chrome/Firefox's responsive mode, the buttons fit without a horizontal scrollbar at 320px wide, with the exception of viewing an individual post on multisite, when there are too many buttons to fit on the toolbar.

**Comment by lkraav** [comment]
Yes, Firefox responsive mode showed it first. Yes, the buttons visually fit, but you are able to move the content area horizontally, so something on the right side gets thrown off because too much paddding. It makes things hard to debug, when you don't if you've messed up the DOM structure yourself or not.

**Comment by johnbillion** [comment]
Sounds like it might be a difference in layout on Linux. Firefox on OS X doesn't show the horizontal scrollbar.

Does removing just the right hand side padding from the button fix the issue?
