### ISSUE TITLE
Add ability to filter user_can_view()

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#150]
I have an existing multi-site, where I need to have Administrator roles to get access to Query Monitor. I can see the current logic grants `view_query_monitor` on plugin activation for single sites. But on big development multi-site, granting this capability for Administrator on site by site basis is just a big hassle. With Debug Bar I had a mu-plugin that filtered the output of the permission check to an alternative cap. For example, I would prefer to filter `view_query_monitor` check and turn it into something every Administrator has by default.

Or am I missing something basic here? My Admins aren't able to see QM right now.

**Comment by lkraav** [comment]
This may be the answer http://snippets.khromov.se/dynamically-control-user-capabilities-on-multisite-with-wordpress/

**Comment by lkraav** [comment]
```
leho@conversionready mu-plugins $ [-] cat query-monitor-administator.php 
<?php
add_filter( "user_has_cap", function( $allcaps, $cap, $args ) {

    if ( isset( $allcaps["manage_options"] ) && $allcaps["manage_options"] ) {
        $allcaps["view_query_monitor"] = true;
    }

    return $allcaps;

}, 10, 3 );
```

**Comment by johnbillion** [comment]
Yep, that's the way to do it for now. In a future release I'll probably switch to using capability filtering on the fly instead of adding and removing the `view_query_monitor` cap when activating and deactivating the plugin. This should continue to work in that situation.
