### ISSUE TITLE
Hooks Table : Long Plugin Slugs Cause QM to stretch past 100% width (adds horiz scrollbar)

### ISSUE THREAD

**Issue by jambox** [johnbillion/query-monitor#155]
When a plugin slug is long enough (I think that's the culprit) the following CSS allows the output table to exceed the page width:
```
.qm .qm-nowrap {
    white-space: nowrap !important;
}
```

The text in question that's causing the issues is `Plugin: advanced-custom-field-repeater-collapser`

I know it's a super long plugin name but I think it's a reasonable use case to accommodate. Some solution ideas:

* Abbreviate the text "Plugin:" as something like `(P)`, `(Plug.)`, etc.
* Remove the text "Plugin" and add a color code to distinguish Core, Themes and Plugin calls
* Add a line break after the caller class (i.e. `Plugin:<br/>advanced-custom-field-repeater-collapser`)
* Shrink the size of the `td.qm-ltr.qm-nowrap` elem 

I'm using Chrome on OS X, by the way.

Thanks!

**Comment by johnbillion** [comment]
Thanks for the report. Can you attach a screenshot please?

**Comment by jambox** [comment]
Thanks for the quick response John. My screencapture extension isn't working so I just took a regular screenshot...the little yellow corner on the top right is the page bg. Let me know if you need more than this.

<img width="1199" alt="screen shot 2015-11-18 at 5 47 27 pm" src="https://cloud.githubusercontent.com/assets/472818/11258179/a518b1e0-8e1c-11e5-9d6e-23265f381b9d.png">

**Comment by jambox** [comment]
Hey John thanks for working on this. Seems to have addressed the problems on the front end, but it looks like the Languages section is now behaving similarly, only on the admin side. I've attached a couple screenshots to demonstrate, one with the element that I think is causing the issue and one to show the scrollbar disappearing by removing those elements from the dev inspector

Evil elems
----
<img width="1281" alt="screen shot 2016-02-29 at 11 38 51 am" src="https://cloud.githubusercontent.com/assets/472818/13401531/78843708-deda-11e5-869c-089e7e2436e3.png">

With evil elems gone
----
<img width="1283" alt="screen shot 2016-02-29 at 11 39 07 am" src="https://cloud.githubusercontent.com/assets/472818/13401543/8751fd9c-deda-11e5-9626-2043006aec05.png">
