### ISSUE TITLE
'db.php' symlink name conflicts with w3 total-cache 'db.php' file name

### ISSUE THREAD

**Issue by Boldairdev** [johnbillion/query-monitor#164]
Hi,

I recently installed W3 Total Cache, the problem with it is that it also uses a file called db.php that ends up at the same location than query-monitor db.php symlink. 

So I can obviously use one or the other but not both.

I was wondering how hard it'd be to rename the symlink in your plugin to something more unique like 'db_query-monitor.php' instead to avoid this (and future/others) conflict ?

**Comment by johnbillion** [comment]
Unfortunately this isn't possible as the file needs to be named db.php in order for it to be loaded by WordPress.

Further reading: #68, #131, #135.

**Comment by Boldairdev** [comment]
Oh ok.
Well I took the liberty of editing the related wiki FAQ page to add that information to it. :)
Cheers and thanks for the quick reply

**Comment by johnbillion** [comment]
Thanks!
