### ISSUE TITLE
No Query Monitor output on !is_admin() pages after upgrade to 4.5

### ISSUE THREAD

**Issue by ak5** [johnbillion/query-monitor#182]
Hi!

Love this plugin, absolutely essential to figuring out WordPress for me - thanks so much!

I have an issue where I cannot see any of the query monitor output on the frontend since upgrading to WP 4.5 while being logged in. I do see everything in admin pages just fine.

As a work around, setting cookie and logging out gets me the output on frontend again.

**Comment by johnbillion** [comment]
Do you see any JavaScript errors in your browser console? Does the `Query Monitor` admin toolbar menu appear at all? Is QM's output present if you view the source of the page?

**Comment by ak5** [comment]
Ah yes, I do get this issue in the console: 
```Uncaught Error: Syntax error, unrecognized expression: a[href=#top]```

It looks like the same issue reported elsewhere with jquery not working with the undefined behavior of =# but needs a string like ="#top" in this case?

The Query Monitor admin toolbar does appear but not with the modified stats after load (page load time, memory, etc).

View Source does have the QM output.

**Comment by johnbillion** [comment]
Thanks, so this is unfortunately an issue with a plugin or theme on your site. Can you let me know the file name and line number that's triggering that error?

QM gracefully handles situations where jQuery isn't available, but gracefully handling JavaScript errors triggered elsewhere on the page is difficult.

**Comment by ak5** [comment]
It just says jquery.js line 2. If this is not QM, I'll find the offending plugin - thanks for your quick reply!
