### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by DuckDagobert** [johnbillion/query-monitor#184]
Hey,

great plugin! Unfortunately it doesn't seem to work with PHP7(-fpm) anymore. It shows in debug bar, but on click nothing happens and there is nothing in the footer showing either.
HHVM & php5(-fpm) work perfectly fine however.

**Comment by lkraav** [comment]
This has nothing to do with Query Monitor. Something else on your sites crashes with PHP7 and you need to turn on `WP_DEBUG` to see what it is.

**Comment by johnbillion** [comment]
Thanks for the report, @DuckDagobert. As Ikraav pointed out this could be due to a problem somewhere else on your site. Are you able to check your server's error log and PHP's error log to see if there are any errors in there?

**Comment by DuckDagobert** [comment]
Ok, I checked and it was not PHP7, but on the is_home page it doesn't work, neither with php5, hhvm or php7. It works fine on all pages except the home page.
The qm div is there with display:none and when I manually change it to display:block it displays correctly however. Just on click nothing happens.

**Comment by johnbillion** [comment]
Thanks for the info.

Are there any JavaScript errors in your browser console on the home page? Any errors that appear in PHP's error log?

**Comment by DuckDagobert** [comment]
Hi, I now got it fixed. Was a incompatability with the jquery version I was using and a WP theme.

**Comment by johnbillion** [comment]
Thanks for letting me know, glad to hear you got it fixed!
