### ISSUE TITLE
New debug bar add-on available

### ISSUE THREAD

**Issue by DuckDagobert** [johnbillion/query-monitor#185]
See: https://github.com/10up/debug-bar-elasticpress

**Comment by johnbillion** [comment]
Thanks! Debug Bar add-ons should work without requiring any changes in QM.

I took a brief look at the code in the add-on and it looks very straight forward so I don't anticipate there will be any issues.

**Comment by DuckDagobert** [comment]
I've been using it with QM since months and it's working perfectly fine.
