### ISSUE TITLE
Strange JS error when using VVV

### ISSUE THREAD

**Issue by afragen** [johnbillion/query-monitor#189]
I'm getting a strange JS error in a VVV multisite.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/15307735/e3532dfe-1b8a-11e6-9970-d2a29e8c4705.png)

**Comment by johnbillion** [comment]
Does the error remain of you deactivate all your other plugins and switch
to one of the default themes?

**Comment by afragen** [comment]
I think this may be related to a Shiny Updates error I was getting.

https://github.com/obenland/shiny-updates/issues/111

**Comment by johnbillion** [comment]
Thanks for the update. I'm gonna go ahead and close this ticket - feel free to re-open if there is an issue specific to QM.
