### ISSUE TITLE
De-couple the output

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#19]
One of the end goals of Query Monitor is to enable (but not necessarily provide) other methods of output, such as persistent logging.

The [QM_Component class](https://github.com/johnbillion/QueryMonitor/blob/master/Component.php) currently separates the data collection and processing from the HTML output, but this should be separated even further into separate classes.

The HTML output is also coupled to the main QueryMonitor class which enqueues the CSS/JS and outputs the admin toolbar menu code.

A new class (or classes) should be implemented which provides a basis for all output. QM would use this for its HTML output and its HTTP header output. Another plugin could then use this for outputting to a persistent log of its choosing.

**Comment by FabianSperrle** [comment]
Any news on the persistent logging? Do I have to get my hands dirty or have you made progress already? :smile:

**Comment by johnbillion** [comment]
@FabianSperrle It's in the pipeline, but no, there's nothing ready yet.

If you want to get your hands a little dirty, there's a *very* rough and ready implementation in [the logger branch](https://github.com/johnbillion/query-monitor/tree/logger) which I knocked up ages ago when I needed it. It logs some output to `error_log()`. Not ideal but handy if you really need it. Also [take note of this](https://github.com/johnbillion/query-monitor/blob/logger/dispatchers/Logger.php#L28-L39).

**Comment by lkraav** [comment]
I'm also looking for JSON format output, to automagically send a subset of performance data to outside analytics tools - let's say Google Analytics events for the simplest example.

It doesn't look like this moved a whole lot, so wondering what could be the next step here? How massive is the workload here I wonder? If there was a $$$ bounty on it, how much would someone take this on for?

**Comment by johnbillion** [comment]
@lkraav This would be relatively simple to implement, the only problem would be that QM still logs some large objects in three places (hooks, JS & CSS, and backtraces).

I'll push some code later this evening that demonstrates how to write an output dispatcher without having to handle every different collector in QM.

**Comment by johnbillion** [comment]
@lkraav See https://github.com/johnbillion/query-monitor/tree/json-output. In this branch, QM outputs a `qm_json` object too. It can, for example, be queried in your browser console with something like `qm_json.db_queries.times['get_option()'].calls`.

See the commit at https://github.com/johnbillion/query-monitor/commit/cd1bd85da3b8520c2db89635aeef0cda341d6d47 for which files you'll want to start hacking for your own needs.

**Comment by lkraav** [comment]
Reactions ^^^^

**Comment by lkraav** [comment]
@johnbillion the branch has an initial state of outputting `var qm_json = ;`, which looks like `$out` isn't getting populated correctly for some reason. Is this normal or?

**Comment by johnbillion** [comment]
Not quite sure what's going on there. Try reloading the page and the `qm_json` variable should be correctly populated.

**Comment by lkraav** [comment]
> Not quite sure what's going on there. Try reloading the page and the qm_json variable should be correctly populated.

@johnbillion I'm not able to get the object to show up. Perhaps backtracing the output is the next step, but this isn't showing anything meaningful.

1 .../wp-includes/plugin.php:525QM_Dispatcher_JSON->dispatch(#1)
2 .../wp-includes/load.php:638do_action(tag)
3 PHP internal callshutdown_action_hook()

→ Called from .../query-monitor.git/dispatchers/JSON.php:46 [QM_Dispatcher_JSON->dispatch()]

**Comment by johnbillion** [comment]
Closing this as fixed. I'm going to open up follow-up issues for further work.
