### ISSUE TITLE
Some way to monitor direct file requests?

### ISSUE THREAD

**Issue by squarestar** [johnbillion/query-monitor#190]
I'm using WP Document Revisions on a site and am having some trouble using QM to figure out some problems that have arisen: When I click on a link to a document, because it goes straight to the file without loading any of WP, I can't see what queries or requests were made.

Is there any way around this?

**Comment by johnbillion** [comment]
Due to the way QM hooks into WordPress, monitoring a file that doesn't load WordPress isn't possible.

Bear in mind that if the file is loaded directly then it won't be performing any queries, unless it's a standalone PHP file.

**Comment by squarestar** [comment]
The thing is that the Documents plugin does some behind-the-scenes processing in order to serve up the document. For example, the URL for the file may be "http://domain.com/documents/2016/05/document.pdf", but the file itself lives in "/wp-content/uploads/2016/05" and is called "fa1be654a7ed9f.pdf". The plugin does some work to get this to happen, and I'd like to be able to see what's going on - is there a way to write the queries and requests to a log file?

**Comment by johnbillion** [comment]
Okay so it does actually load WordPress.

QM only prints its output when certain hooks have fired (for example, the `wp_footer` hook). I am working on adding a persistent logger to QM (see #173), but there's no ETA just yet.

**Comment by squarestar** [comment]
That's great about the logger - thanks.

In the meantime, is it possible to manually add an action to get QM to fire on a plugin's hook, i.e., 
`add_action('plugin_action', 'fire_query_monitor')` ?
