### ISSUE TITLE
HTTP requests for wp-cron

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#191]
![](https://cloud.githubusercontent.com/assets/403283/15646464/0f579254-265e-11e6-8777-a8ec92cb405e.png)
As the screenshot I get often this alert locally but because I am locally I don't care about the cron work, maybe we can define a constant to disable that alert.

**Comment by johnbillion** [comment]
I've noticed this too. Ideally I'd like to get to the bottom of the actual problem in core.

**Comment by johnbillion** [comment]
Thanks for the suggestion Daniele but I'm going to close this for now as it's not something I have any plans to work on. The root cause should really be investigated and fixed.

**Comment by Mte90** [comment]
Implement a constant to disable core notification can be an idea to implement something quickly without so many difficulties.
