### ISSUE TITLE
Available Image Size Section

### ISSUE THREAD

**Issue by desrosj** [johnbillion/query-monitor#196]
One thing that I have found myself looking for occasionally is a section listing all image sizes available that were registered using `add_image_size()`.

**Comment by crstauf** [comment]
@desrosj I just added this requested feature to my [Query Monitor Extend](https://github.com/crstauf/query-monitor-extend) plugin:
https://github.com/crstauf/query-monitor-extend/commit/025427f2a19ec137a06e87fd3aa38fe437941776

**Comment by johnbillion** [comment]
Closing this off as it's not something I plan on adding. Cheers!
