### ISSUE TITLE
Should Query Monitor take a break in embeds?

### ISSUE THREAD

**Issue by dcavins** [johnbillion/query-monitor#197]
I'm not sure what behavior is actually desirable, here, but I noticed that Query Monitor is tacking on the monitor report in embed responses. That could be useful or not (and maybe it's intentional). So this is more of a question than an issue.

Thanks for the terrific plugin!

![qm-in-embeds](https://cloud.githubusercontent.com/assets/1391994/15985498/0e70c56c-2fb5-11e6-8039-057268977a53.png)

**Comment by johnbillion** [comment]
Thanks for the message David. This output is indeed intentional and was added in 2.10.0.

As expected, the output only appears when a user with access to QM's output is viewing the embed.

**Comment by dcavins** [comment]
Thanks! I should have read the changelog before opening the issue, where it clearly states that this is a new feature: https://wordpress.org/plugins/query-monitor/changelog/

Sorry for jumping the gun. Thanks again.

**Comment by johnbillion** [comment]
Note: This got removed again in 487e52e because I'm pretty sure nobody uses it and it was more of an annoyance than a help.
