### ISSUE TITLE
Broken Dependencies with Classy Framework

### ISSUE THREAD

**Issue by anrw** [johnbillion/query-monitor#198]
Hey all,

First of all thank you for such a great plugin! 

I am using "Mailchimp for Wordpress" plugin and see that "Query Monitor" tells that there is an error in plugin dependencies.

I have looked in the code and see that its registering properly:

`wp_enqueue_script( 'mc4wp-forms-api', MC4WP_PLUGIN_URL . 'assets/js/forms-api'.  $this->filename_suffix .'.js', array(), MC4WP_VERSION, true );`

Could you please let me know what this issue exactly means and provide some tips on how it can be fixed.

Thank you,
Andrew

<img width="874" alt="screen shot 2016-06-16 at 10 15 13 am" src="https://cloud.githubusercontent.com/assets/7533603/16108862/63865aec-33ae-11e6-8411-981601cb99db.png">

**Comment by johnbillion** [comment]
Thanks for the message. I'll check this out and see if I can find where the problem lies.

**Comment by johnbillion** [comment]
I've tested the Mailchimp for WordPress plugin and when viewing a form I don't see any dependency errors showing up like this.

Are you able to deactivate the other plugins on your site one by one to see if the error disappears? Also there may be an issue with your theme, so you could try switching to one of the default themes (such as Twenty Fifteen).

Do please let me know if it looks like another plugin or theme is causing the problem and I'll look into it.

**Comment by anrw** [comment]
Thanks John,

The problem is caused by my theme. I have custom framework that is based on "Laravel-Blade" template engine. In my opinion, the issue is caused because "Query Monitor" performs checking before my theme gives rendered output.

Is there a way to turn off this checking? Because I don't think that it can be somehow fixed. Anyway, many thanks for your help.

You can also take a look to the framework: https://github.com/anrw/classy

Andrew

**Comment by johnbillion** [comment]
@anrw Can you provide some more information on how your theme works with CSS and JS files please?

QM waits until the `shutdown` hook to determine which dependencies are missing, and collects the list of scripts and styles that were output on the `wp_head` and `wp_print_footer_scripts` actions. If your theme is doing something that means these hooks aren't being used then I suspect your theme won't work correctly with QM.
