### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#20]
Query Monitor does not currently provide a profiling mechanism. Not sure how I want to do this yet. Suggestions/discussion welcome.

See also:
- [TimeStack](https://github.com/joehoyle/Time-Stack/) (WordPress) by Joe Hoyle
- [Hopper](https://github.com/rmccue/Hopper) (WordPress) by Ryan McCue
- [Laps](https://bitbucket.org/Rarst/laps) (WordPress) by Andrey Savchenko
- [Debug Bar Extender](http://wordpress.org/plugins/debug-bar-extender/) (WordPress) by Thorsten Ott
- [Clockwork](https://github.com/itsgoingd/clockwork) (PHP)

**Comment by szepeviktor** [comment]
Very nice.
