### ISSUE TITLE
Less useful stack traces when a database drop-in is in use

### ISSUE THREAD

**Issue by tristanleboss** [johnbillion/query-monitor#201]
Hello,

I am unsure my title is clear but it could be cool if Query Monitor could account for the presence of W3 Total Cache (with the database caching feature enabled) and logs queries as the function really executing them instead of showing "W3_Db->default_query" everywhere.

Indeed, on my site, the "$wpdb Queries" only shows "W3_Db->default_query" in the Caller dropdown. The "Queries by Caller" is also unusable as it only contains one "W3_Db->default_query" line. The "Duplicate Queries" also only contains "W3_Db->default_query" as the caller.

Regards,

Tristan

**Comment by johnbillion** [comment]
Thanks for the message.

QM should already handle this here:
https://github.com/johnbillion/query-monitor/blob/master/classes/Backtrace.php#L24
. It could well be that this has broken at some point though. I'll look
into it.

**Comment by tristanleboss** [comment]
Ok, I did some check (I added a `var_dump($this->trace);` in the class constructor) and it seems this class is only used for the "Languages" table. Indeed, all the traces which appeared on my screen where for: 

'[0]=>
  array(4) {
    ["function"]=>
    string(13) "log_file_load"
    ["class"]=>
    string(22) "QM_Collector_Languages"'

**Comment by tristanleboss** [comment]
Okay, I grepped the plugin folder to find out where the class is used and found out a "db.file":

`./query-monitor/wp-content/db.php:              $this->queries[$i]['trace'] = new QM_Backtrace( array(
./query-monitor/collectors/php_errors.php:              if ( ! class_exists( 'QM_Backtrace' ) ) {
./query-monitor/collectors/php_errors.php:              $trace  = new QM_Backtrace( array(
./query-monitor/collectors/transients.php:              $trace = new QM_Backtrace( array(
./query-monitor/collectors/languages.php:               $trace    = new QM_Backtrace;
./query-monitor/collectors/redirects.php:               $trace = new QM_Backtrace;
./query-monitor/collectors/http.php:            $trace = new QM_Backtrace;`

I then discovered the Wiki page: https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink

The problem is simply due to the fact that, if you use W3 Total Cache with the DB caching feature enabled, W3 Total Cache puts its own `db.php` file in the `wp-content` folder. So, it's impossible to symlink the one from your plugin which contains the required call to `QM_Backtrace`.

BUT, because QM still manages to log the queries without its `db.php` file, I suspect it's just missing a call to the `QM_Backtrace` class in the code which does that.

**Comment by tristanleboss** [comment]
The problem lies here:

https://github.com/johnbillion/query-monitor/blob/master/collectors/db_queries.php#L141

Indeed, because the QM `db.php` is not used, the query lacks a real trace and so fallbacks on the WPDB stack information which is not filtered.

I managed to fix it by adding this piece of code right before line 141:

`				$callers   = array_map('trim', $callers);
				$callers   = array_reverse($callers);

				foreach( $callers as &$caller )
				{
					if( preg_match('%^W3_Db(Cache|CallUnderlying|Driver|Processor)?->%', $caller) )
					{
						$caller = null;
					}
					else
					{
						break;
					}
				}

				$callers   = array_filter($callers);
				$callers   = array_reverse($callers);
`

**Comment by johnbillion** [comment]
This has all been improved in the years since this issue was opened. Cheers!
