### ISSUE TITLE
Fatal Error when activating version 2.11.2

### ISSUE THREAD

**Issue by kshaner** [johnbillion/query-monitor#205]
Using version 2.11.2 installed with wp-cli from the wordpress repo:

( ! ) Warning: require_once(/var/www/wp-content/plugins/query-monitor/classes/Timer.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/query-monitor/query-monitor.php on line 54

Perhaps a file was missed in the svn commit?

**Comment by johnbillion** [comment]
Argh. Thanks. Fix coming up.

**Comment by johnbillion** [comment]
Fixed in 2.11.3 which has just been released to wp.org.
