### ISSUE TITLE
Admin bar node class

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#218]
[Line 101 of `dispatchers/Html.php`](https://github.com/johnbillion/query-monitor/blob/master/dispatchers/Html.php#L101) is ineffectual, for two reasons:

1. there is no class `.hide-if-js` defined in QM's stylesheet
(Note: class is defined in `wp-admin/css/common(-rtl).css` for use in the admin, but there's not on the frontend)

1. `WP_Admin_Bar::add_menu()` expects an array element with key `class`, not `classname`

Didn't want to provide a fix until I knew for sure which behavior was intended: I'm thinking that hiding the QM admin bar menu on the frontend is the desired behavior... can you confirm?

**Comment by crstauf** [comment]
just a follow up here: this is a peculiar issue, as in some cases, `classname` must be used in order for the class to be added, but on the top menu item, using `class` successfully adds `hide-if-js` to the top menu item.

**Comment by johnbillion** [comment]
The `hide-if-js` class is indeed a core class. This looks like a remnant of some old code in QM and, as it doesn't even work, it can be removed.
