### ISSUE TITLE
Plugin names with same beginning conflict in Component filtering

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#223]
Perfect example is Query Monitor (`Plugin: query-monitor`) and Query Monitor Extend (`Plugin: query-monitor-extend`):

![screen shot 2016-08-04 at 9 36 08 pm](https://cloud.githubusercontent.com/assets/4573033/17423759/84e59852-5a8b-11e6-95f5-d2c6e8b83d74.png)

The simple solution is just to add a space (" ") after the component, but wondering if we should consider a less common delimiter, such as `|` or `,`?

**Comment by johnbillion** [comment]
I'm going to close this as it's not something I'm interested in spending time fixing myself, but feel free to open a PR if you find a good solution.

**Comment by johnbillion** [comment]
Closing this off as it's an edge case and it'll ultimately get fixed in #483 when the filtering operates at the data level instead of the display level.
