### ISSUE TITLE
Transient Set Component Always QM

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#224]
Re the attached screenshot, transient component is always reported as `Plugin: query-monitor`. The transients set in the screenshot are set in an mu-plugin, and a theme file.

![screen shot 2016-08-05 at 2 06 15 am](https://cloud.githubusercontent.com/assets/4573033/17427787/55bbbd9c-5ab1-11e6-9509-7bd39eb5a3f9.png)

In my experimenting, it seemed that removing the `'ignore_items' => 1` from the `QM_Backtrace` call ([L48 of `collectors/transients.php`](https://github.com/johnbillion/query-monitor/blob/master/collectors/transients.php#L48)) fixed the issue, which leaves me puzzled, but it seems correct:

![screen shot 2016-08-05 at 2 21 52 am](https://cloud.githubusercontent.com/assets/4573033/17428052/65ebafa4-5ab3-11e6-8724-0e382cfaa0a3.png)

Can anyone confirm?

**Comment by crstauf** [comment]
Notice: QMX fixes this issue, so make sure to deactivate QMX when diagnosing.

**Comment by johnbillion** [comment]
I've seen this too. Needs some investigation.

**Comment by johnbillion** [comment]
Is this still an issue since QM 2.16?

**Comment by crstauf** [comment]
@johnbillion Actually, I'm currently running QM 2.15, and it appears to be correct there as well.
![screen shot 2017-11-01 at 11 34 55 pm](https://user-images.githubusercontent.com/4573033/32308656-6468c396-bf5d-11e7-86cc-e933f72f1d98.png)

**Comment by johnbillion** [comment]
Thanks!
