### ISSUE TITLE
setting the $current_user variable prevents query monitor from showing up

### ISSUE THREAD

**Issue by miczed** [johnbillion/query-monitor#229]
Hi

I just had a strange issue today. In a custom wordpress page-template I had the following line:
`$current_user = get_current_user_id();`

However this line prevented Query Monitor from showing up on the page. I guess the variable `$current_user` is used by Query Monitor and if I overwrite it, something breaks.

I changed the variable in my code to `$currentUser` and now Query Monitor works like a charm. I am not sure if this behavior is intended by the creator of this plugin so this might be something you could fix in the future.

Anyway if somebody is running into a similar issue, just rename your variable.

**Comment by crstauf** [comment]
@miczed `$current_user` is a global variable, used by `wp_get_current_user()`, so when you change it, it affects the entire system. QM does a test to see if the current user (which is technically the user in `$current_user`, not necessarily the actual user) can view QM (`current_user_can('view_query_monitor')`), if the user stored in `$current_user` does not have that privilege, QM will not show.

your solution is correct: use a different variable name.

**Comment by crstauf** [comment]
https://github.com/johnbillion/query-monitor#who-can-see-query-monitors-output

**Comment by miczed** [comment]
Ok so it was very stupid from me to overwrite that variable anyway. Thanks for pointing that out! 
So I guess we can close this. 

QM is a superb plugin! It helped me to speed up my site by more than 50%. Thank you guys for developing such an awesome plugin.
