### ISSUE TITLE
Show PHP error as notice in backend

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#231]
Will be a not bad idea to integrate https://gist.github.com/Mte90/c869ed85661d65b8c1b0 in query-monitor, in that way we can avoid for that feature to install a specific plugin.

**Comment by johnbillion** [comment]
QM collects errors and lists them in its own error panel. What's the need to output them inline?

**Comment by Mte90** [comment]
Well to see the errors we need to open the big panel of query monitor, in that way they are showed as notice in the wordpress panel.
But I understand that will be a duplicate of the same information in the same page.

**Comment by johnbillion** [comment]
Thanks for the suggestion, Daniele, but I'm not interested in implementing this in QM. Displaying errors inline can mess up the layout -- displaying them all in one place in QM's error panel prevents this.

Cheers
John
