### ISSUE TITLE
Fatal Error on Activation

### ISSUE THREAD

**Issue by w00tw00t111** [johnbillion/query-monitor#237]
Hey @johnbillion ,

I've had success with query-monitor on another site, but when I went to install it on a new site from the Wordpress repo (this is self hosted WP site) on activation I get the following error message:

Fatal error: Class QM_Collectors contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (IteratorAggregate::getIterator) in /home/ralwebsite/public_html/wp-content/plugins/query-monitor/classes/Collectors.php on line 62

You can see the error below:
![error](https://cloud.githubusercontent.com/assets/2299680/19109850/cbbce2ba-8abc-11e6-8c09-063bcc72faf1.png)

The details of the environment:
PHP 5.4.45
WP 4.6.1

Hope that is enough information to be of assistance. Let me know if I can try anything to help debug.

**Comment by johnbillion** [comment]
Thanks for the message. The `QM_Collectors` class doesn't contain any abstract methods, and it implements all of its interface's methods, so I think this error must be down to a local issue on your site or your server.

Can you try re-downloading QM in case your download was somehow broken?

**Comment by w00tw00t111** [comment]
@johnbillion 
Thanks for replying :)

Yes - I tried a few different things. One - downloading via the plugins in the WP admin. Deleting re-downloading.

Then downloading directly from the git repo and installing.

Then using an older version (2.12.0) that was installed on another server - installed that and it threw the same error.
:/

**Comment by johnbillion** [comment]
I just tested this on a PHP 5.3 install and saw no problems. Currently provisioning a 5.4 install for testing.

**Comment by w00tw00t111** [comment]
Am cloning a copy of the site that it isn't working on - to a site that it
is working on.

Will test that and then remove all plugins except QM to see if that is an
issue.

Will report back in a moment.

Thanks!

**Comment by w00tw00t111** [comment]
Just tested the clone - basically just used ManageWP to clone the site that was having a problem to another domain, on another server, etc.

Query Monitor worked without a problem. All of the plugins, themes, database etc were copied over so in theory the WP files and DB are absolutely identical.

Both servers are on the same version of centOS, etc.

Do you know if there is a server configuration that could be artificially throwing this error?

**Comment by johnbillion** [comment]
I just tested this on 5.4 and also saw no problems.

I guess there's a configuration somewhere that's messing this up, but I've no clue what it could be. I'll continue having a search around to see if I can come up with anything.

**Comment by w00tw00t111** [comment]
Same here

I'm talking with my host now to see if there is a php / server setting that
could affect this.

**Comment by w00tw00t111** [comment]
John, determined the issue. PHP FPM was failing and needed to be restarted.

Why that was causing an issue and throwing that error is beyond me.

Thanks for the time in trying to debug it.
