### ISSUE TITLE
Ability to silence PHP errors from selected plugins

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#239]
When working on a site where you're not 100% in control of all the code -- for example, shared plugins on the WordPress.com VIP platform -- it can be annoying to see a persistent notification for PHP notices caused by poor code.

QM should provide a feature to mute specific error levels for specific components via a filter. For example:

``` php
add_filter( 'qm/collect/silent_php_errors', function( array $silent ) {
    $silent[ 'chartbeat' ] = E_NOTICE & E_STRICT;
    $silent[ 'theme' ]     = QM_E_DEPRECATED;
    return $silent;
} );
```

This should work similarly to the silencing of the HTTP API when Airplane Mode is active, and the silencing of `@-` suppressed PHP errors. They errors should still be listed but shouldn't trigger a notification in the admin toolbar.

**Comment by crstauf** [comment]
+1

**Comment by ivdimova** [comment]
According to the issue description above I am not sure what should happen if the plugin errors are silenced - only the background color in the admin toolbar to stay the same or also the menu notification to be hidden - screenshot attached. @johnbillion please advice.
![screen shot 2017-11-24 at 12 35 43 pm](https://user-images.githubusercontent.com/465636/33206775-0b7f322e-d114-11e7-9e6b-c74d83304cb2.png)

**Comment by johnbillion** [comment]
Fixed in #287 for version 3.0.0.

**Comment by crstauf** [comment]
@johnbillion I really like this feature, but it's not very visible (as far as I can tell). 

Thoughts on if it can/should be added to readme?

**Comment by johnbillion** [comment]
I [blogged about it](https://querymonitor.com/blog/2018/07/silencing-errors-from-plugins-and-themes/) but nobody reads that blog. I'll add something to the readme.
