### ISSUE TITLE
QM sections not visible with upcoming Twenty Seventeen theme

### ISSUE THREAD

**Issue by ihorvorotnov** [johnbillion/query-monitor#242]
Twenty Seventeen default theme is coming pretty soon. However, it's nearly impossible to work with QM and this theme - the new fixed header image design conflicts with QM styles (or vice versa?)

<img width="1437" alt="screen shot 2016-11-29 at 18 12 19" src="https://cloud.githubusercontent.com/assets/1066083/20717833/816be6d8-b65f-11e6-95fb-96a249d5a6b0.png">

**Comment by ihorvorotnov** [comment]
I understand, if there's a conflict with a theme, the theme itself is the part that should be modified. However, in this case this is the new default WP theme for next year. I believe, QM should work fine with it out of the box.

**Comment by johnbillion** [comment]
Thanks, I noticed this too and the next version of QM will include a fix for this.

**Comment by johnbillion** [comment]
This has been fixed in the latest version of QM. The code isn't appearing on GitHub yet due to some ongoing service outage, but the version on w.org has been updated.
