### ISSUE TITLE
Site offline - Fatal Error

### ISSUE THREAD

**Issue by TeoS9** [johnbillion/query-monitor#243]
Hi everyone!

Please I really need your help. I just installed Query monitor on the website I was working on, 
http://www.nisivoccia-architettura.com/
with Slider Responsive theme and my site went offline. 
How can I "get it back"? I can't access to anything. How can I put it online again?

Thank You

**Comment by shinerweb** [comment]
TeoS9:  If you login to your server's control panel, and use the File Manager, or, use FTP and login to your site, you can navigate to the plugins folder and simply delete the Query plugin sub-folder (i.e. delete the Query folder and NOT the top level Plugin folder).
WordPress will detect the plugin is no longer there and disable it and your site should come back online again.

You'll find the plugin folders somewhere like:

public_html/wp-content/plugins     (providing you haven't set up unique paths).
