### ISSUE TITLE
Issue Xdebug and Query Monitor

### ISSUE THREAD

**Issue by feekApp** [johnbillion/query-monitor#248]
Hi,

I've set in Xdebug the ability to open the file with an php-error with your code-editor:
```
xdebug.file_link_format="txmt://open/?url=file://%f&line=%l"
```
But this Xdebug functionality does not work anymore when Query Monitor is activated. 

![image](http://feek.d.pr/RAl0.jpg)

In my case I have an error in line 217 of file `function.php`. When Query Monitor is disabled, the filename have a link url `txmt://open/?url=file.....` in order to open the file `function.php` in TextMate (see image on the top).

But when Query Monitor is activated `function.php` is not wrapped with a link to the file, but the file `query-monitor/collectors/php_errors.php` on line 164 (see image on the bottom).

Hope you can fix this.

Regards,
Feek

**Comment by johnbillion** [comment]
Yeah this is an unfortunate side effect of the way QM deals with PHP's error handling. I've not found a way around it yet.

If you look at the individual items in the stack trace, you can still click the links there with no problem.
