### ISSUE TITLE
(Possible) Incorrect reporting on query time

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#249]
The query below is reported by QM as completing in 0.0003 "time" (seconds I'd presume), however, phpMyAdmin reports the query completing in 0.036 seconds.

`SELECT option_value FROM wp_options WHERE option_name = '_site_transient_update_core' LIMIT 1`

That's about all the information I have, unfortunately. Anyone have any thoughts?

**Comment by johnbillion** [comment]
I presume you've run the query over and over multiple times. Is there much variance?

**Comment by crstauf** [comment]
Variance (according to phpMyAdmin) is 0.0015 seconds. There has been no variance I have seen according to QM. And to be clear, that query is not the only one reporting differently from phpMyAdmin: https://cloudup.com/c3qYLAEv-OM

**Comment by johnbillion** [comment]
I'm not sure that there's much that can be done here. QM doesn't log the query time itself, rather it uses the time recorded by WordPress core: https://github.com/WordPress/wordpress-develop/blob/d570de32ca3a5f623bf26d70dfc55141c339073d/src/wp-includes/wp-db.php#L1796-L1820

I've no idea why there would be such a large variance when running that query in phpMyAdmin, but I would suggest running the query on the mysql command line and seeing what sort of numbers you get there.
