### ISSUE TITLE
Open in a new window (popup)

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#251]
I was thinking that sometimes I prefer to have the output of query monitor in a new window or popup to avoid a long page and have the wp page in different view so can be more productive.
I was thinking to do also that a support of the refresh of the window need to be happen also in the popup.

I think that is easy to do with communication between a window and another one in pure js.

**Comment by johnbillion** [comment]
Thanks for the suggestion Daniele but I'm going to close this for now as it's not something I have any plans to work on. I much prefer your browser dev tools solution anyway :-)

**Comment by Mte90** [comment]
I think that now is in javascript the UI is not so difficult to move that in a popup.
So we can deprecate the browser extension for the moment.

``` function openWin(id) {
     var divText = '';
     divText = '<link rel="stylesheet" href="' + document.getElementById("query-monitor-css").getAttribute('href') + '" type="text/css" media="all">';
     divText = divText + '<script type="text/javascript" src="http://demo.test/wp-includes/js/jquery/jquery.js?ver=1.12.4"></script>';
     divText = divText + '<script type="text/javascript" src="http://demo.test/wp-content/plugins/query-monitor/assets/query-monitor.js?ver=1523541389"></script>';
     divText = divText + document.getElementById(id).innerHTML;
     myWindow=window.open('','','width=700,height=700');
     var doc = myWindow.document;
     doc.open();
     doc.write(divText);
     doc.close();
 }


openWin('query-monitor')
```
An example code that copy the html but is not working.
I am thinking to add a message on the browser extension to say that is deprecated and this feature will be very comfortable on switching.
