### ISSUE TITLE
Javascript error on admin page

### ISSUE THREAD

**Issue by kingmaryjonatan** [johnbillion/query-monitor#252]
Probably a collision of templates or such. But a heads up.

Error in console:

`Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.<anonymous> (query-monitor.js?ver=1489654149:67)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)`

Error in code (qm.menu.top.classname) variable.

`if ( $('#wp-admin-bar-query-monitor').length ) {
		var container = document.createDocumentFragment();
		$('#wp-admin-bar-query-monitor')
			.addClass(qm.menu.top.classname)
			.find('a').eq(0)
			.html(qm.menu.top.title);`

Wordpress 4.7.3
Query monitor 2.13.4

**Comment by johnbillion** [comment]
Thanks for the report. Can you check your PHP error logs for fatal errors and try deactivating all your other plugins one by one to see where the issue is?

**Comment by kingmaryjonatan** [comment]
Found the PHP Errors:

`Fatal error: Uncaught TypeError: Argument 1 passed to QM_Output_Html_Assets::dependency_row() must be an instance of _WP_Dependency, boolean given, called in /var/www/himlabadet.dev/site/public_html/app/plugins/query-monitor/output/html/assets.php on line 117 and defined in /var/www/xx/site/public_html/app/plugins/query-monitor/output/html/assets.php on line 125`

`TypeError: Argument 1 passed to QM_Output_Html_Assets::dependency_row() must be an instance of _WP_Dependency, boolean given, called in /var/www/himlabadet.dev/site/public_html/app/plugins/query-monitor/output/html/assets.php on line 117 in /var/www/himlabadet.dev/site/public_html/app/plugins/query-monitor/output/html/assets.php on line 125`

**Comment by johnbillion** [comment]
Thanks. Either your theme or a plugin on your site may be doing something wrong with the scripts and styles dependency system. If you can narrow it down then I can take a look to see whether it's a valid use case that QM needs to handle, or whether the plugin/theme is doing something wrong.

Can you try switching to one of the default themes to see if the error persists? If so, try deactivating your plugins one by one to see if you can identify which one causes the issue.

**Comment by kingmaryjonatan** [comment]
Yes, it's probably theme related.

Thanks i will look into it :)
