### ISSUE TITLE
Issue on LocalHost!

### ISSUE THREAD

**Issue by ahmadawais** [johnbillion/query-monitor#254]
I see this issue in the debug log which makes it harder to keep an eye on other errors. Can you check?

```php


array_diff(): Argument #1 is not an array
 Type: PHP Warning Line: 50
 File:local.dev/wp-content/plugins/query-monitor/collectors/assets.php

```

**Comment by johnbillion** [comment]
This usually indicates that a plugin or theme on your site is breaking the script or style dependencies. Can you try deactivating your plugins one by one to see which one is causing the problem?

**Comment by ahmadawais** [comment]
The issue is, I am not sure how to reproduce this error. It is not like that it occurs on every page load. Any insights into that?

**Comment by johnbillion** [comment]
You could try installing XDebug, which will give you a full stack trace for each error that gets logged. This will hopefully help you pinpoint the problem.
