### ISSUE TITLE
Warning: array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by grappler** [johnbillion/query-monitor#257]
`Warning: array_flip(): Can only flip STRING and INTEGER values! in /collectors/request.php on line 67`

The array comes from the `wporg-developer` theme. The values are defined in [`Devhub_Handbooks::add_query_vars`](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-developer/inc/handbooks.php#L64) 

```
array(5) {
  ["is_handbook"] => bool(false)
  ["current_handbook"] =>bool(false)
  ["current_handbook_home_url"] =>bool(false)
  ["current_handbook_name"] => string(0) ""
  ["empty_post_type_search"] => bool(false)
}
```

Related https://github.com/johnbillion/query-monitor/issues/146

**Comment by johnbillion** [comment]
Thanks for the ticket.

`Devhub_Handbooks::add_query_vars()` is at fault here. The `query_vars` filter expects an array that contains query vars in the array values, not in the array keys.

**Comment by grappler** [comment]
Thanks, I opened a ticket for it https://meta.trac.wordpress.org/ticket/2882
