### ISSUE TITLE
Issues with link

### ISSUE THREAD

**Issue by uhlhosting** [johnbillion/query-monitor#259]
[root@panel poisonbite]# ln -s /home/poisonbite/public_html/wp-content/plugins/query-monitor/wp-content/db.php /home/poisonbite/public_html/wp-content/db.php
ln: creating symbolic link `/home/poisonbite/public_html/wp-content/db.php': File exists
[root@panel poisonbite]#

$wpdb Queries
Extended query information such as the component and affected rows is not available. Query Monitor was unable to symlink its db.php file into place. See this wiki page for more information.

**Comment by johnbillion** [comment]
Note the result of the `ln` command telling you that the file exists already. Please see the section at the bottom of the wiki page.
