### ISSUE TITLE
Use `map_meta_cap` or `user_has_cap` filters for capabilities checking

### ISSUE THREAD

**Issue by mboynes** [johnbillion/query-monitor#261]
I ran into an issue today trying to use QM on a site using the `$wp_user_roles` global to define roles and capabilities. Because QM only adds its custom capability on activation, if a site uses this global (or ever resets roles and capabilities), QM will be hidden.

You might consider using either the `map_meta_cap` or `user_has_cap` filters to check this custom capability instead of adding it on activation.

**Comment by johnbillion** [comment]
Yep I definitely want to do this. The activation hook has been a pain since day one.
