### ISSUE TITLE
At refresh after open the view #qm-php-errors remain in the url

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#267]
With javascript is possible to remove this terms from the url and avoiding confusion because the view is not opened automatically (open with a click and not with the presence of the hash).

**Comment by johnbillion** [comment]
Sì, you're correct Daniele, this would be a good feature. WordPress core does this with messages in the admin area (`wp_admin_canonical_url()` function).

**Comment by Mte90** [comment]
Maybe the best way is to remove the anchors in the url when the user click to open the view

**Comment by johnbillion** [comment]
Fixed in 3.0.
