### ISSUE TITLE
Missing javascript

### ISSUE THREAD

**Issue by Colir** [johnbillion/query-monitor#271]
Hi.
First at all thank you for this really helpful plugin.

Query Monitor show me a warning on script & css

I actually deregister js and Css form a plugin (CF7 polylang) like this
`
function deregister_plugins_file(){
	wp_deregister_style('cf7-polylang');
	wp_deregister_script('cf7-polylang');
}
add_action('wp_enqueue_scripts', 'deregister_plugins_file');
`
However Query Monitor show me an alert on this file : 

`
Position | Script
Missing | cf7-polylang
`

Can you please help me to know what i'm doing wrong ?

thank you

**Comment by johnbillion** [comment]
You're deregistering a script without also unenqueing it, hence the missing script error.

If you need any more help, please post on the public support forums at wordpress.org/support. I can't provide support for every error that QM shows you.

**Comment by Colir** [comment]
ok i understand. thanks you, i will post on wp support.
