### ISSUE TITLE
Function 'get_singular_template' not found or invalid function name in collectors/theme.php

### ISSUE THREAD

**Issue by Dartui** [johnbillion/query-monitor#276]
Today I have installed Query Monitor on site with WordPress 4.1. `get_singular_template` function was introduced to WP in 4.3, so I am getting this warning:
`call_user_func() expects parameter 1 to be a valid callback, function 'get_singular_template' not found or invalid function name in wp-content/plugins/query-monitor/collectors/theme.php:69`

**Comment by johnbillion** [comment]
Thanks for the report. I'll get this fixed.
