### ISSUE TITLE
Implement ARIA state on toggle buttons

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#278]
The buttons for toggling open stack traces and other information should implement the correct ARIA attributes and state so they are more accessible.

I'm not sure on specifics, but here's some starting info: https://www.w3.org/WAI/GL/wiki/Using_WAI-ARIA_state_and_property_attributes_to_expose_the_state_of_a_user_interface_component#Example_1:_A_toggle_button

**Comment by rianrietveld** [comment]
Commented with #285: this needs `aria-expanded`, not `aria-pressed`.

**Comment by ivdimova** [comment]
I assume we can close this one @johnbillion ?

**Comment by johnbillion** [comment]
Fixed in #285
