### ISSUE TITLE
Document hooks and filters

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#279]
QM contains a bunch of hooks and filters. These all need docblocks that adhere to the WP documentation standards.

**Comment by jocastaneda** [comment]
I started a quick brang: https://github.com/johnbillion/query-monitor/compare/master...jocastaneda:component/documentation

There are a few things I know I missed and the phrasing on a few may need to change. The only thing I haven't done is added the version when the hook was introduced. I'll try and dig up when later today though.

**Comment by johnbillion** [comment]
@jocastaneda Thanks! Feel free to open a PR when you think it's ready. I'm not too worried about the `@since` tags for now, they can always be added in later.

**Comment by jocastaneda** [comment]
Will do.

I've found a decent way of getting them so I have a few of them already added.

**Comment by johnbillion** [comment]
Fixed in #356
