### ISSUE TITLE
CSS breaks mobile view

### ISSUE THREAD

**Issue by Beee4life** [johnbillion/query-monitor#280]
If you're developing in Chrome and use the responsive view, the site will break (on screens smaller than 800px) if you have deactivated the top admin bar.

When a screen size is smaller than 800 px #qm kicks in (line 138 of query-monitor.css). 
The width is 'forced' to min-width: 800 px.

This can be easily fixed by removing line 138 ( changing it so it won't stretch).

**Comment by johnbillion** [comment]
Thanks for the report. I'll see what I can do about this, but it's low priority.

**Comment by Beee4life** [comment]
I understand.... it's not a too big of an issue if you're aware.... 
plus adding 2 slashes fixes the issues (temporarily) if someone's too bothered by it.

**Comment by eddr** [comment]
here too

**Comment by johnbillion** [comment]
This should be greatly improved with the new UI in 3.0.

**Comment by Beee4life** [comment]
Great to hear. Will check out 3.0.
