### ISSUE TITLE
Divi theme customizer won't load with active QM

### ISSUE THREAD

**Issue by Albiik** [johnbillion/query-monitor#281]
Hi
I discover that Divi theme (elegantthemes.com) can't be customized with active QM. Menu Appearance|Customize doesn't load (only blank page - see screen) with active QM plugin. With disabled QM menu work. 

I test it on several sites some combinations updates wordpress, divi theme and QM plugin. This bug is independent on wordpress and divi version (last 3 updates). Last version QM which work is 2.15.0 - this version work with latest update WordPress 4.8.3 and DiviVersion: 3.0.86.  QM version 2.16.0-2.16.2 doesn't work. 

I try other themes from elegant Twenty Fifteen etc. and they work OK. I tried delete divi theme and upload new version, without success.

![qm-active](https://user-images.githubusercontent.com/33499359/32578010-f38e8b72-c4db-11e7-9b18-dde10da6e525.jpg)

**Comment by johnbillion** [comment]
This most likely has the same root cause as #269.
