### ISSUE TITLE
PHP functions running times?

### ISSUE THREAD

**Issue by eddr** [johnbillion/query-monitor#282]
Hi man, great plugin. It's really next level of WP development

Wanted to ask - any chance you'll add in the future performance indicators for the PHP functions?

EDIT: I see now that you said you'll probably add such functionality

**Comment by johnbillion** [comment]
Thanks for the suggestion.

This isn't something that I'm planning on adding to QM, although it is possible to do via ticks in PHP but the overhead is significant (which skews the profiling). It would need to be an opt-in feature, or an add-on plugin.

What I _am_ planning on adding is an API so developers can perform profiling of their own code using something along the lines of this:

```php
do_action( 'qm/start', 'foo' );
my_long_running_function();
do_action( 'qm/stop', 'foo' );
```

It would support laps too:

```php
do_action( 'qm/start', 'foo' );
foreach ( $items as $item ) {
	do_something();
	do_action( 'qm/lap', 'foo' );
}
do_action( 'qm/stop', 'foo' );
```

The timing and memory usage information for this profile would then be output in a panel in QM.

No ETA for this feature just yet.

**Comment by crstauf** [comment]
@eddr [QMX](https://github.com/crstauf/query-monitor-extend) supports adding benchmarks in your code, and displaying them in QM (though I **strongly** look forward to @johnbillion's implementing into QM).

**Comment by eddr** [comment]
@crstauf thanks man, I appreciate the help!
I would probably wait

**Comment by johnbillion** [comment]
First pass of this is now in the develop branch. See #301.
