### ISSUE TITLE
Debugging PDF Thumbnail Support

### ISSUE THREAD

**Issue by grappler** [johnbillion/query-monitor#283]
PDF Thumbnails require Imagick, Imagemagick, and Ghostscript to work. Would it be possible to list the versions in the Environment section?

I could install [Debug Media](https://wordpress.org/plugins/debug-media/) but I would prefer not to use [the Debug Bar plugin](https://wordpress.org/plugins/debug-bar/).

I am not sure if it something you want to support in Query Monitor.

**Comment by johnbillion** [comment]
Yep I can look into adding the extension versions. Extensions are listed currently in the Environment panel but the versions aren't shown.

If you activate any Debug Bar extension, Query Monitor will take over its display of you don't have Debug Bar activated.

**Comment by grappler** [comment]
> Extensions are listed currently in the Environment panel but the versions aren't shown.

Ah, I missed it because they were all hidden. Maybe instead of adding the version number it may be better to add a comment that PDF Thumbnails are supported depending if Imagick, Imagemagick, and Ghostscript are enabled.

> If you activate any Debug Bar plugin, Query Monitor will take over its display if you don't have Debug Bar activated.

Thanks! I now remeber this being mentioned before.

**Comment by johnbillion** [comment]
> it may be better to add a comment that PDF Thumbnails are supported

Good idea. I think QM could do this for a few areas in WordPress, eg. PDF thumbnails, EXIF, OpenSSL.

**Comment by johnbillion** [comment]
This is not going to happen any time soon, sorry.
