### ISSUE TITLE
Undefined index ltime

### ISSUE THREAD

**Issue by Beee4life** [johnbillion/query-monitor#284]
I just noticed the following error.

<img width="1269" alt="screen shot 2017-11-21 at 23 15 44" src="https://user-images.githubusercontent.com/4508731/33100229-ec4d9eba-cf13-11e7-917d-1238c1edd59a.png">

**Comment by johnbillion** [comment]
Thanks for the report! I'll close this as a duplicate of #266 because it's probably the same cause.

**Comment by Beee4life** [comment]
Sorry for the duplicate, missed it.
