### ISSUE TITLE
Memory error because of capabilities check

### ISSUE THREAD

**Issue by remcokalf** [johnbillion/query-monitor#288]
When loading my posts page in WP backend, I hav 5+ seconds load times, and memory is exhausted. With 256Mb allocated in htaccess, I get a white screen and server error:

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 6189056 bytes) in xxxx/public_html/wp-content/plugins/query-monitor/output/html/caps.php on line 147

Changing to 512Mb fixes the whitescreen but loading is unacceptable.
Yes, it's a large website, but I previously did not have any problems. This is new since my last update of QM.

edit:
I see others having the same issue:
https://wordpress.org/support/topic/peak-memory-usage-incrase-since-2-16-x/
I am on 2.17.0.

A setting to disable certain panels, in this case capabilities would also be an idea.

**Comment by johnbillion** [comment]
Yeah unfortunately this new panel has caused memory issues for several people. If you check out the `develop` branch, memory usage is quite a bit better, but still not great.

**Comment by lkraav** [comment]
@remcokalf you could filter out the caps collector via `add_filter qm/built-in-collectors`.

**Comment by johnbillion** [comment]
> you could perhaps set the array keys to the file basename

Good idea. #297.

**Comment by johnbillion** [comment]
Fixed in d523733
