### ISSUE TITLE
Allow running QM without jQuery dependency

### ISSUE THREAD

**Issue by hors-lignes** [johnbillion/query-monitor#289]
For Wordpress development where jQuery is not a vital tool (it is already the case since a while), it could be nice to unregister it without a Query Monitor complain.

**Comment by johnbillion** [comment]
Yeah I've tried this before but unfortunately the code for the sorting and filtering controls in QM is pretty complex and would take a great amount of work to port away from jQuery.

I'll close this for now as I don't have any plans to tackle this, but of course patches welcome!

**Comment by 27pchrisl** [comment]
Although jQuery is required, QM loads 'jquery' which depends on 'jquery-migrate' (unnecessarily I think), so this could be one less HTTP request.

**Comment by crstauf** [comment]
@johnbillion Perhaps an alternative would be a constant that loads QM without jQuery (disabled sorting and filtering)? I know I've been interested a couple of times to get a more accurate reading on how the actual page is, without the loading of jQuery; I'd be willing to give up sorting and filtering in those situations, for a more accurate analysis of the page.

**Comment by johnbillion** [comment]
I can get behind that.
