### ISSUE TITLE
Output causes problems on sites running WPBakery Page Builder

### ISSUE THREAD

**Issue by lumpysimon** [johnbillion/query-monitor#290]
When using WPBakery Page Builder's front end editor, QM's output obscures the content and the WPBakery toolbar, making it difficult to edit and impossible to save any changes.

![qm-bakery](https://user-images.githubusercontent.com/625372/33826365-a3dfd410-de5c-11e7-9ac5-777205667502.png)

Maybe QM could be disabled on pages where the `vc_action` query var is set with a value of `vc_inline`?

**Comment by johnbillion** [comment]
Can you try the previous version of QM (`2.6.2`) and let me know if the problem still occurs? In `2.7` I [switched from absolute positioning to relative](https://github.com/johnbillion/query-monitor/commit/8a127de8c7c806afd6a2b24f07df415350e5c1dc) to avoid issues with some default themes.

**Comment by lumpysimon** [comment]
Yep, works fine with `2.16.2`

**Comment by johnbillion** [comment]
This should be greatly improved with the new UI in 3.0.
