### ISSUE TITLE
[Feature request] Allow admin menu position

### ISSUE THREAD

**Issue by shivapoudel** [johnbillion/query-monitor#294]
I want to debug registered admin menu position assigned in Admin Screen if QM. If I will visit Apperance page then its menu position is 60 and just like that I want to know the third-party plugins menu position :)

**Comment by johnbillion** [comment]
I've thought about this and I've decided it's not something that I'm planning on adding to QM. Thanks for the suggestion, though!

If you want to write an add-on plugin there are some examples here: https://github.com/johnbillion/query-monitor/wiki/Query-Monitor-Add-on-Plugins
