### ISSUE TITLE
Query Monitor conflict with Timber Debug Bar

### ISSUE THREAD

**Issue by Beee4life** [johnbillion/query-monitor#295]
I just noticed that the plugin doesn't show any values and there is no on click action available (at least nothing shows) when I'm viewing a particular post type archive (event created by [Events Manager](http://wp-events-plugin.com/)).

It only shows this:
<img width="137" alt="screen shot 2018-01-01 at 20 08 02" src="https://user-images.githubusercontent.com/4508731/34470332-873252f0-ef2f-11e7-967b-e48656f33f40.png">

I switched to other templates and it works there, so it's theme related.
I deactivated several js/php functions to see if that would trigger it, but no dice yet.

Any idea what might cause this ??

**Comment by ihorvorotnov** [comment]
Usually, when you see only "Query Monitor" link and it's not clickable it means there's some javascript error. Check your browser console, find the error and fix it, QM will work again.

**Comment by Beee4life** [comment]
Thanks for the reply @ihorvorotnov 

That was my first guess as well, but I can't find any js errors yet in my console, hence why I turned here.

**Comment by johnbillion** [comment]
Thanks for the report. Are there any fatal errors in your PHP error log?

**Comment by Beee4life** [comment]
I don't think so otherwise I would have posted them here. Always have a tail -f running to monitor logs.... Will check again on short term.

**Comment by Beee4life** [comment]
It took a while to test... No errors appear. 

I found out the [Timber Debug Bar](https://github.com/timber/debug-bar-timber) is the culprit here. When I deactivated this, it showed again. I made a note of it in [this topic](https://github.com/timber/debug-bar-timber/issues/14).

**Comment by johnbillion** [comment]
Thanks for the follow-up. This may still be caused by QM, so I'll reopen this until I have time to investigate.

**Comment by Beee4life** [comment]
Any updates reg this ? Just noticed it again... which made me think of this topic.

**Comment by johnbillion** [comment]
I'll see if I can find some time to check it out. No promises though!

**Comment by Beee4life** [comment]
I understand.

**Comment by Beee4life** [comment]
@johnbillion have you ever found some time to look into this ?

**Comment by johnbillion** [comment]
No I haven't, I'll add it to the next minor milestone to remind me to look into it.

**Comment by johnbillion** [comment]
I've been trying to reproduce this problem with no luck.

I'm running the Timber starter theme, Timber Debug bar, and Events Manager, and haven't seen any problem with the QM menu.

Are you able to narrow this down any further?

**Comment by Beee4life** [comment]
I will look into it again and see what's happening.... will get back to you.
