### ISSUE TITLE
Contract long file paths

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#302]
One thing that causes the layout of QM to easily get messed up is long file paths. Here are two examples:

![query-monitor-queries](https://user-images.githubusercontent.com/208434/34872545-280af05e-f789-11e7-8b06-d10962f0c0cf.png)

![x17fbk](https://user-images.githubusercontent.com/208434/34872589-5d446f7a-f789-11e7-9c8c-510862c8f90d.jpg)

What can be done in order to display these file paths better and/or make them shorter?

Options: (which aren't exclusive to one another)

* Strip the leading `wp-content/plugins` and `wp-content/themes` segments.
* Contract the file path (see below).
* Don't display the file path at all, put it behind a toggle.

The iTerm2 app for Mac contracts file paths in the `Recent Directories` pane by shortening each segment of the path. For example, this file path:

    /sites/fresh/branches/4.8/src/wp-includes/rest-api/fields

can end up being displayed as:

    /s/f/b/4/s/w/rest-api/fields

This behaviour is okay, but I would rather not contract the first segment of the path because it can be an important piece of information when the user wants to open the file.

On a related note, I've seen some apps which shorten function names when they contain namespaces. For example:

    \My\Long\Plugin\NameSpace\App\function_name()

can be shown as:

    \My\...\App\function_name()

Thoughts and ideas welcome.

**Comment by ivdimova** [comment]
I personally support the idea of a toggle button or any other idea of showing the full path on request. If the leading `wp-content/plugins` and `wp-content/themes` segments are stripped this may cause confusion in case some of these folders are renamed - slightly possible but still an option. Same is valid for shortening the paths - the way this is being displayed in the end may not be familiar to the user and cause additional confusion. With a toggle button the path will be displayed only if needed and in all other cases the layout will be consistent. @johnbillion

**Comment by ihorvorotnov** [comment]
Maybe smth very short like `/ ... /file.php`, where `...` is a link that toggles full path on click?

**Comment by crstauf** [comment]
In QMX, I've taken to showing the last few directories (including the filename) in the cell, and putting the full path in the `title` attribute.

**Comment by johnbillion** [comment]
I've decided not to do anything with this for now. QM 3.0 hides most paths behind a toggle by default, which mostly eliminate the problem of suboptimal layouts.
