### ISSUE TITLE
Improve output on error log

### ISSUE THREAD

**Issue by Mte90** [johnbillion/query-monitor#304]
I made this little plugin -> https://gist.github.com/Mte90/e09a84a4e1c61690e55b3a6e0c67ef94
Can be used as mu-plugins, so you put this file automatically is loaded by wordpress and the log contain more info that are useful for WordPress.
Like the url where the error is happening and the filter (usually errors about a filter can show as reference the wrong file).

I added support for Query-Monitor so can be used also with this plugin.
I think that the output in log of query monitor can be improved in this plugin, maybe with a constant.

**Comment by johnbillion** [comment]
I can see this being useful but I don't think it belongs specifically in QM. There are plenty of tools that override the logging and I don't want Qm to muddy those waters.
