### ISSUE TITLE
db.php problem when migrating sites

### ISSUE THREAD

**Issue by davidfavor** [johnbillion/query-monitor#305]
Normally QM rm db.php + plugin deactivate + plugin activate fixes this problem.

Current version of QM reports common db.php problem + the above doesn't fix the problem.

The result of the above steps.

1) db.php never recreates.

2) Error message still refers to old db.php incorrect symlink, even though db.php is gone.

3) Recreating link via manual **ln -s** causes error message to persist.

Runtime environment...

QM - 2.17.0

```
PHP 7.1.12-3+ubuntu17.04.1+deb.sury.org+1 (cli) (built: Dec 14 2017 15:38:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-3+ubuntu17.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
Completely deleting QM + removing all traces of plugin + reinstall produces same problem.

Suggestions?

**Comment by lkraav** [comment]
I've learned that restarting PHP (FPM or Apache module) may also be necessary to clear opcache for the `class_exists( 'QM_Backtrace' )` check to update.

**Comment by davidfavor** [comment]
No exactly.

After migration old paths still exist, which won't have anything to do with Opcache, as Opcache has no clue about any path on source machine.

Unsure exactly what the problem might be.

Next time it occurs, I'll attempt to track it down.

**Comment by johnbillion** [comment]
I'm going to close this issue because it seems that it's somehow related to the opcache in PHP FPM. I've seen this very occasionally and restarting FPM fixes the issue.

I don't think this is specific to QM, but if anyone has any more information please feel free to post here.
