### ISSUE TITLE
Can't see plugin menu

### ISSUE THREAD

**Issue by jeffmcml** [johnbillion/query-monitor#310]
I installed Query Monitor and I'm an admin.  But I don't see any menu in the admin screen for this plugin.

**Comment by jeffmcml** [comment]
Sorry, I totally missed the menu at the top of the admin page.  I see it now.  

However I have a followup issue - the queries I want to see are generated from cron scripts.  It looks like they are not reported by Query Monitor, is that correct?

**Comment by johnbillion** [comment]
Glad you got it sorted :-)

QM doesn't currently operate with background processes such as cron. See #173. This is a work in progress, but there's no ETA just yet.

**Comment by jeffmcml** [comment]
Actually I can also run the scripts that are executed by cron, but in a
browser window.  It's not a Wordpress page.  Any chance that will work?

Jeff

**Comment by johnbillion** [comment]
That will work as long as `DOING_CRON` isn't defined.
