### ISSUE TITLE
Better handling of JavaScript errors

### ISSUE THREAD

**Issue by gmgj** [johnbillion/query-monitor#312]
This is an observation, not a request to fix. If I activate Free Jetpack, it fails to create the menu dropdown. 
http://cookdotcom.com/wp-admin/index.php  I step through query-monitor.js in Chrome debugger, no errors.  If you are interested in seeing, I can give you an admin access to the site.     Windows 10 Pro, latest everything, Hostgator, PHP 5.4.45.

**Comment by johnbillion** [comment]
Are there any fatal errors allowing in the PHP error log?

**Comment by gmgj** [comment]
I do not see any errors; however, shared hosting PHP errors can be wanky.  

![querymonitormenu](https://user-images.githubusercontent.com/1705834/36386899-5d75e20e-1565-11e8-9278-bcb2bb41d879.png)

I occasionally see the above when I have both jetpack and query monitor active. 
I tested with twentyseventeen and a twentyseveenteen child theme.

**Comment by johnbillion** [comment]
That's the output that QM shows you if the admin toolbar isn't shown on the current page load.

If you click one of those links does it correctly open the main QM output and scroll you to the panel that you clicked?

Are there any other JavaScript errors in the browser console?

Can you try the development version from the `develop` branch in GitHub? It has some added resilience in place so it hopefully breaks less often when JavaScript errors or PHP fatal errors occur elsewhere.

**Comment by johnbillion** [comment]
If your shared host log files are wanky (good word) you might want to enable `WP_DEBUG` and `WP_DEBUG_LOG` then see if anything appears in the log at `wp-content/debug.log`.

**Comment by gmgj** [comment]
I changed to 
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

I added this to my child theme functions.php and activated that theme:
error_log(__FILE__ ." : ". __FUNCTION__ . ' called at ' . microtime(true),0);

I see these, but, nothing else
[19-Feb-2018 17:58:26 UTC] /home3/gmgj/public_html/cookdotcom.com/wp-content/themes/twentyseventeen-child/functions.php : gmgj_theme_enqueue_styles called at 1519063106.0509

-----
? That's the output that QM shows you if the admin toolbar isn't shown on the current page load.

? If you click one of those links does it correctly open the main QM output and scroll you to the panel that you clicked?
This page opens  
http://cookdotcom.com/wp-login.php#qm-db_queries-wpdb  
and I see a page of queries

? Are there any other JavaScript errors in the browser console?
I tried looking after page load and display, nothing

If I open the developer tools and  hit url http://cookdotcom.com/wp-login.php
I get this (chrome save as)
ewtab:7 SW registered
thumb/ Failed to load resource: net::ERR_FAILED
wp-login.php Failed to load resource: net::ERR_FAILED
thumb/ Failed to load resource: net::ERR_FAILED
2171483 Failed to load resource: net::ERR_FAILED
thumb/ Failed to load resource: net::ERR_FAILED
Navigated to http://cookdotcom.com/wp-login.php
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate&ver=4.9.4:9 JQMIGRATE: Migrate is installed, version 1.4.1

? Can you try the development version from the develop branch in GitHub? It has some added resilience in place so it hopefully breaks less often when JavaScript errors or PHP fatal errors occur elsewhere.

I might be able to get to this in a few days.
--------------
I do not see why it does not throw an error in query_monitor here:

container.appendChild( new_menu.get(0) );

Is there someplace in query_monitor.js that I could set a breakpoint on and check or watch or whatever?

Also, the offer stands, I can set you up with access to WordPress cookdotcom and / or my hostgator account.  cookdotcom is a test site.  I do most of my work in WAMP and then test on Hostgator.  There are a couple of live client WordPress sites on my Hostgator site, but, they are low traffic sites for associations like the Worcester chapter of the Association of Facilities engineers.

Hostgator was bought a few years ago.  I would sya they are not playing nice at the moment.  See
https://garyjohnson53.wordpress.com/2018/01/29/mojo-marketplace/

**Comment by gmgj** [comment]
Opps, I meant throw an error here:
		$('#wp-admin-bar-query-monitor ul').append(container);

**Comment by luke-au** [comment]
I'm working on a website which uses [Cooked – Recipes for WordPress](https://en-au.wordpress.org/plugins/cooked/) which appears to have a conflict when **Query Monitor** is active.
The page using their `[cooked-browse]` shortcode causes the below console error when active.

**Console**
> Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLDocument.<anonymous> (query-monitor.js?ver=1510281732:72)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

```javascript
$('#wp-admin-bar-query-monitor')
			.addClass(qm.menu.top.classname)
			.find('a').eq(0)
			.html(qm.menu.top.title)
		;
```

**Comment by gmgj** [comment]
I have downloaded the zip from here: https://github.com/WordPress/wordpress-develop  I have a test site on hostgator that I can put it on, it is an existing WP site.  But I am unsure what to do.  Can I just upload and overwrite the existing files?  Is there doc on how to set it up?  Will I be able to associate Free Jetpack with a development site?  In my first round of tests, the problem only occured when I had free jetpack installed and activated.

**Comment by gmgj** [comment]
I tested on a new test site.  If I change the Jetpack - free,  settings to enable  
Enable the WordPress.com toolbar
The WordPress.com toolbar replaces the default admin bar and offers quick links to the Reader, all your sites, your WordPress.com profile, and notifications. Centralize your WordPress experience with a single global toolbar.

That' s when  the glitch shows up.  I guess that's not to surprising.  I had the chrome developer tools up as I toggled the toolbar off and on, still did not see anything in the console except multiple occurences of these
JQMIGRATE: Migrate is installed, version 1.4.1 
Navigated to http://gjtest.garyjohnsoninfo.info/gjtest/wp-admin/admin.php?page=jetpack

**Comment by JiveDig** [comment]
I"m receiving the same error. Not using Cooked plugin, and not using Jetpack.

When I dump `console.log( qm );` I don't get an object, I get an HTML string.

<img width="549" alt="slack-imgs" src="https://user-images.githubusercontent.com/540990/37841246-a2260ce6-2e95-11e8-8f11-07467322903a.png">

Dumping `console.log( qm.menu );` naturally returns 'undefined' then.

**Comment by johnbillion** [comment]
Resilience to external JavaScript errors has been improved in 3.0.
