### ISSUE TITLE
Problem on Yoast SEO settings page

### ISSUE THREAD

**Issue by mundschenk-at** [johnbillion/query-monitor#315]
I've noticed an issue when Query Monitor is used in conjunction with Yoast SEO. On the Search Appearance page of Yoast's settings, a `TypeError: qm.menu is undefined` is reported on line 71 of `query-monitor.js`. This does not happen on other Yoast settings pages nor in general. ("Search Appearance" is the name in Yoast 7.x, previously the page was titled "Title & Meta", the error was the same).

**Comment by johnbillion** [comment]
Thanks for the report. Are there any fatal errors showing in your PHP error log?

**Comment by mundschenk-at** [comment]
No. The markup seems to be all there (i.e. the table at the bottom of the page).

**Comment by johnbillion** [comment]
Thanks. I've checked this myself and can't see a problem.

* Does the problem go away if you deactivate all your other plugins and switch to one of the default themes (for example Twenty Seventeen)?
* Are there any other JavaScript errors in the browser console?
* Are you using the latest version of QM (2.17.0)?
* Which version of PHP are you using?
* Which version of WordPress are you using?
* Can you enable double-check your PHP error log? (I ask because usually when this error happens, it's being caused by a fatal error on the page.)

**Comment by mundschenk-at** [comment]
PHP 7.2.3 and WordPress 4.9.4. There are no other JS errors on the console. QM is 2.17.0. There are no errors in the PHP log. 

The whole thing is pretty weird. I've been unable to reproduce this locally, but the effect is consistent on a production multisite - only in one site, though. I've tried switching off the non-network activated plugins and re-enabling one by one, but so far I've found three plugins that seem to trigger the issue (AMP, Yoast Glue for SEO & AMP, Admin Bar User Switching). While there are quite a few plugins enabled, the machine has got more than enough RAM and the memory and execution time limits are set quite high. Also, there are no errors.

Since those plugin don't much in common, I experimented a bit further and it seems that the number of plugins (or maybe hooked callbacks?) is an issue, because if I deactivate some other plugins, I can re-activate e.g. AMP without breaking things. When there are "too many" plugins, the markup from QM is truncated, thus breaking JS because the last inline script is missing. However, there no errors in the logfile. And neither execution time nor memory limits should be or appear to be triggered.

**Comment by mundschenk-at** [comment]
@johnbillion Can you point me to a function/method where I could try to add some `error_log` calls to determine where/why the script stops?

**Comment by mundschenk-at** [comment]
@johnbillion I've poked around a bit and it seems all the proper functions (`Html::after_output`) are called, but the echoed output never makes it to the client (on the broken page).

**Comment by mundschenk-at** [comment]
I poked around some more on 2.17.0 and it looks like there was some problem due to a lot of nested output buffers. I have not been able to determine any root cause, it might even have been a PHP bug (not too likely, but possible) that got triggered somehow, as removing plugins at more-or-less random made things work (where the same plugins, re-added one-by-one were not a problem, only in some combinations).

I have not been able to trigger the issue with 3.0.0, so I think this issue can be closed (unless you'd like to keep it as a marker if something similar crops up for somebody else).
