### ISSUE TITLE
Incorrect Request Data

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#317]
View the _Request_ section shows the incorrect object: https://cloudup.com/cukFMCMzKVt

Fresh install; QM 2.17.0 only plugin activated, _Twenty Seventeen_.
(Also checked _Sample Page_)

**Comment by johnbillion** [comment]
Thanks for the report. On the post editing screen WordPress doesn't set the queried object, so there is none. The current user is always shown by QM.

I can see how this is confusing. I'll improve this by always showing the queried object row even if there is none.

**Comment by johnbillion** [comment]
Oh the Query Vars aren't clear either. The admin area of WordPress doesn't use query vars from the global `WP_Query`, so there are none, even when there are query arguments in the URL.

I'll improve this too.

**Comment by johnbillion** [comment]
Fixed in c5d160b for version 3.0.0.
