### ISSUE TITLE
Wordpress jquery bug

### ISSUE THREAD

**Issue by Demonisius666** [johnbillion/query-monitor#322]
FILE: /www/wp-content/plugins/query-monitor/collectors/environment.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 127 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
------------------------------------------------------------------------------------------------------------

FILE: /www/wp-content/plugins/query-monitor/wp-content/db.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 119 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
------------------------------------------------------------------------------------------------------------

**Comment by johnbillion** [comment]
Please read the conditional code around the affected lines.

**Comment by Demonisius666** [comment]
PHP Compatibility Checker plugin show that error

**Comment by Demonisius666** [comment]
btw thank you. Very nice debug plugin for wordpress.
