### ISSUE TITLE
New version show empty page with plugins content

### ISSUE THREAD

**Issue by qijianjun** [johnbillion/query-monitor#323]
I just update to 3.0 version and the plugin content shown in the tab is empty, after switching back to 2.17.0, the plugins content can show again.

**Comment by johnbillion** [comment]
Thanks for the report. Can you take a screenshot so I can understand what's missing? Thanks!

**Comment by qijianjun** [comment]
Sorry I just found all is OK after reactivate the new version again and force a page fresh.

The problem I mentioned before is: after the upgrade, the content area of the plugins is all white and no content shown.

![image](https://user-images.githubusercontent.com/612912/38666339-351e6e72-3e71-11e8-8066-4c7fbc855c7a.png)

**Comment by johnbillion** [comment]
Thanks for letting me know!
