### ISSUE TITLE
"A Javascript problem is preventing Query Monitor from working properly"

### ISSUE THREAD

**Issue by teknofilo** [johnbillion/query-monitor#325]
After updating to 3.0.0, Query Monitor only works file in admin pages. In the public website, all data is appended at the end of the page, and this message is shown in at least two different browsers: "A Javascript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading"

**Comment by johnbillion** [comment]
Thanks for the report. Is there a plugin or theme active on your site that's doing something unusual with jQuery? For example, replacing it or removing it.

**Comment by teknofilo** [comment]
Not that I am aware of... is there an easy way to identify such behaviour

I use many plugins (Jetpack, Yoast, Mashare, SNAP, etc.) and a commercial theme, but I am not aware of any plugin that replaces or removes jQuery.

**Comment by abuyoyo** [comment]
I have a similar issue after upgrading to 3.0
On the front-end I get this message:
> A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.

I've disabled all ajax scripts I use in my theme - still no luck. `#query-monitor` tag has class `.qm-no-js` and does NOT have class .`qm-show`. The tag is set to `display:none`

I do have a plugin that removes jquery-migrate from the front-end (https://wordpress.org/plugins/remove-jquery-migrate/). And I am admittedly running the site on an old version of PHP (5.3.23) and will not be able to upgrade in the near future.

I also have the jquery-plus plugin (https://wordpress.org/plugins/wp-jquery-plus/) installed. Which attempts to load jquery and jquery-migrate (migrate later removed altogether by the aforementioned plugin) from a cdn. And adds a `document.write` fallback script for the local jquery version.

qm 2.17 was working flawlessly btw. With my custom ajax scripts and all the above mentioned.

On the backend (in wp-admin) the new qm 3.0 window DOES work properly. The admin-bar however says "Ajax: notice". Clicking on it does not tell me what the notice might be. Nothing unusual appears in the PHP Errors/notices.

I have, I believe, somewhere, a localized script with the following code:
`var ajaxurl = 'http://new.iac.ani-mator.com/wp-admin/admin-ajax.php';`
I don't know if that's qm adding it or one of my own scripts. I vaguely remember doing something like that at one point or another. Maybe not.
Will have to dig in to find out.

**Comment by abuyoyo** [comment]
I have a similar issue after upgrading to 3.0
On the front-end I get this message:
> A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.

I've disabled all ajax scripts I use in my theme - still no luck. `#query-monitor` tag has class `.qm-no-js` and does NOT have class .`qm-show`. The tag is set to `display:none`

I do have a plugin that removes jquery-migrate from the front-end (https://wordpress.org/plugins/remove-jquery-migrate/). And I am admittedly running the site on an old version of PHP (5.3.23) and will not be able to upgrade in the near future.

I also have the jquery-plus plugin (https://wordpress.org/plugins/wp-jquery-plus/) installed. Which attempts to load jquery and jquery-migrate (migrate later removed altogether by the aforementioned plugin) from a cdn. And adds a `document.write` fallback script for the local jquery version.

qm 2.17 was working flawlessly btw. With my custom ajax scripts and all the above mentioned.

On the backend (in wp-admin) the new qm 3.0 window DOES work properly. The admin-bar however says "Ajax: notice". Clicking on it does not tell me what the notice might be. Nothing unusual appears in the PHP Errors/notices.

I have, I believe, somewhere, a localized script with the following code:
`var ajaxurl = 'http://mywebsite/wp-admin/admin-ajax.php';`
I don't know if that's qm adding it or one of my own scripts. I vaguely remember doing something like that at one point or another. Maybe not.
Will have to dig in to find out.

**Comment by emwebber** [comment]
I'm also having this issue, but seems only to happen when i'm looking at Gravity Forms (an installed plugin) in the admin...was a solution ever provided that i'm maybe not seeing?

**Comment by Luc45** [comment]
I use a custom jQuery:

```
wp_deregister_script('jquery');
wp_enqueue_script('jquery', get_template_directory_uri() . '/assets/jquery.min.js');
```

And Query Monitor doesn't load:
`(index):1068 A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.`

All the best,
Lucas

**Comment by tnorthcutt** [comment]
FWIW, I'm seeing this issue in the admin on Gravity Forms screens, with only QM and Gravity Forms active. @johnbillion I'd be more than happy to help debug/isolate further if desired.

**Comment by johnbillion** [comment]
@tnorthcutt Thanks for the offer of help. I pushed a JS fix in QM 3.3.1 but I don't think it's related to this issue. Try updating anyway and see if anything changes.

If not, the path forward really is to figure out if Gravity Forms is doing anything weird with jQuery (for example, overriding it, dequeueing it, deregistering it, changing dependencies, renaming it, forcing it to the footer, messing with the `$` or `jQuery` globals) or whether it's caused by another issue.

Some related questions:

* Does QM still get output to the page? If so, does it operate in the single-pane scrolling mode? (That's the fallback mode when JS is messed up.)
* What errors, if any, does QM report in the browser console?
* Any other JS errors in the console?
* Any fatal errors in the PHP error log?

**Comment by fippy** [comment]
I'm seeing this issue on QM 3.3.4 and Gravity Forms 2.4.8 (latest version)

**Comment by tnorthcutt** [comment]
@johnbillion Update:

I'm seeing these errors in the console:
`A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.`
And:
`QM error from page: undefined QM_i18n`

Those appear to come from [these lines](https://github.com/johnbillion/query-monitor/blob/f45006680bc6518f869958007388d9bd3cb37b62/dispatchers/Html.php#L486-L490) in `/dispatchers/Html.php`.

- No PHP errors in the log
- QM output is still on the page; see screenshot below

Happy to continue debugging; let me know what would be most helpful.

![image](https://user-images.githubusercontent.com/796639/57468645-1eb38400-7242-11e9-8eca-fb6aba39c2ba.png)

**Comment by steffanhalv** [comment]
@tnorthcutt I am having this problem too

**Comment by kampiamodikuesto** [comment]
i have same problem

**Comment by bahia0019** [comment]
Same issue here. Isolated to GF and QM. Let me know if there's anything I can do to help troubleshoot it.
<img width="1440" alt="Screen Shot 2019-07-08 at 7 36 17 PM" src="https://user-images.githubusercontent.com/1586037/60855331-1cc15f00-a1b8-11e9-8b86-ef43dcbb1ca5.png">

**Comment by johnbillion** [comment]
Thanks folks, I don't have much time to look into this at the moment I'm afraid, but it's on my to-do list.

**Comment by johnbillion** [comment]
I have a suspicion that this page in GF doesn't enqueue any JS and CSS other than from core and GF. Can anybody confirm this? Are the `query-monitor.js` and `query-monitor.css` files included in the source of this screen?

**Comment by bahia0019** [comment]
You caught me right before my bedtime here in San Diego.
Confirmed. No JS or CSS for you, even on the Forms list page. 
Off to bed, happy to check anything else for you in the morning.

<img width="1440" alt="Screen Shot 2019-07-09 at 1 39 27 AM" src="https://user-images.githubusercontent.com/1586037/60873197-cd485680-a1ea-11e9-9e86-92a01816294b.png">

**Comment by steckinsights** [comment]
Did anything ever come of this? Seeing the same issue.

Hosting with Kinsta (CDN probably isn't in play due to it being a staging install).  I deactivated all plugins except Query Monitor and it still occurs.

Theme in use is Storefront by Automattic. Same problem when switching to Twentynineteen theme.  

Seeing `A JavaScript problem on the page is preventing Query Monitor from working correctly. jQuery may have been blocked from loading.` as well as `QM error from page: undefined QM_i18n`.

**Comment by steckinsights** [comment]
FWIW, my issue was resolved.  Bad URL in the wp-config.php file (referencing live site while working on staging).

**Comment by jethromay** [comment]
Same issue. I have de-registered the default jQuery and replaced it with one via NPM. Is there a work around for this?

**Comment by valassis-nick** [comment]
I've found a quick workaround @jethromay - https://docs.gravityforms.com/enabling-no-conflict-mode/

Essentially, you disable GravityForms' no-conflict mode. Have tested locally and in my production instance. This is not a long-term fix, however.

**Comment by johnbillion** [comment]
This whole thing with Gravity Forms thinking it's a special snowflake and deciding to prevent all other plugins from loading their JS or CSS on its administration pages it not something I'm interested in dealing with.

Please take this up with the folks at Gravity Forms.

**Comment by valassis-nick** [comment]
@johnbillion totally fair. I plan on opening a ticket with their support team & pointing here, because it's totally out of order that any paid service's admin page doesn't follow standard WP coding practices.

**Comment by ethanclevenger91** [comment]
Assuming that Gravity Forms's "No-Conflict" mode isn't the default, this actually seems fine. They've added an opt-in setting to their plugin to disable other scripts/styles on their admin page to attempt to force the form builder to work when all else fails.

But I'm not sure if No-Conflict is the GF default or not. It definitely should _not_ be. If there's anything to be taken up with them, that's it, IMO.
