### ISSUE TITLE
php_uname warning

### ISSUE THREAD

**Issue by Daronspence** [johnbillion/query-monitor#328]
On some servers/hosts, `php_uname()` is disabled. This can throw an error like: 
`Warning: php_uname() has been disabled for security reasons in /app/public/wp-content/plugins/query-monitor/collectors/environment.php on line 230`

One such host is Flywheel. https://getflywheel.com/wordpress-support/what-php-functions-are-disabled/

Is it possible to add a conditional check to prevent this? Query Monitor also doesn't catch the warning, I assume because it happens after the plugin stops collecting errors from the rest of the page.

Cheers

**Comment by johnbillion** [comment]
Fixed in 965d9da
