### ISSUE TITLE
[feature request] - remove dir=rtl styling

### ISSUE THREAD

**Issue by abuyoyo** [johnbillion/query-monitor#330]
My website is localized to an rtl-language.

Query-Monitor however only outputs ltr/English information (scripts, hooks, sql queries etc. are all in ltr English).
This leads to a very badly formatted table.
I can see no use-case where right-alignment of developer information can be useful.
I use a plugin to override the default query-monitor styling. 

![qm-rtl](https://user-images.githubusercontent.com/24979061/39093070-f653c954-4621-11e8-9a1f-f38372068194.jpg)

**Comment by abuyoyo** [comment]
To be fair - I would override the rtl styling on v2.17 and earlier too. For much the same reason.
My plugin was simply tailored to the old layout.
But admittedly this is a larger issue with localization (and rtl support) on Wordpress. Not strictly a qm issue.

**Comment by johnbillion** [comment]
Fixed in abe1a32
