### ISSUE TITLE
PHP Errors: individual item one-click clipboard copy

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#331]
Hey. Today I realized it would be massively convenient for bug reports to be able to get a one-click formatted output of any error row. Adding some clipboard JS with that usual mobile-like double-square copy icon sounds doable. Not sure yet what the formatting should be like, perhaps:

```
LEVEL
    Notice

MESSAGE
    Undefined index: cssClass

...
```

Your thoughts?

**Comment by johnbillion** [comment]
What's your use case? Pasting into bug reports?

**Comment by lkraav** [comment]
> What's your use case? Pasting into bug reports?

Exactly. Perhaps you've noticed, too, how flaky mouse-copying over HTML elements can be (selects random other things, etc). Pre-formatting would also be quite an effort saver.

I have a feeling (yes, totally anecdotal data) some notices/warnings don't get reported simply because it's too much work..

But thinking about it led me to a more general idea - provide an API for people to provision whatever integration buttons.

* button 1 - copy to clipboard
* button 2 - pre-fill an external bug reporting service

Perhaps clipboard copy could be incorporated in core here as an example, other authors could provide addon plugins.

**Comment by johnbillion** [comment]
I've been thinking about this a bit and even though I like the idea I don't think it's something that I'll implement.

Thanks for the suggestion, though!
