### ISSUE TITLE
WP Update screens (plugins etc) shows Query Monitor

### ISSUE THREAD

**Issue by slaFFik** [johnbillion/query-monitor#335]
It's better to describe with a screenshot (take a look at the bottom of it). I think, there should be no Query Monitor half-rendered bar.

![image](https://user-images.githubusercontent.com/282234/39568509-26f026c8-4ecb-11e8-848a-6770a07be4da.png)

Doesn't matter what I update.

**Comment by johnbillion** [comment]
Thanks! This is the view that is collapsed by default when there's no admin toolbar (the updates are actually performed in an iframe). The same view can be seen when you're using the Customizer.

I need to do some work to make this a bit clearer.

**Comment by deckerweb** [comment]
@johnbillion 
Is there any progress on this?
This bar is still appearing in all Iframes, Thickbox modals, Customizer, also Elementor Editor panel

Especially when updating a huge list of plugins on the page http://my-path/wp-admin/update-core.php?action=do-plugin-upgrade

The Query Monitor bar within that Iframe is covering the action links at the bottom making it hard to go back etc. via these links.

I would suggest a solution to remove these appearances via a constant so I can control it as a user.
In some cases, for example in the Customizer and Elementor Editor panel, it was actually useful to have the QM instances there as it helped debug some strange issues. But most of the time these bars go on my nerves in these cases and I want them to disappear there (and only display if I would really need in rare cases).

Thanks in advance!

**Comment by johnbillion** [comment]
This was fixed in version 3.6 (009360e).
