### ISSUE TITLE
Incompatibility with Autoptimize : "A JavaScript problem on the page"

### ISSUE THREAD

**Issue by louiswalch** [johnbillion/query-monitor#336]
I am using Autoptimize to concatenate all JP files for performance gains. When this is activated, I'm getting the "A JavaScript problem on the page" error, even though jQuery is present on the page. Autoptimize does not include jQuery in the concatenated file, so the <script> tag remains on the page in it's original location. The rest of the JS is moved down to the bottom of the page.

Without Autoptimize:
Jquery first, then all the other independent .js embed.
![without_autoptimize](https://user-images.githubusercontent.com/286013/39669752-ec97aede-50c2-11e8-908f-b4b25881798b.png)

With Autoptimize:
Jquery first, then a single .js embed containing all files (including yours).
![with_autoptimize](https://user-images.githubusercontent.com/286013/39669751-ec8a7926-50c2-11e8-97a1-f8254e16c119.png)

Any idea what's going on?

**Comment by johnbillion** [comment]
Thanks for the report. I've reproduced the problem with Autoptimize enabled and I'm in the process of figuring out the cause.
