### ISSUE TITLE
Lap action parameter incompatibility 

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#337]
This could just be that I don't understand the usage of the `$name` parameter.

`action_function_time_lap()` has two parameters: `$function` and `$name`. My understanding, is that `$function` is the high-level item being timed, whereas `$name` provides an additional level of description of where the lap occurred.

The problem is, that when `action_function_time_lap()` calls `QM_Timer::lap()`, it's param is `$name` (which I think is expected to be a string?), whereas `QM_Timer::lap()` expects the first parameter (`$data`) to be an array, and `$name` is the second parameter.

**Comment by johnbillion** [comment]
Thanks for the report. This is indeed a bug.

**Comment by johnbillion** [comment]
I hadn't noticed this because I haven't found myself needing to use the lapping functionality like I thought I would.

In QM 3.1 I'll complete the output of the lap data and fix this bug.

**Comment by johnbillion** [comment]
Fixed in 8721917
