### ISSUE TITLE
Sort timings by order started/stopped

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#339]
Would be helpful if there were (optional?) columns to show when in the entire page load the timer started and stopped, and to be able to sort by those columns (looks like currently sorted by when timer is ended).

**Comment by johnbillion** [comment]
I've been playing around this afternoon with this and I like the idea of displaying the started and stopped times, so I've added in columns for those. I attempted to make them sortable, but it's greatly complicated by the ability to put laps in for a timer, and I didn't like any of the sorting behaviour when laps are shown, so I decided to leave out the sorting.

Ideally sorting by one of the Started, Stopped, or Time columns would retain the corresponding grouping for laps, but I'm not interested in spending any time trying to figure out how to do that :-)

**Comment by johnbillion** [comment]
![wp test_wp-admin_](https://user-images.githubusercontent.com/208434/66258613-4120dd80-e79f-11e9-9a71-4e5c9b46eedf.png)

**Comment by crstauf** [comment]
I've often found the way laps are down to be curious. For most of my use cases for laps, I'd expect to see the total time, and then expand to see lap times (rather than laps always show); that would resolve the grouping issue.
