### ISSUE TITLE
Icon for wordpress.org repo

### ISSUE THREAD

**Issue by ibes** [johnbillion/query-monitor#345]
Hi there, 

I am grateful for this plugin to exist and want to give a bit love back. 

I created a quite basic icon for the plugin and maybe you want to use it. 
This is how to this should work:
https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

If I have done something wrong or you have a wish for how to improve this - let me know. 
I am not a designer - so nothing fancy. But a lot better than a random background, I think :)

I used Open Sans - the font that is also used in the WP plugin repo. 
And added the red square - as that is cute and feels quite symbolic for highlighting lines in the menu with errors. 

If this is a nice and helpful contribution, please let me know. 
I am thinking about doing that for more plugins that I appreciate and have not yet artworks. 
I like it when the plugins look good :)

![icon-128x128](https://user-images.githubusercontent.com/383277/41036996-39ecfe36-6992-11e8-8db6-5146c6f43667.png)
![icon-256x256](https://user-images.githubusercontent.com/383277/41036998-3a5a0ae4-6992-11e8-8f9b-2689610ad630.png)

I can't upload the icon.svg so here is the code for it :)

```svg
<svg height="256" viewBox="0 0 67.733331 67.733331" width="256" xmlns="http://www.w3.org/2000/svg" style="background-color: #fff"><path d="m-3.667492-3.913738h99.153259v82.518562h-99.153259z" fill="#fff" stroke-width=".264583"/><g stroke-width=".202634" transform="translate(0 -229.26668)"><path d="m29.5109 259.95874q0 5.05319-1.937691 8.51064-1.918693 3.45745-5.604104 4.86322l6.648937 7.16186h-6.117022l-5.243162-6.23101h-.740881q-6.287995 0-9.6694545-3.7234-3.3624625-3.7424-3.3624625-10.6193 0-6.8769 3.3814595-10.56232 3.4004565-3.68541 9.6884515-3.68541 6.19301 0 9.574469 3.74241 3.38146 3.7424 3.38146 10.54331zm-21.2006113 0q0 5.12918 2.0706693 7.78876 2.070669 2.64057 6.136019 2.64057 4.046353 0 6.098025-2.62158 2.070669-2.62158 2.070669-7.80775 0-5.11018-2.051672-7.75076-2.032675-2.64058-6.079028-2.64058-4.084347 0-6.174013 2.64058-2.0706693 2.64058-2.0706693 7.75076z"/><path d="m47.482026 273.88351-8.054712-23.19529h-.151976q.322949 5.16718.322949 9.68845v13.50684h-4.122342v-27.77356h6.401977l7.712767 22.09347h.113982l7.940731-22.09347h6.420973v27.77356h-4.369301v-13.7348q0-2.07067.09498-5.39514.113982-3.32447.18997-4.02735h-.151976l-8.339666 23.15729h-4.00836z"/></g><path d="m35.272469 47.09367h28.975803v4.233337h-28.975803z" fill="#de0100" stroke-width=".262807"/></svg>
```

**Comment by johnbillion** [comment]
Thanks!

**Comment by johnbillion** [comment]
Thanks for your work on this @ibes but QM now has a new logo!

**Comment by ibes** [comment]
@johnbillion 
Wow - a fancy one. 

I am happy that the place of the logo is finally not a random generated thing anymore. 
Thanks for your awesome work.
