### ISSUE TITLE
Problem with db.php

### ISSUE THREAD

**Issue by MarkH5555** [johnbillion/query-monitor#346]
Hi

Just installed Query Monitor and created a symlink to the non standard wp-content folder used by the site (wp-gapcontent).  The symlink was created but the Wordpress site would not then load.  

Removing the db.php symlink from wp-gapcontent meant the site would load once more.  W3 Cache was disabled before doing doing any of this.

I added the symlink because the query screen was reporting that it was unable to create a symlink itself.

The Wordpress site in question has 49 active plugins.

Any ideas where I am going wrong?
Many thanks
Mark

**Comment by johnbillion** [comment]
Are there any errors showing in your server's error logs during the period where the site did not load?

**Comment by MarkH5555** [comment]
H John

Thanks for getting back to me.

Nothing was written to the error logs at the time

Thanks
Mark

**Comment by johnbillion** [comment]
@MarkH5555 Have you been able to identify the problem here? Might be worth trying to deactivate your other plugins one by one to see if there's a conflict.
