### ISSUE TITLE
Extension 'mysql_' is deprecated since PHP 5.5

### ISSUE THREAD

**Issue by FrequentFlyer** [johnbillion/query-monitor#347]
FILE:  /wp-content/plugins/query-monitor/wp-content/db.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 123 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
------------------------------------------------------------------------------------------------------------

FILE: /wp-content/plugins/query-monitor/collectors/environment.php
------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------
 123 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
 128 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0; Use mysqli instead
------------------------------------------------------------------------------------------------------------

**Comment by johnbillion** [comment]
Please look at the actual code block before reporting errors from automated scans.
