### ISSUE TITLE
Display all user defined constants

### ISSUE THREAD

**Issue by igmoweb** [johnbillion/query-monitor#348]
I don't know if it would be too much but it would come handy if QM displays all the user-defined constants with `get_defined_constants(true)['user']`. This list can get quite long so QM could display it toggled off by default. I've seen 279 defined in a pretty big site but I don't really know if that's a long list or not.

QM could even list the most important ones like the current displayed in QM (here's a list and a related issue: https://github.com/johnbillion/query-monitor/issues/167 )

**Comment by crstauf** [comment]
@igmoweb I created a plugin, [_Query Monitor Extend_](https://github.com/crstauf/query-monitor-extend), which adds several panels to QM, including user defined constants.

Recommend the `version/1.0` branch, but `master` should work as well.

**Comment by johnbillion** [comment]
Closing this off as it's not something I plan on adding. Cheers!
