### ISSUE TITLE
Display on mobile is wonky

### ISSUE THREAD

**Issue by afragen** [johnbillion/query-monitor#349]
Since the 3.0 update the display on mobile is wonky. 

The 2 biggest examples are the percentage of the screen that QM uses. On my iPad it’s seems that it’s about 90%

![img_0454](https://user-images.githubusercontent.com/1296790/42136857-ae2bc2a8-7d17-11e8-8e40-4340c5cab518.png)

And when trying to view HTTP requests the column is extremely narrow.

![img_0455](https://user-images.githubusercontent.com/1296790/42136863-c844deea-7d17-11e8-94b8-dfe118b1975b.png)

Clearly QM is still usable but not optimal. There also is no way to drag the upper bar and resize this on mobile.

**Comment by johnbillion** [comment]
Thanks for the report!

I've been making some improvements to this ready for version 3.1. I'll test it out on my iPad and see what other improvements I can make. I should be able to make the top bar draggable on all devices too.

**Comment by afragen** [comment]
I’m happy to help test if you need it.

**Comment by bobbingwide** [comment]
Adding this minor problem. The Attributes column on the Blocks page looks like it needs some CSS to wrap very long attributes.  Inner HTML is OK.
![5bfd5b04-d9e4-4f0f-ae14-4fcf85e753a9](https://user-images.githubusercontent.com/2474435/49718133-18988780-fc51-11e8-83cb-7c5ef5c7422f.png)

**Comment by johnbillion** [comment]
Cheers. I'll continue playing around with this.

**Comment by johnbillion** [comment]
These issues should be fixed now. The panel can be resized on touch-enabled devices (it's a bit janky but that seems to be an issue with the event listener support). If you see any other issues, please open individual new issues.
