### ISSUE TITLE
3.0.1: possible conflict w/ Rocket Lazy Load plugin, QM hangs Chrome tab (only?) w/ infinite loading spinner

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#350]
We ran into a sudden QM loading weirdness and seemed to be able to narrow it down to Rocket Lazy Load (1.4.8) https://github.com/wp-media/rocket-lazy-load

Hypothesis: something within post-page-load JS routines probably collide.

Symptom: visible parts of the page finish loading, then it comes time for QM to render its admin panel, but this part never finishes, and browser tab starts spinning CPU at 100%.

I've achieved different results in Firefox and Chrome. We'll try to record a screencast later today, but putting it out here if someone else is already experiencing or can reproduce on their own earlier.

**Comment by johnbillion** [comment]
Is this still happening?

**Comment by lkraav** [comment]
> Is this still happening?

I haven't checked w/ 3.1.0, will have to report back.

**Comment by lkraav** [comment]
@johnbillion I've just verified, this is definitely still happening. Rocket Lazy Load currently 1.4.9, Query Monitor latest.

There's a clear few second delay for QM finishing loading just by having Rocket Lazy Load active.

If you enable a large data set panel like `SAVEQUERIES true`, delay will be tens of seconds, if not for all intents and purposes "infinite" (depending on how high the query count is).

**Comment by lkraav** [comment]
have discovered additional info, that maybe invalidates above hypothesis.

Our comments table is ballooning due to how some plugins store their metadata, and it turns out Admin Bar "Comments" menu item scans comments table on every request.

This becomes a massive performance bottleneck at hundreds of thousands of comments table rows, so I unhooked those menu items (source: https://gist.github.com/mattclements/10a997775894c7a0eba1)

I will also take a closer look at SAVEQUERIES next. It's likely this is not a JS topic at all.

**Comment by johnbillion** [comment]
Ah yeah I've seen that same performance problem on sites with a large number of comments.

Sort of related: https://core.trac.wordpress.org/ticket/19372

**Comment by lkraav** [comment]
rocket-lazy-load-2.3.0.2
query-monitor-3.2.2

This is now confirmed to still be a problem, with plugins at their latest versions, but surprisingly only on Chrome.

Firefox-64+ seems to somehow manage to avoid this issue.
