### ISSUE TITLE
Query Monitor Conflicts With other Debugging Plugins

### ISSUE THREAD

**Issue by bv-akash** [johnbillion/query-monitor#358]
Not an issue rather a query.

The QM db.php symlink is causing a conflicts with other plugins which also creates a db.php for extending their capabilities.

In one of your answers here [https://wordpress.org/support/topic/error-with-w3-total-cache-file-dbphp-is-not-a-w3tc-drop-in/](https://wordpress.org/support/topic/error-with-w3-total-cache-file-dbphp-is-not-a-w3tc-drop-in/) you mentioned that Query Monitor can get the Details it is extracting using db.php without even including it, But it is your Least priority.

Can you please tell how is it possible to get the backtrace without creating a symlink of db.php

Thanks in advance.

**Comment by johnbillion** [comment]
Without a db.php file in place, WordPress does fetch its own backtrace for queries but it doesn't include enough information for QM to be able to determine the component responsible for the query.

It's frustrating but there really isn't a solution at the moment.

See also https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink#when-an-existing-dbphp-file-is-already-in-place

**Comment by bv-akash** [comment]
Hey John,

Isn't it possible to Extend wpdb in a Class inside Plugin and display the data without creating the Symlink and if No, Why this Symlink is important.
