### ISSUE TITLE
Safari gives error of missing "query-monitor.css.map"

### ISSUE THREAD

**Issue by jidaikobo-shibata** [johnbillion/query-monitor#360]
Hi,

first of all, thank you for giving us such a great plug-in.

Safari's error console gives me an error about "query-monitor.css.map".

> Failed to load resource: the sever responded with a status of 404 () http://example.com/wp-content/plugins/query-monitor/assets/query-monitor.css.map

obviously there is not such a file.

Do you have an idea to solve this?

Thanks.

**Comment by johnbillion** [comment]
Thanks for the report! I thought I disabled source mapping in the Sass
compiler but maybe I didn't. I'll check it out.

**Comment by robert1112** [comment]
Hi 

I would like to repot I still got the same error on console.

I use Query Monitor Version 3.3. Thank you.
