### ISSUE TITLE
Panel menu UL is showing disc list styles which breaks layout

### ISSUE THREAD

**Issue by chrisblakley** [johnbillion/query-monitor#361]
I noticed this when Query Monitor was first updated to 3 and it has persisted since then after a few plugin updates. I'm not sure if others are seeing it, but I'll make a pull request to explicitly declare `list-style: none;` on those `<ul>` elements.

Before:
![screen shot 2018-08-21 at 8 54 06 am](https://user-images.githubusercontent.com/6349678/44402740-a1fc4080-a520-11e8-8fb9-93a8b752f6b9.png)

After:
![screen shot 2018-08-21 at 8 56 58 am](https://user-images.githubusercontent.com/6349678/44402748-a58fc780-a520-11e8-8514-71b18b441fe4.png)

**Comment by johnbillion** [comment]
Thanks for the report! Out of interest, which theme are you using?

**Comment by chrisblakley** [comment]
I have a custom developed theme that I've used with Query Monitor for years- here are some links for reference if that helps at all:
- https://github.com/chrisblakley/Nebula
- https://gearside.com/nebula

The thought that it could be a theme conflict did cross my mind (it's certainly happened before), but that's why I thought making an explicit declaration within QM would be the way to go.

**Comment by johnbillion** [comment]
Yeah adding the reset to QM is definitely needed. I've been testing QM against a bunch of the most popular themes but styles like this will keep popping up :-).

**Comment by johnbillion** [comment]
Fixed in #362.
