### ISSUE TITLE
PHPCS: don't use the `WordPress-VIP` standard

### ISSUE THREAD

**Issue by jrfnl** [johnbillion/query-monitor#363]
The `WordPress-VIP` standard has been deprecated in WPCS 1.0.0 and will be removed in WPCS 2.0.0.

> If you used that ruleset to check your theme/plugin for hosting on the WordPress.com VIP platform, please use the Automattic VIP coding standards instead.
If you used that ruleset for any other reason, you should probably use the WordPress-Extra or WordPress ruleset instead.

Ref: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.0.0

**Comment by johnbillion** [comment]
Fixed in 3.2.0.
