### ISSUE TITLE
processing or transmission of personal data - EU privacy regulation

### ISSUE THREAD

**Issue by icsadminservice** [johnbillion/query-monitor#365]
Hi,
we use the plugin Query Monitor (Version 3.0.1) on our website. we are located in germany. we need to check if the plugins used are compliant with the EU General Data Protection Regulation.
are personal data processed by the plugin? are personal data stored by the plugin? will personal data be transmitted through the plugin to countries outside the EU?
thanks for the information

**Comment by johnbillion** [comment]
The plugin is GDPR compliant, doesn't send data anywhere, and doesn't even store data persistently. More info here: https://github.com/johnbillion/query-monitor#privacy-statement
