### ISSUE TITLE
Show paths

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#368]
Hello!

What is the quickest way to add various core paths (e.g. `WP_CONTENT_DIR`) to "Environment" tab?

**Comment by szepeviktor** [comment]
```
ABSPATH
WP_CONTENT_DIR
WP_CONTENT_URL
WP_PLUGIN_DIR
WP_PLUGIN_URL
WPMU_PLUGIN_DIR
WPMU_PLUGIN_URL
TEMPLATEPATH
STYLESHEETPATH
```

**Comment by johnbillion** [comment]
There's no way to filter this at the moment. Maybe QM needs a filter on the array of constants that get reported in this panel

**Comment by crstauf** [comment]
@szepeviktor I've created a plugin, [_Query Monitor Extend_](https://github.com/crstauf/query-monitor-extend), which adds several panels to _Query Monitor_, including paths. Recommend the `version/1.0` branch (the latest), but `master` should work just as well.

**Comment by szepeviktor** [comment]
Thank you.

It was already starred :)
