### ISSUE TITLE
See Database queries from REST API

### ISSUE THREAD

**Issue by MisterJimson** [johnbillion/query-monitor#369]
When I view the Query Monitor in WordPress Admin I don't seem to be able to review any database queries made from hitting the REST API.

**Comment by johnbillion** [comment]
QM shows you queries made on the current page load -- for Ajax calls to the REST API or similar you'll need to look at the HTTP headers in the response. QM adds some overview information, such as total query number and total query time.

**Comment by johnbillion** [comment]
This is something I've been working on improving for a long while now. It's in progress :-)

**Comment by MisterJimson** [comment]
Ok for my use case it’s REST requests from another server. Not related to the web page at all.

**Comment by punksta** [comment]
@johnbillion Hello. 
Any way I can analyze db requests which are being made by rest api  (`/wp-json/wp/v2`) requests? I have bunch of plugins and large db. Some of rest-api requests are extremely slow. I assume that some of the plugins is making non-optimized queries.

**Comment by punksta** [comment]
I've got debug information, but helps, but not much.

![image](https://user-images.githubusercontent.com/13404754/60329569-49e06700-9999-11e9-8739-aeb8a64ec091.png)
