### ISSUE TITLE
Incorrectly states OPCache is not in use

### ISSUE THREAD

**Issue by brandonkal** [johnbillion/query-monitor#372]
As the title says, Query Monitor incorrectly reports that the opcache extension is not in use. It looks like the code just lists the installed caching extensions if an object cache is not in use.

![opcache-in-use](https://user-images.githubusercontent.com/4714862/47936635-87890080-de9b-11e8-8026-cca264a0ff1a.png)

https://github.com/johnbillion/query-monitor/blob/dae2820587dea95a169b502cc85b49e5a9195943/output/html/overview.php#L182-L187

**Comment by johnbillion** [comment]
Thanks, some people have reported this on the forum, too. https://wordpress.org/support/topic/external-object-cache-not-in-use/

QM is actually reporting that an external object cache specifically for WordPress is not in use (ie. in the `wp-content/object-cache.php` file), but the Zend OPcache works without this in place so it needs some special handling.

You can safely ignore this warning for now and I'll look at getting it fixed.

**Comment by johnbillion** [comment]
This has been fixed in the `develop` branch: 9cfac74.

**Comment by Rarst** [comment]
You might want to check `opcache_get_status()` status presence and result though. Binary extension might be present, but not in use.

Just pushed respective check (from one of my old snippets) to Laps https://github.com/Rarst/laps/blob/b4c49f3c67eae2afef8e93d1c3010e3bd5e28fe8/src/Record/Collector/Core_Load_Collector.php#L35-L38

**Comment by johnbillion** [comment]
@Rarst Thanks!

**Comment by jazir5** [comment]
I am getting this same error
