### ISSUE TITLE
PHP Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by Daronspence** [johnbillion/query-monitor#375]
Possible PHP 7.2 Bug?

Screenshot of Issue (thanks QM!)
https://cl.ly/1356dea1a153

Environment Screenshot
https://cl.ly/748eb0fb389b

This is a newly spun up site on Flywheel. If their entire infrastructure isn't already on 7.2, they likely will be soon.

**Comment by johnbillion** [comment]
Thanks for the report.

The value of the `max_execution_time` directive should be an integer. It looks like yours has a trailing `s`. If this value hasn't been changed from the default then it's probably a good idea to report this bug to Flywheel.

Ref: http://php.net/manual/en/info.configuration.php#ini.max-execution-time
