### ISSUE TITLE
Gracefully behave on PHP 5.2 without fatals

### ISSUE THREAD

**Issue by slaFFik** [johnbillion/query-monitor#376]
In QM 3.0 you've dropped PHP 5.2 support, which is ok.
Could you please not generate a fatal error in `Util.php` file? Some developers still need to check things on PHP 5.2-7.2 😭 AND use your plugin.

I suggest a graceful degradation (not loading at all or deactivation with or without an admin area notice). 

Ideally, the message and plugin still active (but exits very early and doesn't load its code):
> Query Monitor does not work on PHP 5.2. Blame on you!

But a silent plugin deactivation (or not loading) on PHP 5.2 would be enough too, so developers won't need to go to a DB to copy `active_plugins` serialized array, put it into [SerializedEditor](https://serializededitor.com/), remove the QM, copy the updated serialized array and paste into DB, and save.

Thank you very much :)

**Comment by johnbillion** [comment]
There's already code in the main plugin file to prevent it from doing anything on PHP 5.2, but I might have missed something. I'll take a look.
