### ISSUE TITLE
Declension

### ISSUE THREAD

**Issue by ArthurShlain** [johnbillion/query-monitor#380]
Maybe add _n function here?

```php
esc_html_x( _n('%s Q', '%s Qs', 'Query count', 'query-monitor') ),
```

`wp-content/plugins/query-monitor/output/html/db_queries.php:445`

ru .po file example:
```
msgid "%s Q"
msgid_plural "%s Qs"
msgstr[0] "%s запрос"
msgstr[1] "%s запроса"
msgstr[2] "%s запросов"
```

**Comment by johnbillion** [comment]
Thanks!

**Comment by crstauf** [comment]
Submitted PR #423.

**Comment by crstauf** [comment]
@ArthurShlain Can you please test the PR, and confirm solves your issue?

**Comment by ArthurShlain** [comment]
@crstauf Looks correct. Can you add "%s Qs" (mutiple) string to translations service?

**Comment by crstauf** [comment]
@ArthurShlain I’m not sure what you mean...?

**Comment by ArthurShlain** [comment]
I mean https://translate.wordpress.org/projects/wp-plugins/query-monitor

**Comment by crstauf** [comment]
@ArthurShlain I'm not knowledgeable about i18n/l10n protocols and such; will need someone else who's familiar to make the adjustment you're requesting.

**Comment by johnbillion** [comment]
@crstauf I've merged this in, thanks, however Query Monitor shows a great deal of numerical data and I suspect this isn't the only place that benefits from declension.

@ArthurShlain Is it accurate to state that every place where QM displays a number should support numeric declension?

**Comment by johnbillion** [comment]
In 3872f24 I've added a bunch more calls to `_n()`, `_nx()` etc to allow proper plural forms for phrases which include a numeric value.
