### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by kkmuffme** [johnbillion/query-monitor#381]
version 3.1.1

PHP Notice:  Array to string conversion

in:

query-monitor/output/html/assets.php
line 192
$host   = (string) wp_parse_url( $source, PHP_URL_HOST );

line 193
$scheme = (string) wp_parse_url( $source, PHP_URL_SCHEME );

line 213
$host = (string) wp_parse_url( $error_data['src'], PHP_URL_HOST );

Could you please fix this?

**Comment by kkmuffme** [comment]
PHP 7
WP 4.5.5
URLs of styles/scripts look normal to me.

**Comment by johnbillion** [comment]
Without some more info there's not a lot to go on here, so I'll close this off.

If you're able to narrow down the problem, do please reopen this issue with more info. Thanks!
