### ISSUE TITLE
`wp-admin/post.php` requests cause "Trying to get property of non-object" in `collectors/conditionals.php`, probably via `is_front_page()`

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#384]
Traceback share https://sentry.io/share/issue/cd4986c6a8a24030acea8a5b963818e1/

`is_front_page()` looks to be involved, might be inappropriate to call during this admin request.

I'm not entirely sure what the underlying cause is, but hoping you can tell quicker. But sentry event logs show this is getting triggered daily w/ regular post editing admin work, in relatively large quantities.

**Comment by johnbillion** [comment]
Thanks for the report. I've not been able to reproduce the problem so far. Can you send over some more info?

* Which version of PHP are you running?
* Which version of WordPress are you running?
* Does the error occur during the GET request to the post editing screen, or in the POST request when performing a save?

**Comment by johnbillion** [comment]
Oh wait, that last question makes no sense. It must be during the POST because the error happens during collection in the redirect dispatcher.

**Comment by lkraav** [comment]
PHP 7.1.26, WP 4.9.9

**Comment by johnbillion** [comment]
Let me know if you can find a way to reproduce this.

**Comment by lkraav** [comment]
I think we have not seen this for ages. Maybe fixed somewhere upstream.
