### ISSUE TITLE
Add intelligence to QM window persistence

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#393]
I'm currently working on a custom rewrite rule, and am using QM to do so.

An annoyance is that opening QM on the frontend makes it open in the backend (when I need to re-save permalinks or adjust something), and closing in the backend closes it on the front.

Is it possible to add some intelligence to the cookie to differentiate between front and back ends?

**Comment by johnbillion** [comment]
Thanks for the report.

I've been thinking about this for a while, and I think that for now I'm not going to change this behaviour. It would be jarring to separate the persistence between the front end and the back end.

If you're debugging PHP errors, for example, it's not desirable for the panel's persistence to differ between the front and back end.

If you've got some specific ideas about how to improve this behaviour then let me know.

**Comment by crstauf** [comment]
Given that the frontend and backend are two very distinct, different, and separate experiences, I would not think separate persistence to be jarring.

Several things change between front and back, most notably, admin bar items: that catches you off guard at first, but after two more uses, you understand its behavior. Second notable change is the theme... you may have _Midnight_ as your admin theme, but that doesn't carry over to the front.

Given that the menu bar is always within reach, and only one click away to open QM's window, if you were debugging PHP errors, you open it once in admin, and once in front, and you're set.

With given example of debugging rewrite rules, current flow:
1. open QM on front (opened in back)
1. close QM on back (closed in front)
1. open QM on front

Debugging rewrite rules, separate persistence:
1. open QM on front

Difference: two less clicks (in just one cycle); multiplied if moving back and forth between front and back.

With the example of debugging PHP, current flow:
1. open QM on front (opened in back)

Debugging PHP, separate persistence:
1. open QM on front
1. open QM on back

Difference: one additional click, not multiplied across cycles.

If none of that convinces...

The only solution I can really think of, is a flag for the user to set their preferred behavior. I don't like this solution, but if there is someone that wants shared persistence, that's the only solution I can think of.

**Comment by johnbillion** [comment]
Cheers! Reopening for some further discussion.

**Comment by crstauf** [comment]
On [line 58 of `query-monitor.js`](https://github.com/johnbillion/query-monitor/blob/5524ee077e612e13ac6b7154da52bd83d6ba0bce/assets/query-monitor.js#L58), changing

```js
var container_pinned_key  = 'qm-container-pinned';
```

to

```js
var container_pinned_key  = 'qm-' + ( $('body').hasClass('wp-admin') ? 'admin' : 'front' ) + '-container-pinned';
```

seems to work beautifully right away. 

Local storage item names:
- `qm-admin-container-pinned`
- `qm-front-container-pinned`
