### ISSUE TITLE
Count Scripts and Style panel items

### ISSUE THREAD

**Issue by lkraav** [johnbillion/query-monitor#396]
Scripts and Styles are performance optimization potential items, similar to Duplicate Queries.
Count visibility would be highly useful.

![image](https://user-images.githubusercontent.com/147228/52639824-cdfbeb80-2edd-11e9-8c88-122ac2ea98e4.png)

**Comment by crstauf** [comment]
PR #402 submitted.

**Comment by crstauf** [comment]
@lkraav Will you please try the PR and confirm?

**Comment by lkraav** [comment]
Thanks, looks good on surface. 2 q-s, if I may:

* `sprintf()` instead of string concat, maybe?
* can counts become part of performance data structure outputs? For example, if there was a JSON-renderer, I'd like external watchdog apps to monitor for specific keys that contain these metric values, and record them. Something like `$data['assets']['header']['count']`?

**Comment by crstauf** [comment]
@lkraav Can definitely change to use `sprintf()`.

For my own info: why do you prefer `sprintf()` over concatenation? Solely for ensuring the variable is rendered as the correct type?

Regarding JSON-renderer, there's #291, which would likely be what you're ultimately hoping for. What are you thinking of specifically for this enhancement?

**Comment by lkraav** [comment]
sprintf - clarity, first. String cat is like deciphering alphabet soup.

JSON - just preparedness, as in storage of the counted values.

**Comment by crstauf** [comment]
Interesting (re `sprintf()`), as I find concats easier to read. But QM uses `printf()` and concats, and I do like the type check.

Gotcha (re JSON)... will do.

**Comment by johnbillion** [comment]
Thanks for your contributions guys, on this ticket and on others. I'm quite busy at the moment so won't be able to give much feedback for a while.

**Comment by crstauf** [comment]
@lkraav used `sprintf()`, did JSON prep, and PHP notices fixed.

**Comment by johnbillion** [comment]
Fixed in #402
