### ISSUE TITLE
Script Error - Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by NGenchev** [johnbillion/query-monitor#398]
This happened after update to new version..

Uncaught TypeError: Cannot read property 'className' of null
    at (index):925
(anonymous) @ (index):925
load (async)
(anonymous) @ (index):900

![image](https://user-images.githubusercontent.com/15788358/52778830-8a28f380-304f-11e9-88f3-4b20f471add4.png)

**Comment by johnbillion** [comment]
Thanks! That's a bug :-)
