### ISSUE TITLE
ensure_ajaxurl should not be injected on all pages & users

### ISSUE THREAD

**Issue by glagonikas** [johnbillion/query-monitor#400]
The ensure_ajaxurl() function (https://github.com/johnbillion/query-monitor/blob/master/classes/debug_bar.php#L49-L55) fires on wp_head for all users, including non-logged-in visitors of the site and users that shouldn't have access to QM.

The output is then added on all pages for all users. As this is related to the QM plugin and considering only specific users can see QM, the function should be limited.

Having read #215 we too don't have any QM plugins, yet the code is injected on our page. Tested on a fresh installation running just QM and TwentyNinteen.

**Comment by lkraav** [comment]
Sounds like solid thinking. Maybe clarify the title w/ the goal "... should not be injected ..."?

**Comment by glagonikas** [comment]
done :)

**Comment by johnbillion** [comment]
I'm not sure why #215 was closed. This should be fixed, but I recall that the last time I looked at it, it wasn't as straight forward to fix as I was expecting. PRs welcome.

**Comment by glagonikas** [comment]
I think something in the lines of 
```
if ( ! QM_Dispatcher::user_can_view() ) {
	return false;
}
```
placed at https://github.com/johnbillion/query-monitor/blob/master/classes/debug_bar.php#L12 would probably do the trick, but i'm not very familiar with the internals of this plugin and the above code might not work well or cause issues with some QM extensions?

@johnbillion @crstauf thoughts?

**Comment by crstauf** [comment]
@glagonikas Submitted PR; mind testing?

**Comment by glagonikas** [comment]
Hi @crstauf thanks for your PR. It seems to have fixed the issue and didn't notice anything out of the ordinary.

The only thing i would change, would be to move your changes to line 12, inside the `__construct()` function. This way, you'd also prevent `enqueue()` and `init_panels()` from firing when not necessary.

**Comment by crstauf** [comment]
@glagonikas In theory I would agree, though I am typically a fan of unconditionally registering assets. However, because I don't use the Debug Bar plugins, I don't want to prevent the other hook from loading; someone that uses and is familiar with QM's functionality with Debug Bar will need to test and review if the other hooks are to be prevented as well.

That may need to be a separate issue though. For now, preventing `ensure_ajaxurl()` has (tentatively) been accomplished.

**Comment by glagonikas** [comment]
I think if QM doesn't load, its extensions should't either, as they would be reliant on it to function correctly. Without it, they might throw warnings, errors and possibly even pose a security threat, so i'd prefer if QM was disabled completely so properly-coded extensions would not load and any extensions that stopped functioning would need to be updated by their authors.

Given we don't currently use any other QM extensions and your PR fixes our issue, i don't mind merging it as is.
