### ISSUE TITLE
[Simple Question] My db.php is 777

### ISSUE THREAD

**Issue by ali-han** [johnbillion/query-monitor#403]
`https://github.com/johnbillion/query-monitor/blob/master/wp-content/db.php`

I love your plugin. But I saw the db.php on filezilla under wp-content directory and its "777".
Any security risk?
Thanks.

**Comment by johnbillion** [comment]
Thanks for the message.

The file itself is set to `644` (run `git ls-tree master wp-content` from the repo root), so something on your server configuration must have switched it to `777` when you uploaded it.
