### ISSUE TITLE
Distinguish between related hooks that fired and those that didn't

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#409]
The `Hooks in Use` submenu for each panel can list a large number of hooks, many of which won't have fired during the current request.

Need a way to distinguish between those that fired and those that didn't

**Comment by crstauf** [comment]
@johnbillion How can/are you replicating this?

**Comment by johnbillion** [comment]
I got confused here with some exploratory work that I was doing locally. This panel definitely only shows hooks that have fired during the current request. Mea culpa.
