### ISSUE TITLE
Not working in every admin menu page

### ISSUE THREAD

**Issue by wakeya** [johnbillion/query-monitor#419]
Howdy and thanks for your work with query monitor,it’s super awesome! Well,it’s not working in my intranet development environment.There’s no level menu item show up in the admin toolbar,as well as every admin menu page.
1.no JavaScript errors in my browser console;
2.no fatal errors in my PHP error log;
3.theme:JustNews(A theme developed by Chinese developers)
4.os:cetos 6.1
5.wp:5.0.3
6.web server:nginx(no error log);
7.php:5.3.3
8.browser:Firefox and Chrome on Windows 10
I don't know what happened.
![query-monitor](https://user-images.githubusercontent.com/12173096/53797631-83680f00-3f71-11e9-9af6-8ded91911984.png)

Many thanks!

**Comment by crstauf** [comment]
@wakeya Minimum PHP version for QM is 5.3.6. That’s why it’s not appearing.

**Comment by johnbillion** [comment]
QM should probably show a message for this instead of failing silently.

Ref: https://github.com/johnbillion/query-monitor/blob/76a434985ed788e072059c6f14f8b31a54543d5c/query-monitor.php#L38-L40

**Comment by wakeya** [comment]
> @wakeya Minimum PHP version for QM is 5.3.6. That’s why it’s not appearing.

Thank you very much.I'll try to upgrade my PHP version later.

**Comment by wakeya** [comment]
> QM should probably show a message for this instead of failing silently.
> 
> Ref:
> 
> [query-monitor/query-monitor.php](https://github.com/johnbillion/query-monitor/blob/76a434985ed788e072059c6f14f8b31a54543d5c/query-monitor.php#L38-L40)
> 
> Lines 38 to 40 in [76a4349](/johnbillion/query-monitor/commit/76a434985ed788e072059c6f14f8b31a54543d5c)
> 
>  if ( ! QM_Plugin::php_version_met() ) { 
>  	return; 
>  }

It is quite strange. Maybe I got it wrong, but I haven't found it yet.

**Comment by crstauf** [comment]
@wakeya There isn’t a message currently... QM currently fails silently. #420 is to generate a notice to the user regarding minimum PHP version not being met.

**Comment by wakeya** [comment]
> @wakeya There isn’t a message currently... QM currently fails silently. #420 is to generate a notice to the user regarding minimum PHP version not being met.

After upgrading to PHP 7.3.3, QM can work very well.That's great!
