### ISSUE TITLE
Feature request:  Add a body class when php errors are present

### ISSUE THREAD

**Issue by scofennell** [johnbillion/query-monitor#421]
On many themes that have fixed position header, I deregister the admin bar so I don't have to deconflict it with the theme header.  It's also not uncommon for me to have fixed position elements at the bottom of the window.  I often do that when a plugin needs to output a result message in wp_footer.

So, in the corner case where I have both a pos-fix header, no admin bar, and a pos fix element in the footer, it's difficult to see Query Monitor, and I find that I can develop for a long time without noticing all the php warnings I am piling up.

If QM would instead add a body class for qm-has_php_error or something, I would add styles for that in my personal theme bootstrap.  It would be even better if the error count were passed along as a data attribute for situations when I know a third party plugin always has one php warning, say.

**Comment by crstauf** [comment]
@scofennell This would actually be pretty simple for you to implement in your personal theme bootstrap... something like this should work:

```php
add_action( 'shutdown', function() {
  if ( is_null( error_get_last() ) )
    return;

  echo '<script>document.body.classList.add( 'has-php-error' );</script>';
} );
```

**Comment by johnbillion** [comment]
I've been thinking about this @scofennell and I've decided that it's not something that I'm going to implement as it's an edge case scenario. Adding CSS to your theme to avoid a fixed position header conflicting with the admin toolbar is quite straight forward.

You could build add-on plugin based on crstauf's code above to get around your particular issue.

Cheers!

**Comment by scofennell** [comment]
It's fair enough to close this is you feel it's edge, but adding CSS to deconflict against the admin bar is a little annoying because my css would have to be non-DRY against the height of the admin bar, which changes at various media queries, and I'd have to be non-DRY against the media queries themselves as well.

I generally like crstauf's suggestion (I'd like it more if it didn't require javascript).

Thanks very much for the help and considering my request.  Great plugin and great support.

**Comment by crstauf** [comment]
Any implementation that adds a class to the `body` tag will have to use JS, in order to watch for errors throughout page generation. If you were only concerned about identifying errors before the `body` tag, you could do this pretty easily with the `body_class` filter and `error_get_last()` function.

**Comment by crstauf** [comment]
You could also output your styles directly in the `shutdown` action. It wouldn't be syntaxically correct (outside of HTML), but QM isn't either, and it'd be conditioned on if there were any errors, so a non-issue.

**Comment by scofennell** [comment]
For others interested in this, I wanted to note that I have to take care not to output that script tag in a WP REST API callback, if the callback is being called by a jQuery ajax request.
