### ISSUE TITLE
Issue with clickable stack traces

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#422]
Not sure if I'm just doing something wrong, but I cannot get clickable stack traces to work. To note: can't even get a very basic `atom://open` URL to work (ex: `atom::open?url=file:///Users/caleb/test.txt`). I've searched for any documentation on the `atom://` URI handler, and have been unable to find anything, especially specific to `atom://open`.

I'm using Local by Flywheel as my local environment.

Here's what I added in an mu-plugin:

```php
add_filter( 'qm/output/file_link_format', function( $format ) {
	return 'atom://open/?url=file://%f&line=%l';
} );

add_filter( 'qm/output/file_path_map', function( $map ) {
	$map['/app/public/'] = '/Users/caleb/Local Sites/wpdev.local/app/public/';
	return $map;
} );
```

And here's the URL generated for a `current_user_can()` trace:
`atom://open/?url=file://%2FUsers%2Fcaleb%2FLocal%20Sites%2Fwpdev.local%2Fapp%2Fpublic%2Fwp-includes%2Fcapabilities.php&line=623`

Atom does open, but the file isn't opened.

**Comment by johnbillion** [comment]
The URL looks correct to me, according to the docs at https://atom.io/packages/open.

I thought that the `open` package was included in Atom by default, but maybe it's not. Can you check and try that package if it's not installed by default?

**Comment by crstauf** [comment]
@johnbillion Confirmed; the `open` package is needed (apparently not included in Atom core).

**Comment by johnbillion** [comment]
Cheers, I'll update the blog post.
