### ISSUE TITLE
[Feature Request] Add "Time" column in "Duplicate Queries"

### ISSUE THREAD

**Issue by kkmuffme** [johnbillion/query-monitor#426]
It would be incredibly helpful if the "Dupliate Queries" pane would have a "Time" column, just like it exists for ALL other 3 query panes "Queries", "Queries by Caller" and "Queries by Component".

I would suggest to use the aggregate time of the duplicate queries (analogous how it works in the "Queries by Caller" and "Queries by Component" pane).

This would make finding the slowest duplicate queries much much faster, since not all duplicate queries have to be cross-checked with the Queries pane anymore.

**Comment by johnbillion** [comment]
This sounds like a good idea, thanks.

**Comment by johnbillion** [comment]
This got added in 3.10 👍
