### ISSUE TITLE
 Code of the page being shown.

### ISSUE THREAD

**Issue by MarNery** [johnbillion/query-monitor#431]
The code for the AMPfor WP plugin admin page (ampforwp.com) is being displayed after the last update of the plugin (Version 3.3.3). See attached in the link below.
Can you help me how to solve this bug?
See: https://prnt.sc/n0yy8h
See: https://prnt.sc/n0yyyi
This is making the page gets too large, more than 10 times the normal size.
See: https://prnt.sc/n0yz8j
--
Note: When I disable the "Query Monitor" plugin everything returns to normal as before the upgrade.
See: https://prnt.sc/n0z11m (plugin enable)
See: https://prnt.sc/n0z1t7 (plugin disable)
See: https://prnt.sc/n0z31u (Plugin Result Off)

Thanks ;)

**Comment by MarNery** [comment]
The PHP version I use is 7.3.
I do not know if this information is important. May be ;)

**Comment by johnbillion** [comment]
It looks like something on your site is dumping query output to the page when SAVEQUERIES is true. Your best bet is to ask the author of the AMP plugin about this, or search your codebase for calls to `var_dump`.
