### ISSUE TITLE
QM could show the number of database queries even if SAVEQUERIES is false

### ISSUE THREAD

**Issue by pierre-dargham** [johnbillion/query-monitor#432]
Hello John,

Here is a small feature request :

Because `$wpdb` already has an internal counter of queries (see https://github.com/WordPress/WordPress/blob/5.1.1/wp-includes/wp-db.php#L86), we could use this information when `SAVEQUERIES` is disabled. It will allow us to monitor the amount of queries on production sites, without increasing the memory usage.

I've made an example implementation - from the outside - here : https://github.com/globalis-ms/wp-cubi/blob/0.6.6/web/app/mu-modules/00-wp-cubi-core-mu/src/20-hooks-query-monitor.php#L18:L30

Bests regards,
Pierre

**Comment by lkraav** [comment]
Nice! This allows my production sites also get some easy-access sanitary insight going.
