### ISSUE TITLE
Feature Request: mock fatal error recovery

### ISSUE THREAD

**Issue by JJJ** [johnbillion/query-monitor#439]
WordPress 5.2 includes a fatal error recovery mode, whereby a mechanism in WordPress core identifies a fatal error, emails the site admin a secret link, which drops a cookie to allow admin area access with the offending extension disabled. Pretty neat! Details here:

https://make.wordpress.org/core/2019/04/16/fatal-error-recovery-mode-in-5-2/

Query Monitor already includes a few non-query tools, so it feels to me like the natural place for some preliminary support for mocking/testing this core feature to exist.

In addition to supporting the new drop-in files, I’m imaging some way to mock a fatal error, as a way to monitor that the site (and it’s relative plugins and themes) responds as expected should a fatal error occur.

Possibly as a menu-item in the toolbar drop-down.
Possibly with a new panel in the Query Monitor HUD.
Possibly with a new column in the query panel HUD to identify whether a notice or error would trigger recovery mode.

**Comment by johnbillion** [comment]
Thanks for the report @JJJ . Can you elaborate a bit? I'm not sure by what means this feature would be tested and why.
