### ISSUE TITLE
[Bug] do not output debug data for .xml

### ISSUE THREAD

**Issue by kkmuffme** [johnbillion/query-monitor#440]
If the url is .xml (e.g. sitemap.xml) query monitor should NOT output/append any debug information to the output, since it does not adhere to xml standards, thus breaking the xml completely in specific cases (e.g. if savequeries is defined)
This means we end up with a white or weird looking xml page

**Comment by crstauf** [comment]
@kkmuffme Please see #386 and read the comments and see if the instructions resolve your issue.
