### ISSUE TITLE
Show admin bar times in milliseconds instead of seconds?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [johnbillion/query-monitor#441]
20ms is more intuitive than 0.02s. 

Maybe it's a good idea to display times in milliseconds?

**Comment by johnbillion** [comment]
Thanks for the report.

QM uses seconds throughout its UI and I don't plan to change it right now. I might add an option in the future so users can choose between seconds and milliseconds, but it's not high priority.

Cheers!
