### ISSUE TITLE
Why wordpress dont show errors on desktop with this plugin? 

### ISSUE THREAD

**Issue by seriiserii825** [johnbillion/query-monitor#442]
Hi.
When i activate this plugin and do some mistake in function.php, on desktop appear this 
http://prntscr.com/npfwc1

There is no links to file with error. 

But, when i deactivate this plugin, i get a link
http://prntscr.com/npfwux

May be existing some setting for plugin, that resolve my problem?

Thanks.

**Comment by johnbillion** [comment]
Thanks for the report. I'll try to find some time over the next few days to look into it.

**Comment by johnbillion** [comment]
Fixed in 3.3.6.
