### ISSUE TITLE
Hide stats and just display "Query Monitor"?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [johnbillion/query-monitor#445]
Nice plugin. 

It's a bit distracting to see the stats on every load. 

Is there an option to just show "Query Monitor" instead of "0.49s 39,938kB 0,0220s 37Q" on the top bar and instead just notify using color when there is a potential issue which the user can click and check?

**Comment by johnbillion** [comment]
Thanks for the suggestion.

No this isn't possible currently, and to be honest it's probably not something that I'll add because I find that the stats can help you spot unexpected problems, for example a page that's performing hundreds of queries when you don't expect it to, etc.

Cheers!
