### ISSUE TITLE
Add ability to filter component

### ISSUE THREAD

**Issue by rmccue** [johnbillion/query-monitor#450]
It'd be great if there was a filter in `QM_Util::get_file_component()` (and `QM_Util::get_file_dirs()`). This could be used by third-parties to group components more easily and accurately with custom setups.

For example, the vip-plugin support could be handled entirely via filters with this approach.

**Comment by rmccue** [comment]
(Sidenote: it'd be great if the hide QM/hide core support was filterable as well, so that other components could be hidden as well.)

**Comment by johnbillion** [comment]
This came up in a support thread a while ago: https://wordpress.org/support/topic/recognize-plugins-from-other-directories/

I'm wary of adding a filter here due to how often it gets called. Filters are cheap but not free. Maybe it's not really an issue though.

**Comment by rmccue** [comment]
Alternatively, what about an initial hook to register additional dirs/components, which could then be added to the existing array and `switch`?

**Comment by johnbillion** [comment]
Yeah that sounds like it would work. Could do a filter on the initial population of the dirs in `QM_Util::get_file_dirs()` plus a filter which allows you to define a callback function that gets called to populate the name of the component.

```php
// Register the `/altis` directory as the altis-plugin component:
add_filter( 'qm/component_dirs', function( $dirs ) {
    $dirs['altis-plugin'] = '/altis';
    return $dirs;
} );

// Generate the name used for a member of the altis-plugin component:
add_filter( 'qm/component_name/altis-plugin', function( $name, $file ) {
    return 'Altis Plugin: ' . basename( $file );
}, 10, 2 );
```

**Comment by abuyoyo** [comment]
Yes please :)

**Comment by dhilditch** [comment]
Would this help us get RAM usage per component or per plugin?

**Comment by johnbillion** [comment]
Nope
