### ISSUE TITLE
Adding your own function to the "HTTP API Calls."

### ISSUE THREAD

**Issue by morkpl** [johnbillion/query-monitor#453]
Is it possible to implement my own function for HTTP API calls?

![ice_screenshot_20190610-140229](https://user-images.githubusercontent.com/11688482/59194144-59ce0d80-8b88-11e9-9eb8-edca7990d469.png)

The static function that supports curl requests is in my private plugin.

**Comment by johnbillion** [comment]
You could do this by triggering the same actions that the WordPress HTTP API does. QM uses `http_request_args` to log the start of the call, and `http_api_debug` to log the end. You'd need to make sure you pass in the correct parameters.

I would also check that you definitely need to use curl directly. There are plenty of filters and actions in the WordPress HTTP API for doing things such as setting curl options, eg the `http_api_curl` action.

**Comment by columbian-chris** [comment]
For a quick start, you could use:
```php
$request = new WP_Http;
$result = $request->request( $link );
```
...and you'll see the output in Query Monitor under "HTTP API Calls".
