### ISSUE TITLE
Feature request: Allow disabling of PHP Errors in Ajax Response

### ISSUE THREAD

**Issue by abuyoyo** [johnbillion/query-monitor#457]
Is it possible to add a QM_DISABLE_PHP_ERRORS_AJAX wp-config define to disable PHP Errors being sent to console on every heartbeat?
Or at perhaps allow disabling notice-level and below?

I'm using the console to debug an ajax plugin I'm writing. And naturally I have QM enabled for the ride.
However I have another plugin installed that throws numerous 'undefined index' notices - that color my console red and make it unreadable / a hassle to scroll through.

**Comment by abuyoyo** [comment]
I just found this 10 minutes after posting: QM_DISABLE_ERROR_HANDLER
It does the job but is perhaps over-broad. I still want to see PHP errors in QM (the stack is useful etc.), just not on every heartbeat in the console.

**Comment by johnbillion** [comment]
It sounds like you want to disable particular errors for a particular plugin that you don't have control over. You can do just this in QM: https://querymonitor.com/blog/2018/07/silencing-errors-from-plugins-and-themes/

**Comment by abuyoyo** [comment]
Oh thank you,
That's quite robust.
That blog post should be in the wiki IMO

**Comment by johnbillion** [comment]
Yeah I think I'll add some links in the wiki to the blog posts so that more users can see them.
