### ISSUE TITLE
Filter Name Conflict - wp-affiliate

### ISSUE THREAD

**Issue by codeschreiber** [johnbillion/query-monitor#458]
Hi Guys,

today i found a filter/action name conflict

conflicting part: 'get_template_part'
result: all wp-affiliate plugin shortcodes return nothing

in Query Monitor:
./plugins/query-monitor/collectors/theme.php:  
add_action( 'get_template_part', array( $this, 'action_get_template_part' ), 10, 3 );

in affiliate wp plugin:
./plugins/affiliate-wp/includes/class-templates.php: 
$templates = apply_filters( 'get_template_part', $templates, $slug, $name );

**Comment by lkraav** [comment]
I have already filed this with AffiliateWP a while ago, and they fixed it.

https://affiliatewp.com/changelog/

Version 2.2.17, May 17, 2019
Fix: Shortcodes sometimes don't display when Query Monitor 3.3.5 or later is active
