### ISSUE TITLE
PHP Warning for when cache misses and hits are zero

### ISSUE THREAD

**Issue by grappler** [johnbillion/query-monitor#459]
If both `cache_misses` and `cache_hits` are zero the then the total will be zero too.

This means the calculation `100/0` fails with a warning "Division by zero".

https://github.com/johnbillion/query-monitor/blob/develop/collectors/cache.php#L72

I have not looked into further why we are getting these results for the development sit.

**Comment by johnbillion** [comment]
Cheers. Could be related to this: https://github.com/johnbillion/query-monitor/wiki/Cache-Hit-Rate

Otherwise, please let me know the exact cache driver you're using and I'll look into it.

**Comment by lkraav** [comment]
I think I saw this with https://github.com/pressjitsu/pj-object-cache-red

**Comment by grappler** [comment]
Yes, that is the cache driver that I have installed.

**Comment by ocean90** [comment]
Created #470 with a fix for this warning.
