### ISSUE TITLE
Add RAM usage per plugin or component

### ISSUE THREAD

**Issue by dhilditch** [johnbillion/query-monitor#462]
Scalability is hurt by high RAM usage.

It would be great if the query monitor plugin could report RAM usage per plugin similar to how it can report queries per plugin

**Comment by johnbillion** [comment]
This is a great suggestion and I'd love to do it, but unfortunately it's just not possible.

Query Monitor is able to categorise queries into their respective components by looking at the calling stack trace for each query and seeing what files are included. It even does this after the fact, so the component calculation occurs right at the end of the page load.

There's no such equivalent for memory usage. At the PHP level it's not possible to determine what's consuming memory without using [ticks](https://www.php.net/manual/en/internals2.opcodes.ticks.php) and tracking ticks is incredibly resource intensive, which slows down the page and wildly skews results. I've looked into it a few times but from a practical point of view it's not workable.

If you really need to monitor memory usage at a granular level, you're best off using a lower level tool such as Tideways XHProf or Blackfire: https://github.com/johnbillion/query-monitor#related-tools

**Comment by dhilditch** [comment]
Hmm that's a shame. There is a way I can think of to measure and record it but it's fairly invasive. 

I could code a button that when you click it it deactivates each plugin one by one and records the difference in total RAM usage. 

This would be complicated by plugin dependencies but would be possible and a decent option for dev or test servers to gather this info. 

It could remember the activated plugins and reactivate then one by one and it could even measure the RAM usage in conjunction with other plugins being active or not. 

It's a bit of a dirty solution but it would gather the required info.

**Comment by johnbillion** [comment]
That's just what the P3 Profiler plugin does! :-D

Haven't used it for a long while though and I don't believe it fully works with PHP 7+.
