### ISSUE TITLE
Query monitor shows db user db and more info in source code of pages

### ISSUE THREAD

**Issue by Eckybrazzz** [johnbillion/query-monitor#463]
When using the WordPress plugin this is a real security issue. I had it installed on some sites and it helped me a lot solving problems. But I do give the advice to REMOVE it ASAP as it shows in the source html code this info below. It is sanitized for security. It only shows up when you are logged in, Shows passwords, plugins. All you need to know about a site. FYI it is not inside the WP ADMIN panel, but when visiting the site as logged in admin user front end. I could not reproduce this when you logged in as normal user, this is disabled on my sites.

I don't know how I should use Markdown. In this issue below I just posted a piece of the source but it gives the real normal html output, not the source code.

<div class="qm qm-non-tabular" id="qm-http" role="tabpanel" aria-labelledby="qm-http-caption" tabindex="-1"><div class="qm-boxed"><h2 class="qm-screen-reader-text" id="qm-http-caption">HTTP API Calls</h2><section><div class="qm-notice"><p>No HTTP API calls.</p></div></section></div></div><div class="qm qm-concerns" id="qm-http-concerned_hooks" role="tabpanel" aria-labelledby="qm-http-concerned_hooks-caption" tabindex="-1"><table><caption><h2 id="qm-http-concerned_hooks-caption">HTTP API Calls: Hooks in Use</h2></caption><thead><tr><th scope="col">Hook</th><th scope="col">Priority</th><th scope="col">Callback</th><th scope="col">Component</th></tr></thead><tbody><tr data-qm-subject="Plugin: wp-rocket non-core" data-qm-name="http request args" data-qm-component="Plugin: wp-rocket non-core"><th scope="row" rowspan="2" class="qm-nowrap qm-ltr"><span class="qm-sticky"><code>http_request_args</code></span></th><td class="qm-num">5</td><td class="qm-nowrap qm-ltr qm-has-toggle"><ol class="qm-toggler"><button class="qm-toggle" data-on="+" data-off="-" aria-expanded="false" aria-label="Toggle more information"><span aria-hidden="true">+</span></button><li><code>WP_Rocket\S\P\Updater_Subscriber-&gt;exclude_rocket_from_wp_updates()</code><br><span class="qm-info qm-supplemental">wp-content/plugins/wp-rocket/inc/classes/subscriber/Plugin/class-updater-subscriber.php:148</span></li></ol></td><td class="qm-nowrap">Plugin: wp-rocket</td></tr><tr data-qm-subject="Plugin: wp-rocket non-core" data-qm-name="http request args" data-qm-component="Plugin: wp-rocket non-core"><td class="qm-num">10</td><td class="qm-nowrap qm-ltr qm-has-toggle"><ol class="qm-toggler"><button class="qm-toggle" data-on="+" data-off="-" aria-expanded="false" aria-label="Toggle more information"><span aria-hidden="true">+</span></button><li><code>WP_Rocket\S\P\Updater_Api_Common_Subscriber-&gt;maybe_set_rocket_user_agent()</code><br><span class="qm-info qm-supplemental">wp-content/plugins/wp-rocket/inc/classes/subscriber/Plugin/class-updater-api-common-subscriber.php:129</span></li></ol></td><td class="qm-nowrap">Plugin: wp-rocket</td></tr></tbody></table></div>
--
  |  
  |  
  | <div class="qm qm-non-tabular" id="qm-transients" role="tabpanel" aria-labelledby="qm-transients-caption" tabindex="-1"><div class="qm-boxed"><h2 class="qm-screen-reader-text" id="qm-transients-caption">Transients</h2><section><div class="qm-notice"><p>No transients set.</p></div></section></div></div>
  |  
  |  
  | <div class="qm qm-non-tabular" id="qm-caps" role="tabpanel" aria-labelledby="qm-caps-caption" tabindex="-1"><div class="qm-boxed"><h2 class="qm-screen-reader-text" id="qm-caps-caption">Capability Checks</h2><section><div class="qm-notice"><p>For performance reasons, this panel is not enabled by default. To enable it, add the following code to your <code>wp-config.php</code> file:</p><p><code>define( 'QM_ENABLE_CAPS_PANEL', true );</code></p></div></section></div></div>
  |  
  |  
  |  
  |  
  | <div class="qm qm-non-tabular" id="qm-environment" role="tabpanel" aria-labelledby="qm-environment-caption" tabindex="-1"><div class="qm-boxed"><h2 class="qm-screen-reader-text" id="qm-environment-caption">Environment</h2><section><h3>PHP</h3><table><tbody><tr class=""><th scope="row">Version</th><td>7.3.8</td></tr><tr><th scope="row">SAPI</th><td>fpm-fcgi</td></tr><tr><th scope="row">User</th><td>nginx:nginx</td></tr><tr class=""><th scope="row">max_execution_time</th><td>60</td></tr><tr class=""><th scope="row">memory_limit</th><td>384M</td></tr><tr class=""><th scope="row">upload_max_filesize</th><td>384M</td></tr><tr class=""><th scope="row">post_max_size</th><td>384M</td></tr><tr class=""><th scope="row">display_errors</th><td>0<br><span class="qm-info qm-supplemental">Overridden at runtime from </span></td></tr><tr class=""><th scope="row">log_errors</th><td>1</td></tr><tr><th scope="row">Error Reporting</th><td class="qm-has-toggle qm-ltr"><div class="qm-toggler">4983<button class="qm-toggle" data-on="+" data-off="-" aria-expanded="false" aria-label="Toggle more information"><span aria-hidden="true">+</span></button><div class="qm-toggled"><ul class='qm-supplemental'><li>E_ERROR&nbsp;&#x2713;</li><li>E_WARNING&nbsp;&#x2713;</li><li>E_PARSE&nbsp;&#x2713;</li><li><span class="qm-false">E_NOTICE</span></li><li>E_CORE_ERROR&nbsp;&#x2713;</li><li>E_CORE_WARNING&nbsp;&#x2713;</li><li>E_COMPILE_ERROR&nbsp;&#x2713;</li><li><span class="qm-false">E_COMPILE_WARNING</span></li><li>E_USER_ERROR&nbsp;&#x2713;</li><li>E_USER_WARNING&nbsp;&#x2713;</li><li><span class="qm-false">E_USER_NOTICE</span></li><li><span class="qm-false">E_STRICT</span></li><li>E_RECOVERABLE_ERROR&nbsp;&#x2713;</li><li><span class="qm-false">E_DEPRECATED</span></li><li><span class="qm-false">E_USER_DEPRECATED</span></li><li>E_ALL&nbsp;&#x2713;</li></ul></div></div></td></tr><tr><th scope="row">Extensions</th><td class="qm-has-inner qm-has-toggle qm-ltr"><div class="qm-toggler"><div class="qm-inner-toggle">75 <button class="qm-toggle" data-on="+" data-off="-" aria-expanded="false" aria-label="Toggle more information"><span aria-hidden="true">+</span></button></div><div class="qm-toggled"><table><tr><td>bcmath</td><td>7.3.8</td></td></tr><tr><td>brotli</td><td>0.7.0</td></td></tr><tr><td>bz2</td><td>7.3.8</td></td></tr><tr><td>calendar</td><td>7.3.8</td></td></tr><tr><td>cgi-fcgi</td><td class="qm-false">false</td></td></tr><tr><td>Core</td><td>7.3.8</td></td></tr><tr><td>ctype</td><td>7.3.8</td></td></tr><tr><td>curl</td><td>7.3.8</td></td></tr><tr><td>date</td><td>7.3.8</td></td></tr><tr><td>dom</td><td>20031129</td></td></tr><tr><td>enchant</td><td>7.3.8</td></td></tr><tr><td>exif</td><td>7.3.8</td></td></tr><tr><td>fileinfo</td><td>7.3.8</td></td></tr><tr><td>filter</td><td>7.3.8</td></td></tr><tr><td>ftp</td><td>7.3.8</td></td></tr><tr><td>gd</td><td>7.3.8</td></td></tr><tr><td>geoip</td><td>1.1.2-dev</td></td></tr><tr><td>gettext</td><td>7.3.8</td></td></tr><tr><td>gmp</td><td>7.3.8</td></td></tr><tr><td>hash</td><td>7.3.8</td></td></tr><tr><td>iconv</td><td>7.3.8</td></td></tr><tr><td>igbinary</td><td>3.0.1</td></td></tr><tr><td>imagick</td><td>3.4.4</td></td></tr><tr><td>imap</td><td>7.3.8</td></td></tr><tr><td>intl</td><td>7.3.8</td></td></tr><tr><td>ionCube Loader</td><td>10.3.8</td></td></tr><tr><td>json</td><td>1.7.0</td></td></tr><tr><td>ldap</td><td>7.3.8</td></td></tr><tr><td>libxml</td><td>7.3.8</td></td></tr><tr><td>lz4</td><td>0.3.5</td></td></tr><tr><td>lzf</td><td>1.6.7</td></td></tr><tr><td>mailparse</td><td>3.0.4-dev</td></td></tr><tr><td>maxminddb</td><td>1.4.1</td></td></tr><tr><td>mbstring</td><td>7.3.8</td></td></tr><tr><td>mcrypt</td><td>7.3.8</td></td></tr><tr><td>memcache</td><td>4.0.4</td></td></tr><tr><td>memcached</td><td>3.1.3</td></td></tr><tr><td>mysqli</td><td>7.3.8</td></td></tr><tr><td>mysqlnd</td><td>5.0.12-dev</td></td></tr><tr><td>openssl</td><td>7.3.8</td></td></tr><tr><td>pcntl</td><td>7.3.8</td></td></tr><tr><td>pcre</td><td>7.3.8</td></td></tr><tr><td>PDO</td><td>7.3.8</td></td></tr><tr><td>pdo_mysql</td><td>7.3.8</td></td></tr><tr><td>pdo_sqlite</td><td>7.3.8</td></td></tr><tr><td>Phar</td><td>7.3.8</td></td></tr><tr><td>posix</td><td>7.3.8</td></td></tr><tr><td>pspell</td><td>7.3.8</td></td></tr><tr><td>readline</td><td>7.3.8</td></td></tr><tr><td>redis</td><td>4.3.0</td></td></tr><tr><td>Reflection</td><td>7.3.8</td></td></tr><tr><td>session</td><td>7.3.8</td></td></tr><tr><td>shmop</td><td>7.3.8</td></td></tr><tr><td>SimpleXML</td><td>7.3.8</td></td></tr><tr><td>snmp</td><td>7.3.8</td></td></tr><tr><td>soap</td><td>7.3.8</td></td></tr><tr><td>sockets</td><td>7.3.8</td></td></tr><tr><td>sodium</td><td>7.3.8</td></td></tr><tr><td>SPL</td><td>7.3.8</td></td></tr><tr><td>sqlite3</td><td>7.3.8</td></td></tr><tr><td>standard</td><td>7.3.8</td></td></tr><tr><td>sysvmsg</td><td>7.3.8</td></td></tr><tr><td>sysvsem</td><td>7.3.8</td></td></tr><tr><td>sysvshm</td><td>7.3.8</td></td></tr><tr><td>tidy</td><td>7.3.8</td></td></tr><tr><td>tokenizer</td><td>7.3.8</td></td></tr><tr><td>xml</td><td>7.3.8</td></td></tr><tr><td>xmlreader</td><td>7.3.8</td></td></tr><tr><td>xmlrpc</td><td>7.3.8</td></td></tr><tr><td>xmlwriter</td><td>7.3.8</td></td></tr><tr><td>xsl</td><td>7.3.8</td></td></tr><tr><td>Zend OPcache</td><td>7.3.8</td></td></tr><tr><td>zip</td><td>1.15.4</td></td></tr><tr><td>zlib</td><td>7.3.8</td></td></tr><tr><td>zstd</td><td>0.7.3</td></td></tr></table></div></div></td></tr></tbody></table></section><section><h3>Database</h3><table><tbody><tr><th scope="row">Server Version</th><td>5.5.5</td></tr><tr><th scope="row">Extension</th><td>mysqli</td></tr><tr><th scope="row">Client Version</th><td>50012 (5.0.12)</td></tr>

<tr><th scope="row">User</th><td>wpdb2XXXXX373</td></tr><tr><th scope="row">Host</th><td>localhost</td></tr><tr><th scope="row">Database</th><td>wp23XXXXX26238</td></tr><tr><th scope="row">key_buffer_size</th><td>33554432&nbsp;<span class="qm-info">(~32 MB)</span></td></tr><tr><th scope="row">max_allowed_packet</th><td>67108864&nbsp;<span class="qm-info">(~64 MB)</span></td></tr><tr><th scope="row">max_connections</th><td>300</td></tr><tr><th scope="row">query_cache_limit</th><td>1048576&nbsp;<span class="qm-info">(~1 MB)</span></td></tr><tr><th scope="row">query_cache_size</th><td>67108864&nbsp;<span class="qm-info">(~64 MB)</span></td></tr><tr><th scope="row">query_cache_type</th><td>ON</td></tr></tbody></table></section><section><h3>WordPress</h3><table><tbody><tr><th scope="row">Version</th><td>5.2.2</td></tr><tr><th scope="row">WP_DEBUG</th><td>false</td></tr><tr><th scope="row">WP_DEBUG_DISPLAY</th><td>true</td></tr><tr><th scope="row">WP_DEBUG_LOG</th><td>false</td></tr><tr><th scope="row">SCRIPT_DEBUG</th><td>false</td></tr><tr><th scope="row">WP_CACHE</th><td>true</td></tr><tr><th scope="row">CONCATENATE_SCRIPTS</th><td>false</td></tr><tr><th scope="row">COMPRESS_SCRIPTS</th><td>undefined</td></tr><tr><th scope="row">COMPRESS_CSS</th><td>undefined</td></tr><tr><th scope="row">WP_LOCAL_DEV</th><td>undefined</td></tr><tr><th scope="row">SUNRISE</th><td>undefined</td></tr></tbody></table></section><section><h3>Server</h3><table><tbody><tr><th scope="row">Software</th><td>nginx</td></tr><tr><th scope="row">Version</th><td>1.17.3</td></tr><tr><th scope="row">Address</th><td>111.222.333.444</td></tr><tr><th scope="row">Host</th><td>server24XXXX</td></tr><tr><th scope="row">OS</th><td>Linux 5.2.9-1.el7.elrepo.x86_64</td></tr></tbody></table></section></div></div>

**Comment by johnbillion** [comment]
There are no passwords in this output.

**Comment by johnbillion** [comment]
I mean there are no passwords in QM's output. A database name is not a password.

What's the problem here? The intention of this plugin is to provide exactly this information.
