### ISSUE TITLE
Missing styles in query monitor

### ISSUE THREAD

**Issue by JennSummers** [johnbillion/query-monitor#467]
Hello, I have 22 missing styles showing in my query monitor toolbar
<img width="1280" alt="Screen Shot 2019-09-08 at 7 18 59 AM" src="https://user-images.githubusercontent.com/47743247/64489252-1ed28900-d20e-11e9-94f5-09920a46125e.png">
 when viewing my site. I have contacted my host for support and they have suggested I contact Query Monitor Support. I have attached a screenshot, any guidance would be greatly appreciated. I have checked the forums and have not been able to find something to help. Thank you for your time. #missingstyles

**Comment by johnbillion** [comment]
This means something on your site is enqueuing these styles but they aren't registered. If I had to guess I'd say some optimisation or performance plugin is incorrectly deregistering them.

Your best bet is to deactivate your plugins one by one until the problem goes away.
