### ISSUE TITLE
Feature Request: Restrict Query Monitor to specific users by name/id

### ISSUE THREAD

**Issue by jb510** [johnbillion/query-monitor#471]
Just a feature idea, I couldn't find a past issue for it.

It would be cool if I could leave QM active but restrict it to specific users.

Why? 
Many of our clients use administrator role accounts. Hence they see QM output, which can confuse or scare them (safe to ignore errors, like ajax/heartbeat errors on WPE).  On the other hand we like it to always be active for the developers working on the site because it helps spot problems any time we navigate pages on the back or front end.

I could do this via a mu-plugin (and probably will very shortly), but it'd be a nice built in feature too.

**Comment by johnbillion** [comment]
Thanks for the report @jb510 . I don't think this is something that necessarily needs to be in QM itself, managing capabilities on a per-user or per-role basis is indeed best done with a plugin such as Members or via WP-CLI.

Cheers for the comments @crstauf @lkraav
