### ISSUE TITLE
Browser console command to show query monitor on the front end whith auth cookie on

### ISSUE THREAD

**Issue by rwsss** [johnbillion/query-monitor#472]
Is there a browser console command that can show query monitor overlay on the front end? I can see its in the source code of the page, so its there. 

PS. This plugin has been a life saver and I cannot stress this enough how useful it is. Thank you for making our lives easier!

**Comment by johnbillion** [comment]
Yep in the Settings panel (click the cog icon next to the close icon) there's a button to enable this.
