### ISSUE TITLE
[Forward Compatibility] Deprecated jQuery

### ISSUE THREAD

**Issue by pentatonicfunk** [johnbillion/query-monitor#473]
In case WP updated their JQuery Version / Themes using updated jQuery Version. these are deprecated:
- jQuery.fn.click() event shorthand is deprecated
- jQuery.fn.change() event shorthand is deprecated
- jQuery.parseJSON is deprecated; use JSON.parse

**Comment by johnbillion** [comment]
Thanks!

**Comment by absolutelynotjames** [comment]
Hey there, any chance I could assist with this? I've been looking to start making contributions to an open source project and this is one that I use almost every day. This issue looks pretty straightforward and I think I've got everything pulled down and set up in my local environment. I'd be happy to come back with a PR to tackle these!

**Comment by Buzut** [comment]
Could it work without jQuery altogether? As the main usage of the plugin is to improve performance, on many custom themes, I just don't use jQuery and can't have the plugin to work on the frontend.

**Comment by johnbillion** [comment]
Query Monitor works without jQuery, just with reduced functionality (check the Settings panel for the constant you can set to prevent QM from depending on jQuery). My long term aim is to remove jQuery entirely but it's not high priority.

**Comment by Buzut** [comment]
Thank you for the answer (and sorry for the delay for reponding!).
