### ISSUE TITLE
Feature request: add filter for http request status codes to flag as errors

### ISSUE THREAD

**Issue by pbiron** [johnbillion/query-monitor#474]
There is currently a filter to control the PHP error level for specific plugins/themes (see [Silencing Errors from Certain Plugins and Themes in Query Monitor](https://querymonitor.com/blog/2018/07/silencing-errors-from-plugins-and-themes/)) that stops the "coloured notification in the admin toolbar" for when those plugins/themes generate certain PHP errors.

It would be nice if there were a similar filter for HTTP response status codes produced by calls to `wp_remote_xxx()`.

I'm writing a plugin that does several `http_remote_head()` calls, most of which will return 404s...and that is perfectly OK and expected for the operation of that plugin.  I want Query Monitor to log the requests, but not flag these specific 404s as "errors" (i.e., not turn the QM admin bar item red).

If there were such a filter, I could bracket these `wp_remote_head()` calls with `{add,remove}_filter()`  calls that hook/unhook that filter.

**Comment by johnbillion** [comment]
I can probably add something in for this.

In the meantime, there's a `qm/collect/silent_http_errors` filter which is used to silence errors returned by the Airplane Mode plugin and errors returned when the request is blocked. If your request returns a specific error code you could use it in this filter to silence the error.

**Comment by pbiron** [comment]
Thanx!

Yeah, I saw that filter and at first thought it was promising.  But then I realized it was for `WP_Error` codes.

I guess until a version of QM is released that has a filter like I'm asking for I could wrap my calls to `wp_remote_head()` in a method and have that method return a specific `WP_Error` if the `HEAD` results in a 404 and then use `qm/collect/silent_http_errors` to silence that call.

What I'm thinking for the new filter is something like:

```
$silent_error_statuses = apply_filters( 'qm/collect/silent_http_error_statuses', array());
...
if ( $http['type'] >= 400 && ( empty( $silent_error_statuses ) || ! in_array( $http['type'], $silent_error_statuses ) ) ) {
	$this->data['errors']['warning'][] = $key;
}

I can do a PR if you'd like.
```

**Comment by pbiron** [comment]
> I guess until a version of QM is released that has a filter like I'm asking for I could wrap my calls to `wp_remote_head()` in a method and have that method return a specific `WP_Error` if the `HEAD` results in a 404 and then use `qm/collect/silent_http_errors` to silence that call.

now that I think about it, that workaround won't work :-(

**Comment by johnbillion** [comment]
You could look into the internals of WordPress core and find out what error code it uses and then wrap your calls in code that uses that error code.

**Comment by johnbillion** [comment]
Oh actually, a 404 doesn't result in an error at all does it. That's a feature of QM.

**Comment by johnbillion** [comment]
Yeah if you want to work on a PR for this that would be great.

**Comment by pbiron** [comment]
I have a patch that works for my use case.

Let me sit on it for a few days and see if I can think of any situations where it would cause harm or if there are other potential use cases that it wouldn't work for.

**Comment by pbiron** [comment]
I should also say that I have an approach that I'd prefer to the PR I opened yesterday, but it would require a bigger change to QM and in the PR I was trying to stay as close to the way the existing `qm/collect/silent_http_errors` filter is used in QM as possible.

The other approach is to apply the new filter at the end of `QM_Collector_HTTP::log_http_response()` rather than in `QM_Collector_HTTP::process()` and store the results of the filter in `$this->data['http'][ $args['_qm_key'] ]['silent_error_statuses']`, which is then checked in `QM_Collector_HTTP::process()`.   Another alternative would be to have the filter return a boolean (rather than an array of HTTP status codes), `true` to silence, `false` to signal the error/warning.

Doing it that way would allow plugins to bracket their calls to `wp_remote_xxx()` with `{add,remove}_filter` calls instead of having a "global" filter (that might then have to check the  backtrace to see if it was their call to a specific URL that triggered the HTTP statuses they want to be silenced.  But like I said, that's very different than the way `qm/collect/silent_http_errors` is currently used.

In my case, there's a small-but-non-zero chance that something else (even a possible future version of core that was requesting the URLs for which I want 404s to be silenced) and I wouldn't want my plugin to silence 404's for other requests for those URLs (hence, the checking of the backtrace in the example usage of the new filter I gave in the PR).

FYI: the URLs my plugin wants to silence 404s for are things like `https://wordpress.org/wordpress-5.3-beta3.zip` or  `https://wordpress.org/wordpress-5.3-RC1.zip`, which is why I say it is _possible_ that a future version of core might do a request on those URLs.

**Comment by johnbillion** [comment]
I'll be honest and say that I've looked at this issue and your PR a few times and I've never been entirely happy with it. I don't like the idea of being able to silence HTTP API errors even if they are only 404s.

As this is such a narrow use case I'm happy closing this off as something I won't implement. Cheers Paul!

**Comment by johnbillion** [comment]
@pbiron What I could support is not triggering the warning in the admin toolbar when a HEAD request results in a 404, because that seems like more of an acceptable situation because a HEAD request is investigative. What do you think? Don't trigger an admin toolbar warning if a HEAD request receives any 4XX error?
