### ISSUE TITLE
Is it possible to use query-monitor on non-WordPress sites?

### ISSUE THREAD

**Issue by carlo-fontanos** [johnbillion/query-monitor#477]
Hi,

I was just wondering if it's currently possible to use query-monitor on non-WordPress sites? You guys did a really great job with this plugin and it would be really nice if there's a way to consume it on custom php sites or frameworks.

**Comment by johnbillion** [comment]
Unfortunately not, most of the power of QM comes from its deep understanding of the components of WordPress.

There are some other tools out there that work similarly to QM, for example Clockwork: https://github.com/itsgoingd/clockwork. Check out the Related Tools section for more info: https://github.com/johnbillion/query-monitor/blob/develop/README.md#related-tools
