### ISSUE TITLE
Where is the debug info of AJAX requests?

### ISSUE THREAD

**Issue by JanisE** [johnbillion/query-monitor#481]
I read that this plug-in supports debugging AJAX calls, but I could not found instructions on how to do it exactly.

For example, I want to see all the queries made by a certain request. If I click on Query Monitor's Settings, a QM window appears at the bottom of the page. If I open `wp-admin/nav-menus.php`, for example, I see all the queries run to display the page in that window.

However, if I search for a page to add to the menu, the search is done in an AJAX call. Where can I see all the queries run for that request? (I found only a few metrics of the request in the response headers.)

**Comment by roborourke** [comment]
@JanisE they show up in your web browser's console. In Chrome right click and choose "Inspect" then go to the console tab, in Firefox right-click and choose "inspect element" then go to the console tab. I think it's similar for IE and Edge.

**Comment by JanisE** [comment]
I don't see anything in the console except some `ReferenceErrors`:
![ajax](https://user-images.githubusercontent.com/1469104/68330317-b869ca00-00db-11ea-9093-4b16f275b1ff.png)

The only thing I get is some totals in response headers:
![ajax2](https://user-images.githubusercontent.com/1469104/68330620-3f1ea700-00dc-11ea-9560-17253b7d57a9.png)

**Comment by johnbillion** [comment]
The totals are the only data that QM exposes food Ajax requests at the moment. Improving this is on the roadmap but no ETA just yet.
