### ISSUE TITLE
`WP_Admin_Bar::add_menu` is deprecated in favor of `WP_Admin_Bar::add_node`

### ISSUE THREAD

**Issue by afragen** [johnbillion/query-monitor#482]
Deprecated: WP_Admin_Bar::add_menu is <strong>deprecated</strong> since version 5.4.0! Use WP_Admin_Bar::add_node() instead.

Lots of errors now in trunk, 🤕

**Comment by johnbillion** [comment]
Thanks! I've already fixed this in the develop branch, I'll do a release soon.
