### ISSUE TITLE
incompatability between  query-monitor and Jetpack 8 

### ISSUE THREAD

**Issue by slartibarfast** [johnbillion/query-monitor#487]
have my site running query-monitor and as soon as JetPack 8 installed it went DOA.

Current plugin: Query Monitor (version 3.5.2) PHP version 7.2.23

Wordpress was nice enough to send me an email with the following:

`An error of type E_ERROR was caused in line 82 of the file /disk2/www/virtual/site.com/htdocs/wp-content/plugins/query-monitor/collectors/php_errors.php. Error message: Uncaught Error: Class 'Automattic\Jetpack\Roles' not found in /disk2/www/virtual/site.com/htdocs/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php:270
Stack trace:
#0 /disk2/www/virtual/site.com/htdocs/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(239): Automattic\Jetpack\Sync\Listener->get_actor('jetpack_plugins...', Array)
#1 /disk2/www/virtual/site.com/htdocs/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Listener.php(114): Automattic\Jetpack\Sync\Listener->enqueue_action('jetpack_plugins...', Array, Object(Automattic\Jetpack\Sync\Queue))
#2 /disk2/www/virtual/site.com/htdocs/wp-includes/class-wp-hook.php(288): Automattic\Jetpack\Sync\Listener->action_handler(Array, Array)
#3 /disk2/www/virtual/site.com/htdocs/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#4 /disk2/www/virtual/site.com/htdocs/wp-includes/plugin.php(478): WP_Hook->do_action(Arra
`

sorry - thats all I've got.  I'll be sending this to Automattic as well.. but with the error being raised in a query-monitor file...

**Comment by johnbillion** [comment]
Thanks for the message. This is Query Monitor's fatal error handler re-throwing an uncaught exception that it's caught.

You'll need to get in touch with Automattic about this. If it's a persistent error then you should also see it without QM active, but you might need to check your error logs to see it.
