### ISSUE TITLE
Server crash 502 latest update

### ISSUE THREAD

**Issue by wpsumo** [johnbillion/query-monitor#488]
Since the latest QM update the server crash frequently once QM is activated on the application.

**Comment by johnbillion** [comment]
What's the error in your error log?

**Comment by alriksson** [comment]
`2019/12/05 13:37:22 [error] 10242#10242: *340976 upstream sent too big header while reading response header from upstream, client: 141.8.12.2, server: domain.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "http://127.0.0.1:8081/wp-admin/admin-ajax.php", host: "domain.com", referrer: "https://domain.com/wp-admin/edit.php?post_type=post"`

**Comment by johnbillion** [comment]
Thanks. That's unlikely to be related to the latest QM update in that case. This means Nginx has a low header size limit, or your site is generating a large number of PHP errors, or a combination of both.

You should investigate the PHP errors and see if you can get those fixed.

I'm planning on adding a limit to the number of HTTP headers that QM adds to Ajax requests for just this reason, but I don't have time at the moment.

**Comment by alriksson** [comment]
Yes could be both but I have a few php notices which is reported to respective plugin developer.

Thanks, then you´re aware and I will wait continue using QM until the respective developer solved their php notices and see if it works then.

**Comment by johnbillion** [comment]
#275
