### ISSUE TITLE
[Help wanted] theme flaws cause query-monitor panel break

### ISSUE THREAD

**Issue by qijianjun** [johnbillion/query-monitor#489]
Hi, my wordpress version is 5.3, and the theme is modified by myself from a downloaded one. I have the following problem for a long time, and I think it dues to my theme flaws, do you know what may have caused this? CSS or js or html structure?

![image](https://user-images.githubusercontent.com/612912/70383552-ab761a00-19aa-11ea-8daf-1d64742705f0.png)
(very very long page and scroll bar generated)

The problem exists only in the front, and not in the wp-admin, but in the admin page, the panel's icons don't show properly, and it probably be related to some theme settings.

![image](https://user-images.githubusercontent.com/612912/70383639-1f64f200-19ac-11ea-8bbf-0f6929a9ea88.png)

**Comment by johnbillion** [comment]
It looks like the stylesheet for QM is being dequeued by your theme, or maybe your theme isn't calling the `wp_footer` hook.
