### ISSUE TITLE
Inspect loading page time

### ISSUE THREAD

**Issue by ralf00** [johnbillion/query-monitor#491]
Hello,

i have a question that is quite generic and not specific but i hope you can help me.
I'm doing a wordpress website speed analysis and my goal is to detect causes for this slowness.
Now i'm trying to understand if this is the tool for me or I need something different.
I tried using the plugin and on the overview result i see for example:
Page generation time: 2.78 s
Db query time: 0.78 s

The plugins shows me all the executed query times but what I really need to focus is on the (2.78 - 0.78) = 2 s time.

How may I go deep on that 2 seconds? i can do that with query monitor? For istance measure PHP functions execution time, or theme loading time or plugins loading time (but not just depending on queries time). do you advice me another tool? i know it could depend on hosting or other issues but i need to analyze that.

I hope someone could help me.

Thank you

Attilio

**Comment by johnbillion** [comment]
Unfortunately PHP processing time isn't something that a PHP-level app such as Query Monitor can be too helpful with (although I'm planning some additions to QM which can help pinpoint issues in slow WordPress actions or filters).

Your first port of call should be to deactivate your plugins one by one to see if there's a particular culprit that takes up most of that time.

Take a look at the recommended tools section: https://github.com/johnbillion/query-monitor#related-tools - The Tideways fork of XHProf is a very good tool, but there's a certain learning curve to using it. It provides a ton of profiling information.
