### ISSUE TITLE
Can bar be disabled on mobile views

### ISSUE THREAD

**Issue by Beee4life** [johnbillion/query-monitor#493]
Not an issue, more a question...

I use query monitor to monitor some stuff when developing (quelle surprise).

In one of my projects, I need to iframe posts as preview.... which also includes the QM bar on the bottom of the iframe, see image.

![Screenshot 2020-02-03 at 11 35 54](https://user-images.githubusercontent.com/4508731/73646426-b206d200-4679-11ea-8a6c-f7d6a22ce40c.png)

Can i disable it under certain circumstances with a filter/action or so ?

**Comment by johnbillion** [comment]
Not by default, but this is definitely a good idea.

QM was originally built to show up everywhere it should show up, but in practical terms most people don't want it showing up on things like iframes, embeds, during WordPress updates in the admin area, etc.

There's a `QM_DISABLE` constant which you could conditionally define based on the URL used in those iframes. Or inside the iframe you could inject some CSS which hides the QM bar.

I'll have a think about adding some options for better controlling situations like this where you don't always want QM showing up.

**Comment by Beee4life** [comment]
I think the constant route is the best way to go....

Would that be as easy as defining it like this ?
`define( 'QM_DISABLE', true );`

**Comment by johnbillion** [comment]
My mistake, it's called `QM_DISABLED`. You can see all the available configuration constants in the settings panel in QM.

**Comment by Beee4life** [comment]
I have defined it as `define( 'QM_DISABLED', true );` in singular.php and in the template file, but doesn't work...

**Comment by Beee4life** [comment]
I wasn't thinking clearly... Now defined it in wp-config.php and it works.... but it's too broad.

I only need it on certain conditions. wp-config.php is too early to hook into IF statements.

**Comment by johnbillion** [comment]
It depends what condition you want to target. I don't know how your iframes work.

It might be easier to conditionally load some CSS which hides QM when you don't want it.

**Comment by Beee4life** [comment]
My iframes run from a singular item (page template), which loads an acf form.
So I only need to apply it when a certain page is viewed.

May I recommend creating a simple filter which you can use by just passing false, like 
`add_filter( 'show_admin_bar', '__return_false' )`.

**Comment by Beee4life** [comment]
For QM it would be someting like `add_filter( 'disable_query_monitor', 'true' )`.

**Comment by crstauf** [comment]
@Beee4life CSS would be a better option, especially because it seems you only want to hide on small viewports (PHP won't give you that).

**Comment by crstauf** [comment]
I'm not 100% sure in my footing here, but it seems like a general best practice is to avoid negative filters, as it can get confusing in some uses. So instead of `disable_query_monitor` use `show_query_monitor`.

(`QM_DISABLED` has always struck me as odd; perhaps the reason being QM defaults to enabled and the constant disables? Like I said, I'm not confident, just something I've seen discussed.)

**Comment by Beee4life** [comment]
I don't mind which way :) as long as I can apply it selectively...

**Comment by johnbillion** [comment]
I'm going to close this off as the `QM_DISABLED` constant is sufficient for most use cases. If you've got more complicated requirements, or you need to run your conditional logic later in the loading process, then some CSS is your best bet. QM can't account for every use case.

**Comment by Beee4life** [comment]
I still think a filter would be the way to go so other users can use it as well if needed.
