### ISSUE TITLE
Unreachable break; after a return

### ISSUE THREAD

**Issue by JJJ** [johnbillion/query-monitor#496]
https://github.com/johnbillion/query-monitor/blob/88444727238cd824f338d065a8393c621556e422/collectors/php_errors.php#L117

**Comment by johnbillion** [comment]
Thanks. I tend to do this as a coding standard thing, the intention being that if I change the logic in the case block so it no longer returns then I don't need to worry about forgetting to add the break back in.

Presuming this gets picked up by PHPStan or something?

**Comment by JJJ** [comment]
The IDE that I use does not rely on PHPStan specifically, but does include real-time syntactical analysis, and this line did jump out as a problem.

I, for one, trust that you will not forget to put the break back in. It’s your project and you know the pros and cons, and it’s OK if our opinions differ here. 🤙

**Comment by johnbillion** [comment]
Cheers, I'm gonna leave this as-is for now 👍
