### ISSUE TITLE
Stack traces showing at all times 

### ISSUE THREAD

**Issue by stephenheron** [johnbillion/query-monitor#498]
Hi,

We recently upgraded Query Monitor to the latest version (3.5.2) and noticed that when we had an uncaught error, we were now displaying a stack trace in production even thought WP_DEBUG is set to false. This was a bit of a surprise. 

When we reverted back to our previous version 3.3.0 we got the expected behaviour of a message stating: 'There has been a critical error on your website.' 

We narrowed down the issue to the QM_Collector_PHP_Errors class around [here](https://github.com/johnbillion/query-monitor/blob/develop/collectors/php_errors.php#L57). In the output_fatal code it echos out to the screen the stack trace. 

We expected this behaviour to be controlled by WP_DEBUG. We completely disabled PHP errors by using the follow snippet:

    error_reporting(0);
    @ini_set('display_errors', 0);

And the stack trace still appeared which caused a bit of confusion. 

Hope this is a clear issue report, if not then please let me know.

Thanks,
Stephen

**Comment by johnbillion** [comment]
Are you using the `develop` branch of QM from GitHub? That's still a work in progress :-)

**Comment by stephenheron** [comment]
Hi @johnbillion 

Nope I tried using the latest one from the releases tab. (3.5.2)

Sorry I just noticed I linked to the develop branch, my bad!

Thanks,
Stephen

**Comment by johnbillion** [comment]
Thanks, I'll investigate then. The `output_fatal` method you pointed to only  exists in the develop branch so the problem must exist elsewhere. I'll take a  look.

**Comment by stephenheron** [comment]
Here is where on the master branch that I tracked it down to: [https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L57](https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L57)

If I removed the printf's the output disappeared.

**Comment by glagonikas** [comment]
@johnbillion I can confirm this happens on our sites also. When the plugin is active, the entire stack trace is showing to everyone, even people who are not logged in. This is a major security issue as it exposes sensitive website directories, functions etc, so it needs patching quickly.

The code responsible seems to be exception_handler found here https://github.com/johnbillion/query-monitor/blob/3.5.2/collectors/php_errors.php#L39-L86 The code linked above is different, but still has the same issue.

This code needs to check if display_errors is enabled and should only show this to admins or when the authentication cookie is set.
