### ISSUE TITLE
Can we have a "How to utilize Query Monitor on your development environment" blog post?

### ISSUE THREAD

**Issue by mayeenulislam** [johnbillion/query-monitor#50]
Query Monitor is a great plugin. But in some instances, as I'm not from PHP background, I feel that, if we can have a blog with detail explanation and direction on how to utilize Query Monitor on a site development and get a better result from WP - then it'd be much better using the plugin for a developer like us.

If possible, can we have such a blog post?

**Comment by Mte90** [comment]
Maybe we can write that on the wiki so the people can contribute and improve

**Comment by ihorvorotnov** [comment]
+1 for Wiki article! Would be happy to contribute with my experience from working with QM on a daily basis for quite a long time.

**Comment by Mte90** [comment]
The wiki is opened so everyone that want can create a new page.

**Comment by Mte90** [comment]
I created a page https://github.com/johnbillion/query-monitor/wiki/How-to-use with few infos.
I hope that we can improve that :-D
