### ISSUE TITLE
switch_to_locale error in WP_Die

### ISSUE THREAD

**Issue by tristanleboss** [johnbillion/query-monitor#511]
WordPress 5.4 (official French version)
QueryMonitor 3.5.2

By looking at my `wp-content/debug.log`, I discovered 2 fatal errors:

> [17-Apr-2020 12:27:36 UTC] PHP Fatal error:  Uncaught Error: Call to a member function switch_to_locale() on null in /public_html/wp-includes/l10n.php:1596
> Stack trace:
> #0 /public_html/wp-content/plugins/query-monitor/dispatchers/WP_Die.php(38): switch_to_locale('fr_FR')
> #1 /public_html/wp-includes/class-wp-hook.php(287): QM_Dispatcher_WP_Die->dispatch('')
> #2 /public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> #3 /public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
> #4 /public_html/wp-includes/load.php(960): do_action('shutdown')
> #5 [internal function]: shutdown_action_hook()
> #6 {main}
>   thrown in /public_html/wp-includes/l10n.php on line 1596

It's not something that happens on every page load and, unfortunately, I don't have the context of this error (URL) but it may mean something is not 100% safe.

**Comment by tristanleboss** [comment]
It seems to happen when a plugin uses the WordPress `wp_die` function in the `plugins_loaded` action.

**Comment by johnbillion** [comment]
Thanks for the report.

This might be caused by QM trying to switch locales before locales have properly loaded. I'll take a look.
