### ISSUE TITLE
"array offset on value of type bool" notice with PHP 7.4

### ISSUE THREAD

**Issue by ashleyfae** [johnbillion/query-monitor#514]
The following notice is triggered on every page load in PHP 7.4:

> PHP Notice:  Trying to access array offset on value of type bool in wp-content/plugins/query-monitor/collectors/environment.php on line 265

**Comment by johnbillion** [comment]
Thanks for the report. It looks like there's an unexpected value being returned by your server for `posix_getgrgid()`.

What's the value of Environment -> PHP -> User in Query Monitor on your server?

**Comment by ashleyfae** [comment]
This is running inside docker as uid 1000, but that uid is not in the Docker container's /etc/passwd file, which is why `posix_getpwuid( posix_getuid() )` is returning `false`. This is a relatively normal configuration for a Docker container, where you run a container under a uid that doesn't have a mapping inside the container.

**Comment by ashleyfae** [comment]
Sorry to clarify further:

`posix_getpwuid( posix_getuid() )` is returning `false`.

Then because that's `false`, `posix_getgrgid( $u['gid'] )` is effectively running as `posix_getgrgid( 0 )`

**Comment by johnbillion** [comment]
Thanks! 👍

**Comment by morganestes** [comment]
This is happening in the newer version of [Local](https://localwp.com/) on macOS, which runs the site on the local machine now (instead of in a Docker container, which is what the older version did). In that case, the user value is `mestes:` (that's me), but it's `posix_getgrgid( $u['gid'] )` that returns false.
