### ISSUE TITLE
Add an "echo" trace to query-monitor

### ISSUE THREAD

**Issue by marcsavall** [johnbillion/query-monitor#516]
Hi
Is it possible to have a function like echo to send message to query monitor window ?
Example : echoInQueryMonitor('I am in function import_inc_mp_order');
or echoInQueryMonitor('%d', $myvalue);
to help debugging.

Best regards

**Comment by johnbillion** [comment]
Yep you can do this with the logging functionality: https://querymonitor.com/blog/2018/07/profiling-and-logging/

Example:

```php
do_action( 'qm/debug', 'Hello' )
```

If you use the `develop` branch you'll be able to pass pretty much any value to this. Earlier versions only support passing in a string. I'll get a stable release out soon.
