### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in query-monitor/collectors/php_errors.php:206

### ISSUE THREAD

**Issue by BozzaDaniel** [johnbillion/query-monitor#517]
The error occurs because QM_Dispatchers::get() can return false.

In php_errors.php (line 206 is the if statement)
```
    protected function output_fatal( $error, array $e ) {
        $dispatcher = QM_Dispatchers::get( 'html' );
    
        if ( empty( $this->display_errors ) && ! $dispatcher::user_can_view() ) {
            return;
        }
```
In Dispatchers.php
```    
    public static function get( $id ) {
        $dispatchers = self::init();
        if ( isset( $dispatchers->items[ $id ] ) ) {
            return $dispatchers->items[ $id ];
        }
        return false;
    }
```

$dispatcher should be checked to see if it is false and if the class exists before executing $dispatcher::user_can_view().

Edit: formatting

**Comment by johnbillion** [comment]
Thanks for the report. Under what condition are you seeing this error?

**Comment by BozzaDaniel** [comment]
I'm getting this error in the REST-API. In the browser I'm getting the generic fatal error message from WordPress and in the error log the above error shows up. The actual fatal error is not logged anywhere.

**Comment by johnbillion** [comment]
Thanks! I'll take a look.
