### ISSUE TITLE
View line number of query

### ISSUE THREAD

**Issue by heydonovan** [johnbillion/query-monitor#52]
Using this as an example:

http://cl.ly/image/2p1T0f2Z2z16

While it indicates the query that was ran, I don't know where in the code I should begin to look. Was it index.php? Or maybe page.php? Currently I'm just grepping for "WP_Query", but that doesn't always work. While I realize further down the page it'll indicate the template, that isn't always helpful:

http://cl.ly/image/2c130s2u1D1E

**Comment by johnbillion** [comment]
It's taken me a while, but I've made some nice improvements to the way stack traces are shown in QM 2.8.0.
