### ISSUE TITLE
Feature request: add innodb_buffer_pool_size to the database environment list

### ISSUE THREAD

**Issue by arkid** [johnbillion/query-monitor#524]
This is a tiny quick change to make that would be really useful.

Basically just add the value for the mysql **innodb_buffer_pool_size** setting to the environment tab under the database variables listed.

This setting can have an absolutely massive influence on a site's performance and I've personally used WP sites that ran on VPS' that had very low default values defined for this setting.    As they were VPS hosted the users had the ability to alter this setting and upon changing it to a larger value of a few 100 MBs performance just shot up.

**Comment by johnbillion** [comment]
Fixed in 5709613.
