### ISSUE TITLE
Feature request: Show the query result size

### ISSUE THREAD

**Issue by glagonikas** [johnbillion/query-monitor#530]
It would be great if the plugin could display the size of the response sent by the SQL server (in kb/mb).

This could sit near "rows" and "time" columns on the individual queries and their aggregate near "Database Query Time" in the Overview.

**Potential use cases**
1. When writing custom queries or are looking to improve performance, understand the effect of badly written queries, such as `SELECT * FROM` instead of selecting the columns you actually need or not using `LIMIT`. This is even bigger of an issue when joining tables.
2. When having two or more servers (for example a database server and an application server) understand the amount of data that needs to be exchanged to generate a page. On a busy site, you might end up hitting the server's network limits if the server needs to exchange data with both the internet and the database.

**Comment by domSBM** [comment]
+1 I would like to see this be implemented

**Comment by johnbillion** [comment]
I've been looking into this and the short answer is this really isn't doable in any reliable way, especially without making modifications to WordPress core to calculate the result size without it being affected by other memory usage within `wpdb`. I would like to see this but I've also got other higher priority things to work on, so I'm going to close this off.

Cheers!
