### ISSUE TITLE
Error 520 When Plugin Disabled

### ISSUE THREAD

**Issue by FibroJedi** [johnbillion/query-monitor#536]
Hey,

So, after looking at the other threads, I should tell you that I use Cloudflare, first.

The plugin works fine with Cloudflare. The issue is when I disable the plugin the Error 520 appears. Re-enabling Query Monitor fixes this. A weird way round for it to be.

This may or may not be an "issue" as in something you need to fix, but is there some way of me to resolve it? Thankfully it's admin only so logged out users aren't affected.

Thanks!

**Comment by johnbillion** [comment]
An HTTP 520 error is specific to Cloudflare and means that your origin server returned an unexpected response to the Cloudflare proxy, most likely some kind of error. I'm not sure if Cloudflare provides logs that allow you to inspect the reason for these errors, might be worth checking.

Does your site show errors in the QM menu while it's active? If so, that's the first thing you should look at fixing. Check your PHP error logs too in case there's a fatal in there.

**Comment by FibroJedi** [comment]
Thanks for your reply, John 🙂

I just have 1 Warning and a few Deprecated notices, no full-on errors, no.

Sadly the PHP error logs didn't actually yield anything at all.

I was aware that it was a Cloudflare-specific error code, however it only happens when I deactivate your plugin and wasn't happening before I first installed your plugin yesterday. That's why I posted here. I hope you don't mind 🙂

________________________________

**Comment by crstauf** [comment]
Some thoughts:

1. Could it be that a plugin or theme has a dependency on Query Monitor that throws a fatal error that prevents Cloudflare from accessing origin? 
2. Is Cloudflare setup to proxy the site, or just DNS (orange or gray cloud)? If it's proxying, temporarily disable that, and see if the 520 remains. If not, you may see the error. If so, then Cloudflare support is probably your next step.

**Comment by johnbillion** [comment]
In that case I would see if you can find out any more about that 502 error from Cloudflare. Also try the usual tactic of deactivating your other plugins (and switching to a default theme such as Twenty Twenty) to see if any of them are causing the error.

**Comment by FibroJedi** [comment]
Thanks. I will go ask Cloudflare then. The only plugin that triggers it is this one. And only when it is deactivated.

Does the plugin leave any lines of code or some filed elsewhere when deactivated, do you know? That could trigger an error if it's something trying to be called that no longer exists.

Martin aka Fibro Jedi
Website<https://fibrojedi.me.uk/> | Twitter<https://twitter.com/FibroJedi> | DeviantArt<https://www.deviantart.com/fibrojedi>
________________________________

**Comment by johnbillion** [comment]
It doesn't leave anything, with the exception of `wp-content/db.php` if your server doesn't have the correct permissions to remove the symlink when the plugin is deactivated. However, this file is designed to work even when QM has been deactivated or deleted, so it shouldn't cause a problem.

You'll really need to find out the cause of the 502. If it's not a fatal error in PHP then I can only guess.
