### ISSUE TITLE
Consider changing warning when certification verification is disabled for local urls

### ISSUE THREAD

**Issue by TimothyBJacobs** [johnbillion/query-monitor#537]
We had a ticket from a customer that was concerned that they saw `sslverify=false` in the HTTP API console. The URL that had it disabled was their cron URL and was triggered by `spawn_cron` which intentionally disables `sslverify`.

I wonder if it might make sense to adjust the alert when `sslverify` is disabled because it's a local URL. Maybe in orange instead of red? Or different text?

**Comment by johnbillion** [comment]
It's supposed to not display that warning at all for local URLs, but it broke at some point quite a long while ago and I haven't gotten around to looking into it.

https://github.com/johnbillion/query-monitor/blob/2070a96369c0507f2f53c3a6abb0fc98a50e1957/output/html/http.php#L107

It looks like at some point core added the `local` arg to local requests, but that's no longer the case.

**Comment by johnbillion** [comment]
Might have happened when core switched to `Requests`? Not sure. But agreed would be nice to fix this again.

**Comment by johnbillion** [comment]
Confirmed that the `local` element in the `$args` array disappeared from core when Requests was added in WP 4.6.

**Comment by johnbillion** [comment]
https://core.trac.wordpress.org/ticket/51767
