### ISSUE TITLE
Fix potential warning with ReflectionMethod

### ISSUE THREAD

**Issue by kkmuffme** [johnbillion/query-monitor#540]
in classes/Util.php after line 234:
you use $class for ReflectionMethod

However $class can be false, triggering a fatal error
Adding a check for `if ( empty( $class ) ) { return; }` should be added.

Fyi: unfortunately I do not have a test case to reproduce it, I just saw that I had this implemented in my custom fork of the plugin and since I am currently unforking all stuff I reported it, so others can benefit from this.

**Comment by johnbillion** [comment]
Thanks for the report.

This code operates on a stack trace provided by PHP (from `debug_backtrace()`) so I can't think under what condition the class would not exist if it is present in the stack trace.

As far as I know, it's not possible to un-declare a class after it's been loaded.

Do you know of a condition under which this would be possible?

**Comment by kkmuffme** [comment]
Not really sure, we just had it happen before that we got a PHP error from that code bc class wasn't truthy.

I checked our issues (unfortunately can only see issues from the last 36 months) and it seems one error we got from there is:
>Catchable fatal error: Object of class Closure could not be converted to string

But I saw that you have it wrapped in a try/catch already now, so this seems to be solved.

**Comment by johnbillion** [comment]
Great, thanks for letting me know 👍
