### ISSUE TITLE
Use WP_CONTENT_DIR instead of hardcoding wp-content

### ISSUE THREAD

**Issue by kkmuffme** [johnbillion/query-monitor#541]
In `classes/Activation.php` instead of hardcoding `'wp-content/`, please use `basename( WP_CONTENT_DIR ) . '/`

Might want to do it within a if check for `if ( defined( 'WP_CONTENT_DIR' ) && WP_CONTENT_DIR ) {`

**Comment by johnbillion** [comment]
Thanks for the report but that path refers to the location of `wp-content/db.php` within the Query Monitor plugin ([this file](https://github.com/johnbillion/query-monitor/blob/develop/wp-content/db.php)). Note that the `$db` variable does use `WP_CONTENT_DIR` as expected.
