### ISSUE TITLE
Query Monitor Not Working with Post Action

### ISSUE THREAD

**Issue by TeamDNK** [johnbillion/query-monitor#542]
### Description
We are using `post_action_{action}` to create an edit page almost identical to the core post edit action. Since there is no way to properly replace the existing blocks editor, we are constructing the admin page to host our standalone editor. Since we are using this hook we are having to call the admin menu and top bar using the following:

`require_once ABSPATH . 'wp-admin/admin-header.php';`

### Issue
Query Monitor does not load properly. There are no JS or PHP error codes sent. The screenshot below is what happens when I hover over the plugin button. Nothing happens when clicked. Also I have confirmed that `query-monitor.js` is attached to the page.

![image](https://user-images.githubusercontent.com/64434855/94836010-4f600480-03c7-11eb-94ac-9fa1185700df.png)

### Environment
WordPress 5.5.1
Theme: TwentyTwenty _(Also tested on minimal stripped down theme)_
Server: nginx/1.17.5

Thanks,
Bula
Chief Technology Officer
The DNK Office

**Comment by johnbillion** [comment]
Thanks for the report. How are you handling the footer?

Query Monitor only outputs its data if the correct hooks have fired. In the admin area this means both the `admin_init` and `admin_footer` hooks need to fire.

**Comment by johnbillion** [comment]
Another thing to check is if anything on the site is calling `fastcgi_finish_request()`. This can cause problems by flushing the output before everything on the `shutdown` hook has finished being rendered, including the output from Query Monitor.

**Comment by TeamDNK** [comment]
> Thanks for the report. How are you handling the footer?
> 
> Query Monitor only outputs its data if the correct hooks have fired. In the admin area this means both the `admin_init` and `admin_footer` hooks need to fire.

Ah, I failed to call the footer - that makes a lot of sense. Included the admin footer and it is working now. Thanks for the quick response and help @johnbillion.

`require_once ABSPATH . 'wp-admin/admin-footer.php';`
