### ISSUE TITLE
Feature Request: preformat/monospace all QM::debug messages.

### ISSUE THREAD

**Issue by abuyoyo** [johnbillion/query-monitor#544]
I use QM::debug while developing. A very useful (and under-promoted) feature for me.

In the Log/Message column, some of the output is preformatted (array, objects..) and some is styled (string and some numbers).
I don't see the use for the non-preformatted texts in the logs. My expectation is to see variable/expression output as in any console - monospaced.

Alternatively,  add a DEFINE to allow opt-in to a pure-monospaced log.

**Comment by johnbillion** [comment]
Good idea and I agree.
