### ISSUE TITLE
can't link db.php on bedrock install (Windows)

### ISSUE THREAD

**Issue by codemonkeynorth** [johnbillion/query-monitor#547]
Hi,

I'm having trouble with the db.php file on a bedrock install of Wordpress

* Wordpress core are files in `/d/site/bedrock/web/wp/` eg `wp-admin`, `wp-includes` etc are in here and a very basic set of files in `wp-content`  (themes\twentytwenty, plugins\hello.php etc)

* project files go in `app` rather than `wp`

* `WP_CONTENT_DIR` points to  `/d/site/bedrock/web/app/`

* query monitor plugin is in  `/d/site/bedrock/web/app/plugins/query-monitor/`

what I'm also not sure what this line is doing since the original `db.php` file is in `query-monitor/db.php`:

`if ( symlink( $this->plugin_path( 'wp-content/db.php' ), $drop_in ) ) {`

note: `$drop_in` evaluates to `/d/site/bedrock/web/app/db.php`

it creates the file there, but it doesn't seem to be a symlink. I got a success mesage from WP CLI but if I run it again I get
```
PHP Warning:  symlink(): No such file or directory in /d/site/bedrock/web/app/plugins/query-monitor/classes/CLI.php on line 38
Warning: symlink(): No such file or directory in /d/site/bedrock/web/app/plugins/query-monitor/classes/CLI.php on line 38
Error: Failed to create wp-content/db.php symlink
```
and Wordpress shows:
`Extended query information such as the component and affected rows is not available. Query Monitor was unable to symlink its db.php file into place`

(above commands/paths from WSL in VSCode)

if I manually try create a symlink:
Wordpress errors out with
`Fatal error: require_once(): Failed opening required 'D:\site\bedrock/web/app/db.php' (include_path='.;C:\php\pear') in D:\site\bedrock\web\wp\wp-includes\load.php on line 470`

thanks
J

**Comment by codemonkeynorth** [comment]
hmm.. deleting the plugin and reinstalling seems to have fixed it.

i'll see if I can work out exact steps that breaks/fixes it

thanks

**Comment by abuyoyo** [comment]
I also occasionally run into this issue on my local machine (Windows). Most recently today.
Getting this message: `Extended query information such as the component and affected rows is not available. Query Monitor was unable to symlink its db.php file into place. See this wiki page for more information.`
The drop-in `db.php` file disappears sometimes.
Deactivating and re-activating Query Monitor solves the issue and restores the `db.php` drop-in. No need to delete and re-install plugin.

**Comment by johnbillion** [comment]
Does any of the info here help? https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink

I think this is an issue that you should raise with the Bedrock folks. QM isn't doing anything unusual with its symlink so the problem must be either with the environment (file permissions) or a bug in PHP itself on Windows.

I'll close this off, do drop a link here if you report this to Bedrock.
