### ISSUE TITLE
db.php issue on WPEngine

### ISSUE THREAD

**Issue by codemonkeynorth** [johnbillion/query-monitor#548]
Hi,

i think WPEngine have quite a strict filesystem so whilst I can create a symlink (in the ssh sandbox that gets copied to the main environment), I'm not sure the relevant write permissions are enabled to allow `db.php` to work

for instance we use Laravel's Blade Engine in WPEmerge framework theme for templating and have to make it write to `/tmp/blade-cache` rather than the usual location for the cache which is `wp-content/uploads/wpemerge/cache/blade`. 

I don't know what the specifics of the various permissions are but this is the only way round it.

So for query monitor to work on WPEngine I think it would need to write to `/tmp/db.php`

is there a way this could be made configurable in the config eg an option like `define('QM_DB_LOCATION', '/tmp/db.php')` ?

I don't know the current reasoning for the symlink but I don't think I can just use `/tmp/db.php` as an alternate symlink since that's probably not where the plugin expects to find it?

thanks
J

**Comment by johnbillion** [comment]
Unfortunately this is a limitation not of QM but of WordPress itself. The location must be WP_CONTENT_DIR/db.php because this file loads before most of WordPress does. More info here: https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink 

This is the first time I've heard of this not working on WP Engine, I would get in touch with their support if I were you.

**Comment by codemonkeynorth** [comment]
@johnbillion thanks for the info. 

Can you confirm it doesn’t need any write access to the db.php file itself ?

Originally I thought it was an empty file for storing output results, but it seems it’s just a PHP class?

Thanks
J

**Comment by johnbillion** [comment]
It's a dropin plugin that overrides the database driver in WordPress so queries can be logged. More info here: https://wpengineer.com/2500/wordpress-dropins/

**Comment by codemonkeynorth** [comment]
Hi thanks. 

They’ve suggested checking for a plugin clash, which I will try, but I don’t see any other plugins are creating/overwriting that `/wp-content/db.php` file

Do you think there could be another process or maybe PHP/nginx setting that could block Query Monitor from working? (again WPEngine lock things down quite a lot, and any custom configuration we have to request from support)

> Using the guide we did put in the symlink for you unfortunately I am still showing the warning in place. The plugin is working correctly just the extended information may not be available. You may want to see if another plugin is causing an issue with this working properly by disabling them if possible while keeping query monitor active.

**Comment by codemonkeynorth** [comment]
Hi @johnbillion 

Just to confirm WPEngine will not enable symlink function for PHP, so it’s a no-go on this platform which is a shame. I’ll stick to local testing

Just leaving this here for anybody with the same problem . Happy to leave closed as there’s no current solution

Thanks
J

**Comment by crstauf** [comment]
@johnbillion Why does copying the file in `query-monitor/wp-content/db.php` to `wp-content/db.php` not allow for extended query information to be collected? For those of us on WPE, copying the file manually would be a nice-to-have alternative.
