### ISSUE TITLE
Page Generation Time

### ISSUE THREAD

**Issue by heydonovan** [johnbillion/query-monitor#56]
This is in reference to my screenshot: http://cl.ly/image/3c0A0L1n3S42

I'm curious as to how total page generation time is calculated. If the "database query time" is only 4 seconds, is the rest PHP? I've even ran the page through xdebug:

http://cl.ly/image/1I2F2M2f3k3k

And as you can see, most of the time was taken up by curl_exec, but it doesn't show up in the plugin as taking up any time. Thanks, John!

**Comment by rajuginne** [comment]
so it is not server response time or ttfb
