### ISSUE TITLE
Strategy to only enable Query Monitor on production for admin users?

### ISSUE THREAD

**Issue by archon810** [johnbillion/query-monitor#560]
Hi,

I'd like to consider the possibility of using [QM_DISABLED](https://github.com/johnbillion/query-monitor/blob/develop/query-monitor.php#L59) to disable QM for all users except logged in admins. This way I would still be able to use it on production but without bogging down regular users, or risking exposing data to anyone else.

However, as a logged in admin, it's quite beneficial to be able to find slow queries and use the rest of QM.

Any ideas how to accomplish this, given that SAVEQUERIES needs to be enabled early on, and admin status functions are only available long after wp-config.php is parsed?

Our only idea was to create a new cookie for admins and then check for this cookie in wp-config.php. Thoughts?

**Comment by crstauf** [comment]
I've typically done this via IP address, but you could also play with [the `view_query_monitor` capability](https://github.com/johnbillion/query-monitor/blob/develop/classes/QueryMonitor.php#L76).

**Comment by johnbillion** [comment]
WordPress.com VIP uses a cookie-based method but I haven't looked into it in any detail: https://github.com/Automattic/vip-go-mu-plugins/blob/master/query-monitor.php

On the sites I work on at Human Made we tend to have Query Monitor installed but inactive on production, and we activate it just for debugging purposes. If your non-logged-in users are mostly hitting a static edge cache then the performance impact should be manageable, and if `SAVEQUERIES` is not defined then QM defines it for you as true only when it's active.

**Comment by archon810** [comment]
We ended up rolling this out with a cookie check method. Thanks for the input, everyone. It's incredibly useful to have on production, but without performance hits affecting non-admin users or showing them any sensitive data.
