### ISSUE TITLE
Query Monitor Reporting Query Incorrectly

### ISSUE THREAD

**Issue by MadtownLems** [johnbillion/query-monitor#563]
Hiya,

I believe I am in a situation where Query Monitor is reporting a query differently than is actually executing. 

Specifically, there are two differences:
1) It is reporting an ASC order when a DESC order was actually run  (this is my main concern)
2) the meta values differ by 2 seconds. (I don't actually care about this, but I found it very interesting) 

Here's a code snippet from my plugin:

var_dump( $query_args );
$the_query = new WP_Query( $query_args );
var_dump( $the_query->request );

Here is the output of that:

// $query_args
array(6) {
  ["post_type"]=>  string(10) "cets_event"
  ["posts_per_page"]=>  int(-1)
  ["order"]=>  string(3) "ASC"
  ["orderby"]=> string(14) "meta_value_num"
  ["meta_key"]=> string(14) "_ez_start_date"
  ["meta_query"]=>  array(2) {
    [0]=>
    array(3) {
      ["key"]=>   string(12) "_ez_end_date"
      ["value"]=> int(1607701245)
      ["compare"]=> string(1) ">"
    }
    [1]=>
    array(3) {
      ["key"]=> string(12) "_ez_end_date"
      ["value"]=> int(1923234045)
      ["compare"]=> string(1) "<"
    }
  }
}

// $the_query->request
string(836) "SELECT   wp_26_posts.* FROM wp_26_posts  INNER JOIN wp_26_postmeta ON ( wp_26_posts.ID = wp_26_postmeta.post_id )  INNER JOIN wp_26_postmeta AS mt1 ON ( wp_26_posts.ID = mt1.post_id )  INNER JOIN wp_26_postmeta AS mt2 ON ( wp_26_posts.ID = mt2.post_id ) WHERE 1=1  AND ( 
  wp_26_postmeta.meta_key = '_ez_start_date' 
  AND 
  ( 
    ( mt1.meta_key = '_ez_end_date' AND mt1.meta_value > '1607701245' ) 
    AND 
    ( mt2.meta_key = '_ez_end_date' AND mt2.meta_value < '1923234045' )
  )
) AND wp_26_posts.post_type = 'cets_event' AND (wp_26_posts.post_status = 'publish' OR wp_26_posts.post_status = 'acf-disabled' OR wp_26_posts.post_status = 'future' OR wp_26_posts.post_status = 'draft' OR wp_26_posts.post_status = 'pending' OR wp_26_posts.post_status = 'private') GROUP BY wp_26_posts.ID ORDER BY wp_26_postmeta.meta_value+0 DESC "

// what Query Monitor shows in the footer
SELECT wp_26_posts.*
FROM wp_26_posts
INNER JOIN wp_26_postmeta
ON ( wp_26_posts.ID = wp_26_postmeta.post_id )
INNER JOIN wp_26_postmeta AS mt1
ON ( wp_26_posts.ID = mt1.post_id )
INNER JOIN wp_26_postmeta AS mt2
ON ( wp_26_posts.ID = mt2.post_id )
WHERE 1=1
AND ( wp_26_postmeta.meta_key = '_ez_start_date'
AND ( ( mt1.meta_key = '_ez_end_date'
AND mt1.meta_value > '1607701243' )
AND ( mt2.meta_key = '_ez_end_date'
AND mt2.meta_value < '1923234043' ) ) )
AND wp_26_posts.post_type = 'cets_event'
AND (wp_26_posts.post_status = 'publish'
OR wp_26_posts.post_status = 'acf-disabled'
OR wp_26_posts.post_status = 'future'
OR wp_26_posts.post_status = 'draft'
OR wp_26_posts.post_status = 'pending'
OR wp_26_posts.post_status = 'private')
GROUP BY wp_26_posts.ID
ORDER BY wp_26_postmeta.meta_value+0 ASC

**Comment by johnbillion** [comment]
It sounds like the query is running more than once, maybe once for ASC and once for DESC, and the one that you're looking at in QM is not the same one you're looking at in your code. If you look through your query list, is there another query that does use DESC?

QM collects the SQL queries directly from the `$wpdb->queries` property as logged by WordPress, so there's not really any opportunity for these to be incorrect unless something on your site is messing with that property.

**Comment by MadtownLems** [comment]
This query does show in the Duplicate Queries page, both with ASC. (query count == 2)

On the general Queries tab, there is not a version of the query with DESC, no.


The numbers change each time I refresh of course, but running it again, my query_args and the_request both show a value that is +2 from the value shown by Query Monitor.

**Comment by MadtownLems** [comment]
OK - I think I figured out, at least somewhat, what was happening.

My code snippet to output the query information was in the rendering of a Block in the Editor, which is just a totally separate query than the one that is displayed in the Query Monitor output panel.

Unless Query Monitor is supposed to / expected to log those kinds of queries, this makes enough sense now.

Thanks for your time!

**Comment by johnbillion** [comment]
Ah that makes sense. Does the block use ServerSideRender? If so, the block is rendered via an Ajax call to the REST API, so the query you're looking at on the actual post editing screen is not the one used to render the block.

**Comment by MadtownLems** [comment]
Yup - that's exactly what was happening. In this case, I think I was fortunate that the query involved the current timestamp as that helped me realize the query was in fact not the same one reported.

Thanks again! (Amazing plugin, btw)

**Comment by johnbillion** [comment]
Great!
