### ISSUE TITLE
Improve support for ACF

### ISSUE THREAD

**Issue by wpsumo** [johnbillion/query-monitor#566]
Possibile to ctaegories sql calls from ACF. Right now they are under core. Would be nice if we could separate ACF and better analyze the sql queries we do with ACF to reduce or improve.

Better debugging and imrpovement of the code and sql.

**Comment by johnbillion** [comment]
Thanks for the report.

How is ACF installed? There's nothing inherent that should cause ACF to be recognised as core. Is it installed as a plugin, or a mu-plugin, or is its installation location somewhere unusual?

**Comment by wpsumo** [comment]
Advanced Custom Fields is installed as a normal plugin.

ACF is used to create custom meta fields in a more developer firendly way but still queried using native functions if I explained it correct.

To test you can just use the free ACF version in the repo. PRO includes extra but wouldn't stop you from testing as it include special fields such as repeaters etc.

https://wordpress.org/plugins/advanced-custom-fields/

Could be helpful to understand:
https://www.advancedcustomfields.com/resources/getting-started-with-acf/

Just setup a simple query and if you need to test special fields from the PRO version let me know.

**Comment by wpsumo** [comment]
@johnbillion Let me know if you need ACF pro copy for testing purposes. And if you need me to setup a sandbox for you.

**Comment by wpsumo** [comment]
@johnbillion FYI it is categorized as Plugin: advanced-custom-fields-pro in wp-admin but not frontend. Where I want to monitor to see queries is working as they should and how they cna be optimized etc.

**Comment by crstauf** [comment]
@wpsumo Can you please provide a query you're seeing come from ACF that is being miscategorized as _Core_? 

On a recent project I see the frontend queries correctly categorized as _Plugin: advanced-custom-fields_ and _Plugin: advanced-custom-fields-pro_.

**Comment by johnbillion** [comment]
Any news on this @wpsumo ?

**Comment by wpsumo** [comment]
I think @crstauf Solved it.

**Comment by johnbillion** [comment]
Cool, well I'll close this off and if you see the bug again let me know the details. 👍

**Comment by wpsumo** [comment]
Will do!
