### ISSUE TITLE
Better code trace for code snippets plugin

### ISSUE THREAD

**Issue by wpsumo** [johnbillion/query-monitor#567]
@johnbillion Would be nice if we in the frontend and in wp-admin could trace code added via a plugin like this:
https://wordpress.org/plugins/code-snippets/

So we can evaluate the performance and improve.

Right now you have to:
Find snippets database query by looking under the ‘Queries’ section and scrolling down until you see a query that starts like:

```
SELECT id, code, scope
FROM wp_snippets
```

But you don't see what is loaded or done example:

```
SHOW TABLES LIKE 'wp_snippets' | do_action('plugins_loaded') | Core | 1 | 0.0003
SELECT id, code, scopeFROM wp_snippetsWHERE scope IN ('global', 'single-use', 'front-end')AND active=1ORDER BY priority ASC, id ASC | do_action('plugins_loaded') | Core | 42 | 0.0001
```

Speaking about that what about a search function also? Would be useful.

**Comment by johnbillion** [comment]
I'm going to close this off, it's not something that I plan on implementing.
