### ISSUE TITLE
jQuery is old school, remove it from query monitor.

### ISSUE THREAD

**Issue by Mosiur404** [johnbillion/query-monitor#568]
jQuery has been a huge help to us. But in modern theme/plugin development it is not that useful. 

I have built several useful sites using Bootstrap, and as of Bootstrap 5, they are removing jQuery. I have also removed jQuery from my themes/plugins ( --- wp_deregister_script('jquery'); ---)

But query monitor doesn't work without it. So can you guys give a second thought to removing jQuery? It is time to move on.

**Comment by johnbillion** [comment]
Yeah I'm definitely planning on this, but it'll most likely happen after #483 . 

Query Monitor does work without jQuery, but in a limited state. Try setting the `QM_NO_JQUERY` constant, hopefully the output is still usable.
