### ISSUE TITLE
520 (Origin Error) in AJAX calls

### ISSUE THREAD

**Issue by jscottelblein** [johnbillion/query-monitor#57]
Love the plugin, however, I have CloudFlare enabled for my site (via the DNS method) and when I also have the Query Monitor plugin activated it caused "520 (Origin Error)" on    admin-ajax.php which means many AJAX feature across the website break.

Screenshot: http://i.imgur.com/6LTOr87.png

I first noticed it when I tried to add an image to a new post and none of the image thumbnails loaded, plus many of the Jetpack dashboard widgets just showed the loading indicator indefinitely.

I deactivated Query Monitor without making any other changes and things are back to normal.

**Comment by dabesa** [comment]
Has this even been fixed?
