### ISSUE TITLE
Undefined index: template_file

### ISSUE THREAD

**Issue by MadtownLems** [johnbillion/query-monitor#570]
PHP NOTICE: [Undefined index: template_file] in file /home/redacted/public_html/wp-content/plugins/query-monitor/output/html/theme.php:54 

I get the above notice when viewing the front-end of our sites (not when viewing dashboard pages) with QM 3.6.7 active.  Let me know if there's anything I can look into or report on from my end to help.

**Comment by enkia** [comment]
> PHP NOTICE: [Undefined index: template_file] in file /home/redacted/public_html/wp-content/plugins/query-monitor/output/html/theme.php:54
> 
> I get the above notice when viewing the front-end of our sites (not when viewing dashboard pages) with QM 3.6.7 active. Let me know if there's anything I can look into or report on from my end to help.

Bit late, but I had the same error when doing:

```
add_action('template_redirect', [$this,'home_redirect']);

...

    function home_redirect() {
        if (is_front_page() && !is_customize_preview()) {
            wp_redirect('/dashboard', 301);
        }
    }
```
I'd forgotten to add `exit` which stopped that template_file error.

```
  wp_redirect('/dashboard', 301);
  exit; 
```

**Comment by johnbillion** [comment]
The `template_include` filter that ultimately populates this value is one of the more troublesome filters that QM hooks into. You'd be surprised at the great lengths some themes go to to mess around with `template_redirect` and `template_include`.

@MadtownLems In the Template -> Hooks in Use panel in QM are there any actions or filters that might be doing something unusual on these hooks?
