### ISSUE TITLE
Consider providing additional "authentication" options for longer profiling sessions

### ISSUE THREAD

**Issue by chrisblakley** [johnbillion/query-monitor#581]
I'm back with another _"is this possible but probably not due to security"_ question. I do a ton of profiling incognito/x-browser on my live site(s) and I get too impatient to log in, set the QM cookie, then log out so lately I've just been forcing `user_can_view()` by editing `Dispacher.php` and adding a conditional for my IP address.

I'm guessing that it probably would not be allowed, but I wanted to ask anyway– is there any chance we could get a filter on that function so that I can permanently add that conditional to my own theme/plugin to always have Query Monitor's drawer available to myself? If so, I would build a toggle that can enable/disable on my non-incognito, logged-in side and I can enable it once from there and use it in as many incognito windows/browsers as needed, then turn it off when I'm done.

If that is not possible, the idea of a toggle button (even one that turns off after 60 minutes, for example) could be useful in Query Monitor itself... Maybe something like this?

![Screen Shot 2021-04-10 at 10 14 30 PM](https://user-images.githubusercontent.com/6349678/114290007-2f7e5d00-9a4a-11eb-9d52-e813886700c9.png)

Feel free to simply close this issue as I know it could be considered a grey area.

**Comment by johnbillion** [comment]
You can already do this via the `user_has_cap` filter:

```php
add_filter( 'user_has_cap', function( $allcaps ) {
	$allcaps['view_query_monitor'] = ( '1.2.3.4' === $_SERVER['REMOTE_ADDR'] );
	return $allcaps;
} );
```

It's unintuitive because the `user_has_cap` filter runs even for users who are not logged in, which you probably wouldn't expect.

Happy to add an additional and explicit filter here, but give this a try and let me know if it suits your needs.

**Comment by johnbillion** [comment]
Watch out if you run this on a site with full page caching! QM does set no-cache headers and sets the `DONOTCACHEPAGE` constant, but there might be some caching plugins out there that ignore these.

**Comment by chrisblakley** [comment]
> It's unintuitive because the user_has_cap filter runs even for users who are not logged in, which you probably wouldn't expect.

Thank you– yes I had no idea that that works for non-logged-in users so I didn't even go down that path. I can confirm that your solution here works perfectly and understood on the page caching note. Thanks again.

**Comment by crstauf** [comment]
@johnbillion This causes the output to appear, but resizing the height of the output doesn't seem to work. Should a separate issue be opened, or is this expected?

**Comment by chrisblakley** [comment]
I've noticed that too– I _believe_ this happens with the cookie method as well.

For anyone that runs into it in the meantime, if you click the "gear" icon that'll pop it open, then you can select the report tab from there (still no resizing). I was thinking that whatever JavaScript that controls the resize probably isn't enqueued on the front-end.

**Comment by crstauf** [comment]
> whatever JavaScript that controls the resize probably isn't enqueued on the front-end

Was my thought as well; wanted to check with John before acting on it.

**Comment by johnbillion** [comment]
Thanks, yes can you open an issue for that please? Might be a JS error there.
