### ISSUE TITLE
QM_COOKIE might not be defined

### ISSUE THREAD

**Issue by tivnet** [johnbillion/query-monitor#59]
```php
	public function user_can_view() {
		if ( isset( $_COOKIE[QM_COOKIE] ) ) // <---------------
			return $this->verify_nonce( $_COOKIE[QM_COOKIE], 'view_query_monitor' );
		return false;
	}
```

Theoretically, I can come here before `plugins_loaded`, and then `QM_COOKIE` is not defined yet.

**Comment by johnbillion** [comment]
QM has been considerably restructured since this ticket was opened. I'm going to close this ticket as realistically I'm not worried about this edge case issue.
