### ISSUE TITLE
Language MO file size 

### ISSUE THREAD

**Issue by wpsumo** [johnbillion/query-monitor#592]
Can not fetch MO file size in query monitor. Using WPML and WPML string translations.
Always seeing `Not Found`

**Comment by johnbillion** [comment]
Do the files actually exist at the paths listed?

**Comment by wpsumo** [comment]
@johnbillion You're right they were not downloaded therefore. Thanks to that, the one that are available shows file size.

**Comment by wpsumo** [comment]
@johnbillion Why is the plugins even loading those requests if the files is not created or used?

**Comment by johnbillion** [comment]
That's the way WordPress works, it checks to see if a translation file for the current language exists and loads it if it does.

**Comment by wpsumo** [comment]
Just looked strange as it was only 2-3 plugins that was listed there. What makes wordpress look for language file for those only? Coming from the plugin developers maybe?
