### ISSUE TITLE
Several PHP notices

### ISSUE THREAD

**Issue by slaFFik** [johnbillion/query-monitor#595]
All these notices happened at the same second.

```
PHP Notice: Undefined index: time_taken in /app/plugins/query-monitor/collectors/overview.php on line 44
PHP Notice: Undefined index: memory in /app/plugins/query-monitor/collectors/overview.php on line 64
PHP Notice: Undefined index: memory in /app/plugins/query-monitor/collectors/overview.php on line 72
PHP Notice: Undefined index: time_taken in /app/plugins/query-monitor/output/headers/overview.php on line 24
```

Unfortunately, I can't provide steps to reproduce :(

**Comment by johnbillion** [comment]
Which version of QM are you using please?

**Comment by slaFFik** [comment]
I'm not sure when exactly I updated to 3.7.1. 
But given that I always update QM to the latest version as soon as I see it live - I assume it was either 3.7.1 or the previous 3.7.0.

**Comment by johnbillion** [comment]
I'll close this off as I haven't seen this myself nor had any further reports. If you're able to reproduce the problem, do please let me know and we can re-open the issue.
