### ISSUE TITLE
symlink(): Permission denied in CLI.php line 44

### ISSUE THREAD

**Issue by enrique71** [johnbillion/query-monitor#597]
When I run `wp qm enable`, I get:
```
$ wp qm enable
Warning: symlink(): Permission denied in C:\MAMP\htdocs\RHS-Bones\wp-content\plugins\query-monitor\classes\CLI.php on line 44
Error: Failed to create wp-content/db.php symlink
```
This is after having troubleshooted missing reference to php.ini in git bash/WP-CLI on Windows MAMP, which had thrown [this mysql_connect error](https://stackoverflow.com/questions/50834815/how-to-fix-mysql-connect-error-in-wp-cli).

My apologies if this is a local environment setup problem rather than an issue - any guidance much appreciated.

**Comment by johnbillion** [comment]
Sorry you're having troubles, but there's nothing that I can do in QM to handle this. It sounds like your file permissions are messed up and you'll probably see permissions errors in other areas too if this is the case (for example when trying to update a plugin or theme).
