### ISSUE TITLE
[BUG] timing all action hooks causing 500 error

### ISSUE THREAD

**Issue by erikdemarco** [johnbillion/query-monitor#600]
I'm using server with 64GB memory.
I want to use query monitor timing function to time all wordpress action hooks but showing 500 error instead.

Here's my code:
```
add_action( 'all', 'time_start', 1 );
function time_start() {
    $current_filter = current_filter();
    do_action( 'qm/start', "{$current_filter}" ); //start timer
    add_action( $current_filter, 'time_stop', PHP_INT_MAX );
}
function time_stop( $value = null ) {
    $current_filter = current_filter();
    do_action( 'qm/stop', "{$current_filter}" );  //stop timer
    return $value;  // In case this was a filter.
}
```

When you set just 1 hook. It works perfect. But if you change it to 'all' it will show 500 error.

**Comment by johnbillion** [comment]
This causes an infinite loop because your `time_start()` function itself calls an action, which calls `time_start()`. You'll need to add a guard clause which skips calling the `qm/start` and `qm/stop` actions when the current action is `qm/start` or `qm/stop`.
