### ISSUE TITLE
problem when installing with composer.

### ISSUE THREAD

**Issue by Guillaume-Tnk** [johnbillion/query-monitor#606]
I have installed the plugin with composer like so:
```
...
{
            "type": "package",
            "package": {
                "name": "johnbillion/query-monitor",
                "version": "3.7.1",
                "type": "wordpress-plugin",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/johnbillion/query-monitor/archive/refs/heads/master.zip"
                }
            }
        }
...
...
"require": {
        ...
        "johnbillion/query-monitor": "3.7.1"
    },
...
```
Upon activation I get this message in the WordPress dashboard:
```
Asset files for Query Monitor need to be built. Run npm i && npm run build from the app/plugins/query-monitor directory.
```
when i do so:
```
npm WARN saveError ENOENT: no such file or directory, open '/path/plugins/query-monitor/package.json'
```
On the front end of the site, I'm getting a lot of output from "query monitor".
I'm trying to use the plugin with a bedrock install, I don't know if it's me doing something wrong, a problem with the plugin itself, or compatibility with bedrock. [https://roots.io/docs/bedrock/master/compatibility/](https://roots.io/docs/bedrock/master/compatibility/)

Any help would be much appreciated.

Edit:
I also tried to install the plugin from the .zip file downloaded from the master branch, develop branch and release branch and install it in the plugin directory manually in a non-bedrock installation to try to find where the issue might come from, but I'm getting the same result.

**Comment by johnbillion** [comment]
There's no need for the `package` information in composer.json. Just use the `require` like a normal Composer dependency and you'll be all good.

**Comment by Guillaume-Tnk** [comment]
> There's no need for the `package` information in composer.json. Just use the `require` like a normal Composer dependency and you'll be all good.

Thank you, I didn't know I could do that, I thought I had to do it the way I did because I couldn't find the plugin on [https://wpackagist.org/](https://wpackagist.org/).
It's working, awesome! 
Thank you!
