### ISSUE TITLE
Query Monitor Throwing "QM output does not exist" Errors

### ISSUE THREAD

**Issue by jesgs** [johnbillion/query-monitor#609]
Hi there! I’m a developer for the Create by Mediavine plugin and our team has recently discovered a quirky bug while developing alongside Query Monitor.

Query Monitor is throwing `QM error from JS: QM output does not exist` errors when using the latest version of our plugin (we didn’t check previous versions) and the WordPress Customizer (latest version). In both instances, there’s an iframe that is remote-loading a preview page, which seems to be the issue.

In Create, this happens when editing a card of any type (Recipe, How-To, or List). In the WordPress Customizer, the error appears when navigating to WordPress Admin > Appearance > Customize.

Through step debugging, our team was able to narrow this down to `window.addEventListener('load')` firing twice--once on the main page, and again inside the iframe, where the `<div id="query-monitor-main"></div>` element isn’t present.

Good luck!

-Jess

**Comment by MadtownLems** [comment]
We're also seeing this on the new Block-based Widgets screen.

**Comment by HRoger** [comment]
I have the same issue when loading iframes

**Comment by bozzmedia** [comment]
I am running into this issue as well. I noticed this particularly when using the customizer [wp-admin/customize.php]

> QM error from JS: QM output does not exist query-monitor.js:754:11
    <anonymous> https://redacted.com/wp-content/plugins/query-monitor/assets/query-monitor.js?ver=1621284575:754
    (Async: EventListener.handleEvent)
    <anonymous> https://redacted.com/wp-content/plugins/query-monitor/assets/query-monitor.js?ver=1621284575:723
