### ISSUE TITLE
Want to debug/explore snippet defined variables

### ISSUE THREAD

**Issue by shahzaib3311** [johnbillion/query-monitor#624]
I Want to debug/explore snippet defined variables to show what data those variables are in snippet holding but unfortunately, I'm unable to see log/dump as its PHP code. Need help in printing variables for debugging purposes. Suppose I've a snippet activated 
`function action_woocommerce_checkout_order_processed( $order_id, $posted_data, $order ) { /* $hello = "Hi User"*/}` I want to see $hello value when this snippet will be triggered.

I've used do_action but its not showing any logs.

**Comment by johnbillion** [comment]
There's documentation for this here: https://querymonitor.com/docs/logging-variables/ . Does that work for you?

**Comment by johnbillion** [comment]
Perhaps the code that you're testing isn't being called? I recommend adding additional logging in many places to track your code path, then you can start to identify why your code isn't being called.

**Comment by shahzaib3311** [comment]
@johnbillion I'm confirming after reassurance the function is being called and doing its job but the variable is not getting logged in the log monitor.
