### ISSUE TITLE
Add Object Cache Pro to add-on list

### ISSUE THREAD

**Issue by tillkruss** [johnbillion/query-monitor#642]
Object Cache Pro is extending Query Monitor quite a bit, can we add it to the [add-on list in the wiki](https://github.com/johnbillion/query-monitor/wiki/Query-Monitor-Add-on-Plugins)?

<img width="1822" alt="Screen Shot 2022-01-06 at 10 33 26 AM" src="https://user-images.githubusercontent.com/665029/148433149-e44628ff-bd2b-4f32-a07f-a4f1e0da3637.png">

<img width="1823" alt="Screen Shot 2022-01-06 at 10 33 51 AM" src="https://user-images.githubusercontent.com/665029/148433157-9b2d1529-04e0-4ada-a8fa-90590692be43.png">

**Comment by johnbillion** [comment]
Done, thanks!
