### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by simplysexyboy** [johnbillion/query-monitor#650]
got fatal error with query monitor not sure what is the problem?

[10-Jan-2022 11:14:06 UTC] PHP Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, string given in /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php:376
Stack trace:
#0 /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(376): array_shift()
#1 /sites/example..com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(111): QM_Output_Html_DB_Queries->output_query_row()
#2 /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(54): QM_Output_Html_DB_Queries->output_error_queries()
#3 /sites/example.com/files/wp-content/plugins/query-monitor/dispatchers/Html.php(325): QM_Output_Html_DB_Queries->output()
#4 /sites/example.com/files/wp-includes/class-wp-hook.php(303): QM_Dispatcher_Html->dispatch()
#5 /sites/example..com/files/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#6 /sites/example.com/files/wp-includes/plugin.php(470): WP_Hook->do_action()
#7 /sites/example..com/files/wp-includes/load.php(1097): do_action()
#8 [internal function]: shutdown_action_hook()
#9 {main}
  thrown in /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php on line 376
[10-Jan-2022 11:15:04 UTC] PHP Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, string given in /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php:376
Stack trace:
#0 /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(376): array_shift()
#1 /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(111): QM_Output_Html_DB_Queries->output_query_row()
#2 /sites/example.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php(54): QM_Output_Html_DB_Queries->output_error_queries()
#3 /sites/example.com/files/wp-content/plugins/query-monitor/dispatchers/Html.php(325): QM_Output_Html_DB_Queries->output()
#4 /sites/example.com/files/wp-includes/class-wp-hook.php(303): QM_Dispatcher_Html->dispatch()
#5 /sites/example.com/files/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#6 /sites/example.com/files/wp-includes/plugin.php(470): WP_Hook->do_action()
#7 /sites/example.com/files/wp-includes/load.php(1097): do_action()
#8 [internal function]: shutdown_action_hook()
#9 {main}
  thrown in /sites/alfa.topiom.com/files/wp-content/plugins/query-monitor/output/html/db_queries.php on line 376

**Comment by johnbillion** [comment]
Thanks for the report 👍
