### ISSUE TITLE
Undefined index on /output/html/languages.php:79

### ISSUE THREAD

**Issue by evscoding** [johnbillion/query-monitor#651]
With new WPML (I know, some websites still use it) there is an 'Warning' for `Undefined index: file` and `Undefined index: line` on `wp-content/plugins/query-monitor/output/html/languages.php:79`.
Dumping the `$mofile['caller']` I was able to spot that that on these cases $mofile['caller'], has ['function'], which has 'calling_file' instead of 'file' and 'calling_line' instead of 'line'.

I have done a quick fix just by checking `$mofile['caller']['function']` and then calling relevant arrays. something like this:

```php
elseif ( $mofile['caller']['function'] ) {
    echo '<td class="qm-nowrap qm-ltr qm-has-toggle">';
    echo self::build_toggler(); // WPCS: XSS ok;
    echo '<ol>';
    echo '<li>';
    echo self::output_filename( $mofile['caller']['function'], $mofile['caller']['calling_file'], $mofile['caller']['calling_line'] ); // WPCS: XSS ok.
    echo '</li>';
    echo '</ol></td>';
}
```

**Comment by johnbillion** [comment]
Thanks, there have been a few reports of this but I've not fixed it so far because I'd like to get to the root cause of the problem. I'll try out WPML and see if I can identify the cause.

Could you let me know which other plugins are active on your site please?

**Comment by evscoding** [comment]
> Thanks, there have been a few reports of this but I've not fixed it so far because I'd like to get to the root cause of the problem. I'll try out WPML and see if I can identify the cause.
> 
> Could you let me know which other plugins are active on your site please?

Sure thing. Just tried to pinpoint exactly my findings. As I have mentioned, this is just a quick fix, maybe you can come up with better solution.

Have a great day!

**Comment by johnbillion** [comment]
I've found the root cause
