### ISSUE TITLE
Admin bar vanished on frontend even after disabling query monitor

### ISSUE THREAD

**Issue by andrepetrini** [johnbillion/query-monitor#653]
Hi folks,
I installed Query Monitor and used it for a while, but I missed the admin bar in front end. 
So I uninstalled Query Monitor to bring it back. Turns out it didn't. Now, even with the plugin completely deleted, I can't use the admin bar on frontend.
I already checked (and unchecked and checked again) the option on user profile, and added the QM_DISABLED to my wp_config, without any results about that.

**Comment by johnbillion** [comment]
Sorry to hear this. Query Monitor doesn't make any persistent changes to your site and certainly doesn't hide the admin toolbar. Did you install or update any other plugins or themes recently?

**Comment by andrepetrini** [comment]
Yes, Query Monitor.
