### ISSUE TITLE
Query by Component not available

### ISSUE THREAD

**Issue by wes-davis** [johnbillion/query-monitor#654]
Hi there,

The “[How To Use Query Monitor](https://querymonitor.com/docs/how-to-use/)” page shows three Queries panels in the admin toolbar menu: Queries, Queries by Caller, and Queries by Component.

However, after installing the current version of the plugin, the Queries by Component panel is not visible — the only two options under "Query" are Duplicate Queries and Queries by Caller.

How can I access the Queries by Component functionality?

**Comment by johnbillion** [comment]
Do you see a warning on the Queries panel about the database drop-in not being in place? If so, this is the reason QM can't calculate the component responsible for each query.

Info here: https://github.com/johnbillion/query-monitor/wiki/db.php-Symlink

**Comment by shakir544** [comment]
Followed steps from the wiki. Still no luck. Getting the same error. "Extended query information such as the component and affected rows is not available. Query Monitor was unable to symlink its db.php file into place. See this wiki page for more information.
"

**Comment by johnbillion** [comment]
Sorry to hear that. You'll need to ask your host for advice in that case. Best of luck!
