### ISSUE TITLE
is it possible to log variables from cron tasks?

### ISSUE THREAD

**Issue by neoswf** [johnbillion/query-monitor#656]
Hi there.
I am able to log variables in a normal php code, but unable to log inside cron tasks. 
Is there a magic way to solve that? 

Printing echo would not work, cause the cron task runs unsynchronized, but I imagined that QM would save variables that been created in a log file, or maybe i'm wrong....

Sorry if it's a lame question to ask. I'm much more of a frontend developer.  Thank you for all the helpers.

**Comment by johnbillion** [comment]
Unfortunately not -- not at the moment anyway.

QM only operates on the current request (ie. the current page load) and doesn't read any logs. As you correctly state a cron event runs asynchronously so there's no way to see it with QM.

Your best bet for now is to use PHP's `error_log()` function and then read the logged values from your error log file, which should be `wp-content/debug.log` with a vanilla WordPress setup, or use a fully featured APM service which supports logging.

A future version of QM will allow you to view data for requests other than the current request, but it's a long way off and there's no ETA at the moment.

**Comment by neoswf** [comment]
Hey John and thank you for your extremely fast response.

Debugging wp-cron is really a headache. I'm used for working with chrome inspector, and lack of option to access the scope and easily debug is extremely frustrating. I feel like I'm back at the days of internet explorer 4, the days before firebug came to ou life, where I was using alert() to debug.

But thankfully I am able to write vars using QM. I will try to print what ever I can outside of the cron job, linearly inside functions. Ill try also using error_log().

A question. Why have you said "vanilla WordPress setup"? In any WP setup I can write to 'debug.log', like with the wp_debug constant, or am I wrong & I did not get ya?

**Comment by johnbillion** [comment]
I feel you with the cron pain. I'm also working on a logger for my WP Crontrol plugin but similarly, no ETA on that just yet.

> Why have you said "vanilla WordPress setup"?

What I meant is that it's possible for the server to be configured so `error_log()` writes to a file other than debug.log, but a standard setup should be fine.

**Comment by neoswf** [comment]
Take all the time you need man :) Its a big big task and the road is very long. I get ya :)

Taking advantage of the subject you just raised, I actually suffer from this problem 😃. 
On one WP VM I get `debug.log` to be written perfectly, but on the other VM, nothing get written. 1 machine is a clone of the other one, and yet, they behave differently (both sits on GCP).

I double checked `php.ini` in the `Error handling and logging` and both files are identical, and as well `wp.config.php`.

If it's not too much to ask, got any idea where more can I look for?
