### ISSUE TITLE
Possible to use outside of WordPress with WP_USE_THEMES = false?

### ISSUE THREAD

**Issue by ten9inc** [johnbillion/query-monitor#657]
I have a custom app that resides outside of WordPress and I'm loading WordPress to use its functionality by including wp-load.php with WP_USE_THEMES set to false.

All of the functionality of WordPress works just fine in my external app, with the exception of Query Monitor. QM does work if I'm within WordPress (both front and backend).

It appears as though all of the plugin's scripts and styles are loading, and I have the admin bar menu option 'Query Monitor'. However, the admin bar menu is empty and I have a console error "QM error from JS: QM output does not exist". I do not see the Query Monitor output injected into my templates.

My app makes use of wp_head() and wp_footer(), so I'm not sure what action isn't firing properly to completely load QM. Do you have any ideas, and is it even possible to get it to work? I have a few wpdb queries in my app that I would like to troubleshoot and QM would be very helpful!

**Comment by johnbillion** [comment]
Possibly the `shutdown` action isn't firing. This fires at the end of the request and QM uses it to output its data at the last possible point.

**Comment by johnbillion** [comment]
I'll close this off as I don't have spare time at the moment to be of any more help, but a good place to investigate is whether other required hooks aren't firing such as `shutdown` that I mentioned above.
