### ISSUE TITLE
PHP Fatal error: Cannot declare class QM_PHP, because the name is already in use

### ISSUE THREAD

**Issue by juncaveim** [johnbillion/query-monitor#659]
When I upgraded the Query Monitor plugin to 3.8.2 version, my site is crashing, any ideas to fix it? Thank you.

PHP Fatal error:  Cannot declare class QM_PHP, because the name is already in use in /htdocs/wp-content/plugins/query-monitor/classes/PHP.php on line 8

**Comment by johnbillion** [comment]
Can you try deleting and reinstalling the plugin? This sounds like it might be caused by a partially failed upgrade. Try deleting the `wp-content/db.php` file too.

**Comment by juncaveim** [comment]
Thanks for your response. Do you have permanent fix for it? Because from time to time, I'm pulling the files from production to staging and that's when the errors occurring.

I tried to add "if ( ! class_exists( 'QM_PHP' ) ) {" before the QM_PHP class is defined (see below screenshot) and it seems it fixed the error.
![Edit-Plugins-‹-MyEmpowerU-—-WordPress](https://user-images.githubusercontent.com/81988141/154091969-c389fad8-804e-41f3-8411-4e72564149c6.png)

**Comment by johnbillion** [comment]
Are you pulling the `wp-content/db.php` symlink too? In that case you need to fix the location that the symlink points to when you move the files.

**Comment by johnbillion** [comment]
> In that case you need to fix the location that the symlink points to when you move the files.

If you're moving files around en masse, you need to ensure that any symlinks amongst those files are updated. This isn't anything specific to Query Monitor.

Cheers!
