### ISSUE TITLE
Standart Woocommerce import process freezes with QM

### ISSUE THREAD

**Issue by qzya** [johnbillion/query-monitor#663]
QM: 3.8.2
WooCommerce: 5.7.1

Standart Woocommerce import process freezes when I trying to import not very big csv file (about 2000 lines and 2 columns)
Apache error log: 
```
[Sun Mar 13 22:41:32.514281 2022] [php7:error] [pid 15510] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/***/***/***/***/wp-content/plugins/query-monitor/classes/Backtrace.php on line 276, referer: https://***/wp-admin/edit.php?post_type=product&page=product_importer&step=import&file=***%2Fwp-content%2Fuploads%2Fto_private-2.csv&delimiter=%2C&update_existing=1&_wpnonce=7433b06d2b
```
\+ Ajax error in browser console: Internal Server Error 500

Disabling QM solves the problem.

**Comment by johnbillion** [comment]
Yeah this is due to the amount of data that QM collects and causes memory exhaustion. You can get around this problem though: https://wordpress.org/plugins/query-monitor/#can%20i%20prevent%20query%20monitor%20from%20collecting%20data%20during%20long-running%20requests%3F
