### ISSUE TITLE
QM reporting error from itself

### ISSUE THREAD

**Issue by columbian-chris** [johnbillion/query-monitor#665]
I have a site where Query Monitor is reporting these PHP notices on my single custom post type pages:

```
Trying to get property 'labels' of non-object | wp-content/plugins/query-monitor/collectors/request.php:242
Trying to get property 'singular_name' of non-object | wp-content/plugins/query-monitor/collectors/request.php:242
```

On the line of code QM is referring to, it's calling `get_post_type_object('name_of_post_type')` and it's returning `null`.  My post type is defined in the `init` hook and the labels is the post type registration are defined so I can't figure out what the problem could be.  It isn't doing it on other custom post type single pages.  Nothing appears to be working abnormally at all on the page.  Any thoughts here as to why this might be happening?

**Comment by columbian-chris** [comment]
This might be the result of `register_post_type()` only being called on the admin side in my plugin.  I'm thinking it needs to be called on the front end also in order for functions like `get_post_type_object()` to work, even though all the elements of my page appear to render correctly.

**Comment by johnbillion** [comment]
Ah yeah that sounds like the culprit. I'm surprised the front end is giving you the expected results to be honest.
