### ISSUE TITLE
Got weird link to wordpress.org every time I click on a button or a panel.

### ISSUE THREAD

**Issue by ngdangtu-vn** [johnbillion/query-monitor#668]
Here is the weird link:

```
localhost/"https:////wordpress.org//support//article//site-editor///"
````

The whole debug panel was wrapped by an anchor tag. So whenever I clicked on any where in the panel such a link, a button, or even non-clickable text, the whole site got redirect to the link above. Only the side panel are worked normally. See the screen below to understand which zones have this weird link:

![Red zones are places wrapped by weird link tag](https://user-images.githubusercontent.com/68631458/163659944-f897b819-acff-4697-b05e-becf73fcb887.png)

The red zones are places that wrapped by weird link, green zone is working normally.

And I only got this bug right after I updated the plugin to version `3.9.0` (the one that supports dark theme)

Update: It's like every link has been turned into the weird one.
![image](https://user-images.githubusercontent.com/68631458/163660663-6f6b5563-e8e4-4bd0-a966-25571cdc94f8.png)

**Comment by johnbillion** [comment]
Thanks for the report.

Does this only affect QM or does it affect other areas of the page?

Does it happen in the admin area as well as the front end?

Are you sure it was caused by the update to QM 3.9.0? Does the problem persist if you revert to 3.8?

Can you try switching to a default theme such as Twenty Twenty-One?

**Comment by ngdangtu-vn** [comment]
My apologize for making a quick conclusion. It seems like it is not entirely the plugin fault. I believe part of it was my theme fault.

1. It only affects QM
2. It didn't affect in admin area.
3. After I check, it is not `3.9.0` fault. The same problem happens in `3.8.2` as well.
4. Default theme didn't cause this error. (But this only happens to mine today)

Thanks to your question, I've been able to narrow down the scope and found out the problem.

1. My theme, I'm developing and it could cause some conflicts to other plugins. I'll double check on it.
2. The `db.php` symlink of Windows 10. After I'd disabled this file (add suffix xx after the name) thing went back to normal.

Sorry for trouble. But could I keep this issue alive? I would like to post the root reason that cause this trouble in here so other people can avoid it it making their theme. (After that I will close the issue).

**Comment by johnbillion** [comment]
Yep let me know when you've found the problem!

**Comment by ngdangtu-vn** [comment]
This is the latest code I use to read all the queries: (I kept it at the end of the footer.php)

```
<pre><?php print_r(count($GLOBALS['wpdb']->queries)) ?></pre>
<pre><?php print_r($GLOBALS['wpdb']->queries) ?></pre>
```

With this config in `wp-config.php`:
```
define('SAVEQUERIES', true);
```

If I remove these code, everything back to normal.

I remember that I try to do micro optimization queries (disable main query & remove duplicate queries) since QM wasn't able to help me find duplicated and I want to avoid set symlink in Windows. Well I should not use this trick. Somehow it broke the plugin.
