### ISSUE TITLE
Add custom data

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#67]
Do you plan to provide a function (instead of vardump) to add custom data to QM output?

**Comment by crstauf** [comment]
Just added `QM_dump` function to my `query_monitor_extend` plugin.
probably not memory efficient, but so far it works fine.

https://github.com/crstauf/query-monitor-extend

Basic usage:
`$array = array(
    'dawn',
    'morning',
    'noon',
    'afternoon',
    'evening',
    'dusk',
    'night',
    'midnight'
);
QM_dump('$array',$array);
QM_dump('$array',$array,true); // don't use multiple tables`

**Comment by johnbillion** [comment]
Closing in favour of https://wordpress.org/plugins/query-monitor-extension-checking-variables/ and https://github.com/crstauf/query-monitor-extend which both provide this.

**Comment by darklx** [comment]
@crstauf I have install your query-monitor-extend plugin and called QM_dump, where can I see the output ?

**Comment by darklx** [comment]
@crstauf Emm... plugin get an warning ,let me see take a look.
Warning: Invalid argument supplied for foreach() in /www/wwwroot/xxx/www/wp-content/plugins/query-monitor/output/Html.php on line 42
--
