### ISSUE TITLE
NS_ERROR_STORAGE_CONSTRAINT error

### ISSUE THREAD

**Issue by testtomat** [johnbillion/query-monitor#672]
I can't use the plugin in my development environment. The development enviroment is a copy of my productive environment with changes of [site_url] and [home] in table options. Additionally I tried a new installation of the plugin. Both ways results in the following error:

Uncaught 
Exception { name: "NS_ERROR_STORAGE_CONSTRAINT", message: "", result: 2153971715, filename: "http://dev.<mydomain>.de/wp-content/plugins/query-monitor/assets/query-monitor.js", lineNumber: 70, columnNumber: 0, data: null, stack: "@http://dev.<mydomain>.de/wp-content/plugins/query-monitor/assets/query-monitor.js:70:28\ne@http://dev.<mydomain>.de/wp-includes/js/jquery/jquery.min.js:2:30038\nDeferred/then/l/</t<@http://dev.<mydomain>.de/wp-includes/js/jquery/jquery.min.js:2:30340\n" }
​
columnNumber: 0
​data: null
​filename: "http://dev.<mydomain>.de/wp-content/plugins/query-monitor/assets/query-monitor.js"
​lineNumber: 70
​message: ""
​name: "NS_ERROR_STORAGE_CONSTRAINT"
​result: 2153971715
​
stack: "@http://dev.<mydomain>.de/wp-content/plugins/query-monitor/assets/query-monitor.js:70:28\ne@http://dev.<mydomain>.de/wp-includes/js/jquery/jquery.min.js:2:30038\nDeferred/then/l/</t<@http://dev.<mydomain>.de/wp-includes/js/jquery/jquery.min.js:2:30340\n"

Any idea?

**Comment by johnbillion** [comment]
This means there's an issue with client side storage in your browser, your best bet is to clear the cache and cookies for the dev site and try again. I don't think this is anything specific to QM.

**Comment by testtomat** [comment]
Yes, that's right. It works in Chrome, but not in Firefox on this machine, even not with clearing cache and all cookies. Thank you.
