### ISSUE TITLE
Oxygen Builder Automatic TOC

### ISSUE THREAD

**Issue by fily1212** [johnbillion/query-monitor#678]
Hi, 
I use Oxygen Builder and all the h2 and h3 are captured when it comes to generate an automatic Table of content. 
The way to prevent this, is to add an attribute "toc-skip" to the root of the DOM of query monitor. Where I should add this attribute in your code? 
Thank you 
Phil

**Comment by johnbillion** [comment]
Unfortunately there are no actions or filters in Query Monitor which allow for this. I recommend that you try to narrow the target element that contains headings you want to list, instead of using all heading elements on the page.
