### ISSUE TITLE
QM error from JS: QM output does not exist

### ISSUE THREAD

**Issue by elearningplugins** [johnbillion/query-monitor#679]
I have a plugin that loads a file uploader via a modal that looks like this URL:

wp-admin/media-upload.php?type=articulate-upload&tab=articulate-upload&npage=1

![image](https://user-images.githubusercontent.com/19674404/177419592-7bab5c00-159d-45af-825a-72a59ddbceb3.png)

Any idea on how to get the Query Monitor to also load so that I can monitor some queries there?

My plugin:

https://wordpress.org/plugins/insert-or-embed-articulate-content-into-wordpress/

**Comment by johnbillion** [comment]
Wow that's a really old-school uploader! Unfortunately I don't think it's a good use of my time to investigate this because it's such a rarely used UI, but I'm always open to a pull request if you're able to figure it out yourself. Cheers.
