### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Nex4rius** [johnbillion/query-monitor#680]
If I enable the plugin I get all functions it's pretty cool BUT each and every single searchbox in the admin area returns "502 Bad Gateway". This bug makes it sadly unusable.

### WordPress Environment ###

WordPress address (URL): https://www.naturkraft-express.de
Site address (URL): https://www.naturkraft-express.de
WC Version: 6.6.1
REST API Version: ✔ 6.6.1
WC Blocks Version: ✔ 7.6.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 8.1.7
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.6.1
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 741.18MB
Datenbank-Datengröße: 650.89MB
Datenbank-Indexgröße: 90.29MB
wp_woocommerce_sessions: Daten: 2.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 11.52MB + Index: 13.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 1.06MB + Index: 0.59MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.39MB + Index: 0.31MB + Engine InnoDB
wp_aiowps_debug_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 3.52MB + Index: 3.27MB + Engine InnoDB
wp_dpd_orders: Daten: 524.52MB + Index: 0.13MB + Engine InnoDB
wp_einkauf_bestellungen: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_einkauf_firmen: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Daten: 0.11MB + Index: 0.08MB + Engine InnoDB
wp_ewwwio_queue: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Daten: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 2.06MB + Index: 0.34MB + Engine InnoDB
wp_postmeta: Daten: 4.56MB + Index: 2.11MB + Engine InnoDB
wp_posts: Daten: 5.50MB + Index: 0.86MB + Engine InnoDB
wp_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Daten: 1.52MB + Index: 5.14MB + Engine InnoDB
wp_statistics_search: Daten: 1.52MB + Index: 1.13MB + Engine InnoDB
wp_statistics_useronline: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Daten: 16.55MB + Index: 22.66MB + Engine InnoDB
wp_statistics_visitor_relationships: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 3.48MB + Index: 3.89MB + Engine InnoDB
wp_users: Daten: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_wcdpi_page_format: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_product_additional: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_product_basic: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_product_sales: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_shipment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_shipment_attachment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcdpi_shipment_item: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Daten: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_packing_slip_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.28MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.45MB + Index: 0.41MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 4.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 1.52MB + Index: 0.84MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woo_shippment_provider: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wpam_actions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_creatives: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_events: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_impressions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_paypal_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens_purchase_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_transactions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_affiliates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_clicks: Daten: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_commissions: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_commission_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_payments: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_payment_commission: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcaf_payment_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Daten: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 179
elementor_font: 1
elementor_library: 9
nav_menu_item: 9
oembed_cache: 31
page: 15
post: 5
product: 54
product_variation: 2
revision: 784
shop_coupon: 73
shop_order: 48
shop_order_refund: 39
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Admin Menu Restriction: von Bilal TAS – 1.0.4
All In One WP Security: von All In One WP Security & Firewall Team – 4.4.12
BackWPup: von Inpsyde GmbH – 3.10.0
Check Port: von Anton Tananaev – 1.1
Creative Mail by Constant Contact: von Constant Contact – 1.5.3
Custom Order Numbers for WooCommerce: von Tyche Softwares – 1.3.5
DHL Shipping Germany for WooCommerce: von DHL – 2.9.1
DPD Versandetikett Plugin WooCommerce: von eMoose GmbH – 3.8.1
Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.5
Easy WP SMTP: von wpecommerce
alexanderfoxc – 1.4.7

Elementor Pro: von Elementor.com – 3.6.5
Elementor: von Elementor.com – 3.6.5
Enable Media Replace: von ShortPixel – 3.6.3
Error Log Monitor: von Janis Elsts – 1.7.2
EWWW Image Optimizer: von Exactly WWW – 6.6.0
Jetpack: von Automattic – 11.1.1
Menu Creator: von Nexarius – 1.4.2
Naturkraft-Express: von Philipp Orak – 1.1
Options View: von Katsushi Kawamori – 2.09
Profit Calculator für Naturkraft-Express: von Philipp Orak – 2.0.0
Rollback Update Failure: von Andy Fragen
Ari Stathopolous
Colin Stewart
Paul Biron – 3.1.0

User Role Editor: von Vladimir Garagulya – 4.63
WC Variations Radio Buttons: von 8manos – 2.0.5
WPC Product Bundles for WooCommerce: von WPClever – 6.3.4
Country Based Restrictions for WooCommerce: von zorem – 3.2
WooCommerce Stripe-Gateway: von WooCommerce – 6.4.3
Germanized für WooCommerce: von vendidero – 3.9.8
WooCommerce PDF Invoices & Packing Slips: von WP Overnight – 3.0.0
WooCommerce Shipping & Tax: von WooCommerce – 1.26.2
WooCommerce: von Automattic – 6.6.1
Yoast SEO: von Team Yoast – 19.2
WP Crontrol: von John Blackbourn & Mitwirkende – 1.14.0
WP Maintenance Mode & Coming Soon: von Themeisle – 2.4.5
WP Statistics: von VeronaLabs – 13.2.4.1

### Inactive Plugins (6) ###

Crypto Payment Gateway for WooCommerce: von TripleA Team – 1.8.1
Query Monitor: von John Blackbourn – 3.9.0
W3 Total Cache: von BoldGrid – 2.2.3
Woocommerce Bulk Price Update: von TechnoCrackers – 2.2.1
Woo Discount Rules: von Flycart – 2.4.3
WP Debugging: von Andy Fragen – 2.11.13

### Must Use Plugins (1) ###

Elementor Safe Mode: von Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop-Basis: #2073 - /shop/
Warenkorb: #9 - /warenkorb/
Kasse: #10 - /kasse/
Mein Konto: #11 - /mein-konto/
Allgemeine Geschäftsbedingungen: #13 - /agb/

### Theme ###

Name: Twenty Twenty
Version: 2.0
Author URL: https://de.wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-07-12 13:36:30 +02:00
Options: ✔
Notes: 47
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 1.581
Oldest: 2022-06-11 03:22:49 +0200
Newest: 2022-07-12 00:29:39 +0200

Ausstehend: 5
Oldest: 2022-07-12 03:57:02 +0200
Newest: 2022-07-12 20:12:01 +0200

### Status report information ###

Generated at: 2022-07-12 00:32:53 +02:00
`

**Comment by johnbillion** [comment]
Unfortunately this could really be caused by anything. You'll need to take a look through your server error logs to try to identify problems such as fatal errors, out of memory issues, etc.

**Comment by Nex4rius** [comment]
> Unfortunately this could really be caused by anything. You'll need to take a look through your server error logs to try to identify problems such as fatal errors, out of memory issues, etc.

Yeah I know but coincidentally it ***only*** happens when this plugin is enabled . . .
