### ISSUE TITLE
Maximum execution time of 300 seconds exceeded

### ISSUE THREAD

**Issue by helgatheviking** [johnbillion/query-monitor#681]
I am diagnosing a clients website and every day the WooCommerce > Status > Logs is logging the following critical error:

>2022-07-13T09:16:16+00:00 CRITICAL Maximum execution time of 300 seconds exceeded i /var/www/mywebsite.com/public_html/wp-content/plugins/query-monitor/classes/Backtrace.php på linje 357

They have version 3.9.0 installed. Is there a way to debug what is causing that likely infinite loop?

**Comment by johnbillion** [comment]
The only advice I can give you here is to try Xdebug which will give you a more complete stack trace in your error logs, which you can use to work your way back to the problematic code. If PHP runs out of memory or execution time there's not much that an application-level tool such as Query Monitor can help with :(

Good luck!
