### ISSUE TITLE
[Enhancement] QM_SHOW_ALL_HOOKS

### ISSUE THREAD

**Issue by erikdemarco** [johnbillion/query-monitor#682]
When 'QM_SHOW_ALL_HOOKS' enabled. There should be a column showing wheter its an 'action' or 'filter' so we can easily differentiate it.

**Comment by johnbillion** [comment]
Thanks for the report, you're absolutely right.

**Comment by crstauf** [comment]
@johnbillion Why limit new column to display only if `QM_SHOW_ALL_HOOKS` is truthy?
