### ISSUE TITLE
Negative memory reported in profiling

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#683]
Added QM's profiling to rendering of a features comparison table, and received some negative values for memory, which I think is probably not correct?

<img width="1203" alt="2022-07-15T191334" src="https://user-images.githubusercontent.com/4573033/179295497-b213642e-5d3f-4302-a00f-c12dddb9159c.png">

**Comment by johnbillion** [comment]
These numbers are an approximation because there's so many factors that can cause the memory to vary, but it could be correct that the memory usage reduces to below its value before the loop or iteration started.

**Comment by johnbillion** [comment]
I'll close this off but do let me know if you think there's a problem or way to improve the memory usage calculation.

**Comment by crstauf** [comment]
🤷‍♂️ 🍻
