### ISSUE TITLE
Should & be &&?

### ISSUE THREAD

**Issue by afragen** [johnbillion/query-monitor#688]
In `shutdown_handler()` is  this `&` a pass by reference or and AND `&&`?
https://github.com/johnbillion/query-monitor/blob/c86893eb3c8456ad3f9ffc692a1ee983119efa20/collectors/php_errors.php#L287

**Comment by simonhammes** [comment]
Neither, this is a bitwise and operation (see https://www.php.net/manual/en/language.operators.bitwise.php).

**Comment by afragen** [comment]
Thanks, I learned something new 🙂
