### ISSUE TITLE
A virus that uses query monitor to infiltrate

### ISSUE THREAD

**Issue by seramo** [johnbillion/query-monitor#692]
Hi @johnbillion

This virus uses query monitor to infiltrate the website

Adds the following files :

**/wp-content/plugins/query-monitor/output/raw/timing-CBdmoD.php**

**/wp-admin/user/options-CBdmoD.php**

[CBdmoD.zip](https://github.com/johnbillion/query-monitor/files/9542047/CBdmoD.zip)

**Comment by johnbillion** [comment]
Thanks for the report @seramo . It's unlikely this is specific to QM and is most likely that your site got hacked and this code got added as a backdoor.

I recommend scanning your site with a service such as Wordfence to ensure there's no more instances of this elsewhere on your site.

Let me know how it goes and feel free to reopen this is you do think it's something specific to QM.
