### ISSUE TITLE
Query monitor throws warnings when using Tribe's The Events Calendar

### ISSUE THREAD

**Issue by cantonbecker** [johnbillion/query-monitor#697]
When Query monitor is activated, certain pages rendered by The Events Calendar (Tribe) throw this warning. Only happens for non-logged in visitors to the website:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Tribe__Events__Query' does not have a method 'pre_get_posts' in /home/upayaorg/2022.upaya.org/wp-includes/class-wp-hook.php on line 307

Warning goes away when I deactivate Query Monitor.

**Comment by johnbillion** [comment]
You'd best report this to the authors of The Events Calendar. The error is correct, that method does not exist.
