### ISSUE TITLE
Optimize Production Composer Build to reduce needless file lookups

### ISSUE THREAD

**Issue by andyblackwell** [johnbillion/query-monitor#707]
I recently did an optimization pass on our sites, and after profiling them found that several plugins with local composer /vendor builds were not fully optimized for production, Query Monitor being in this list.

The plugin's local composer build is not built with `--optimize-autoloader` or `--classmap-authoritative`, and by default the composer ClassLoader will prepend itself to the list of autoloaders. Both of these issues combined can cause thousands of needless file lookups for classes flowing through this loader that it doesn't need to handle. When not built with `--classmap-authoritative` and a class isn't found in the local classmap, then composer makes a few fallback attempts to find the class, resulting in all the needless file lookups.

Looking at your build, would propose adding these flags to your `composer dump-autoload` and `composer install` commands when building for production.
so adding either of these flag combos:  `-oa` or `--optimize-autoloader --classmap-authoritative`

and potentially also adding `prepend-autoloader: false` to the composer.json config, so this autoloader doesn't prepend itself ahead of other more site specific autoloaders:
```
"config": {
    "prepend-autoloader": false
}
```

**Comment by johnbillion** [comment]
Thanks @andyblackwell , much appreciated. I'll take a look at the config ready for the next release.

Out of interest what tools did you use for this profiling?

**Comment by andyblackwell** [comment]
used [blackfire.io](https://www.blackfire.io/), but that's a paid product so prob not helpful

**Comment by johnbillion** [comment]
Thanks again for the pointers. This has been implemented in 32d826b and will be released in the next version. I didn't implement `optimize-autoloader` because QM only uses a class map and there's no optimisation to be done.

**Comment by johnbillion** [comment]
https://github.com/johnbillion/wp-crontrol/issues/91
