### ISSUE TITLE
Conflict with Gravity Forms v2.7

### ISSUE THREAD

**Issue by GerardEarley** [johnbillion/query-monitor#721]
There seems to be a fairly significant conflict between Query Monitor v3.11.1 and Gravity Forms V2.7 when viewing Gravity Forms system information pages.

**Comment by johnbillion** [comment]
There are many plugins that conflict with Gravity Forms because it un-enqueues JavaScript files from other plugins on its administration screens. There should be plenty of information about this on the GF forums or in their documentation.
