### ISSUE TITLE
calling user whoami is launching some antivirus flag as malware query monitor

### ISSUE THREAD

**Issue by rdesanctis** [johnbillion/query-monitor#722]
In environment.php 
the next  lines are launching a malware flag on each page reload with BitDefender Antivirus

if ( empty( $php_u ) && function_exists( 'exec' ) ) {
			$php_u = exec( 'whoami' ); // phpcs:ignore
		}

as a workaround I commented those lines and the malware flag dissapears, but on any future query-moinitor update will back again.

**Comment by johnbillion** [comment]
Answered here: https://wordpress.org/support/topic/bitdefender-warning-on-local-xamp-instalation/
