### ISSUE TITLE
Plugin Inserting <H1>Query Monitor</H1> tag across all pages

### ISSUE THREAD

**Issue by loganjessem** [johnbillion/query-monitor#725]
This plugin is helpful, but it's inserting an `<H1>` tag across all pages and I'm not sure how to get rid of it. 
the site is: frontporchmusic.ca 

![image](https://user-images.githubusercontent.com/124809610/217604077-32fb9eb7-170c-443c-ba4d-49b73bd9ef56.png)

Any advice on how to remove this tag?

**Comment by johnbillion** [comment]
Does this happen if you run the same test while you're not logged in. Query Monitor only outputs something when you're logged in as an Administrator.

**Comment by loganjessem** [comment]
Ohhhh gotcha. Yes, when I'm not logged in the <H1> tag is gone. This is a
silly question, but will Google/other crawlers see this heading when
scraping the site?

thank you for the quick reply

**Comment by johnbillion** [comment]
Nope, as this output only happens when you're logged in as an Administrator, Google won't see any of it. You're all good!
