### ISSUE TITLE
Misleading redirect shown for HTTP API request

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/query-monitor#738]
An HTTP API request to the Gravity Forms API with a trailing question mark gets marked as having been redirected on the receiving end because the trailing question mark is stripped somewhere. Need to investigate why this is flagged as a redirect.

<img width="875" alt="" src="https://user-images.githubusercontent.com/208434/222094331-566561ce-10b2-4a50-99c7-eba74ac9f7cd.png">

**Comment by crstauf** [comment]
It would technically be a redirect, would it not?

**Comment by crstauf** [comment]
![Image](https://github.com/johnbillion/query-monitor/assets/4573033/875dc2b3-839e-4742-9c80-a3d7e6d23b99)

**Comment by crstauf** [comment]
@johnbillion Fixed identifying it as a redirect in #790. Would you also want the `?` removed if the query string is empty?
