### ISSUE TITLE
The method wp_resolve_block_template results in more database queries

### ISSUE THREAD

**Issue by spacedmonkey** [johnbillion/query-monitor#763]
The method  [wp_resolve_block_template](https://github.com/johnbillion/query-monitor/blob/e6fbe9579059e53d6f7b093050b26271cf303809/collectors/theme.php#L570), results in database queries that are reported, even on theme that do not support block templates. 

<img width="1064" alt="Screenshot 2023-05-05 at 11 18 38" src="https://user-images.githubusercontent.com/237508/236432897-a0920491-2cbe-4a6d-ba1b-ef23f0ff47da.png">

Something like this might fix the issue. 

```
protected static function wp_resolve_block_template( $template_type, $template_hierarchy, $fallback_template ) {
		if ( ! function_exists( 'resolve_block_template' ) ) {
			return null;
		}

                if ( ! current_theme_supports( 'block-templates' ) ) {
		    return null;
	        }

		return resolve_block_template( $template_type, $template_hierarchy, $fallback_template );
	}
```

**Comment by johnbillion** [comment]
Looks like `current_theme_supports( 'block-templates' )` is indeed what we want, thanks. Fixed in 6b678fd.
