### ISSUE TITLE
Symlink'd wp-contents folder gives no results

### ISSUE THREAD

**Issue by afragen** [johnbillion/query-monitor#77]
As of WP 3.9 a symlink can be used for wp-content or for plugins/themes. I've done this in a local environment and QM now only lists all queries as coming from Core and not from the symlink'd plugins.

**Comment by afragen** [comment]
This only seems to be an issue with multisite.

**Comment by johnbillion** [comment]
I'm going to close this off as this is nightmarish road that I don't want to go down.
