### ISSUE TITLE
`QueryMonitor::init()` creating several new instances

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#774]
Noticed that QM appears to create multiple instances of itself within one page load. To test this, I adjusted `QueryMonitor::init()` to be like such:

```php
public static function init( $file = null ) {

	static $instance = null;

	if ( ! $instance ) {
error_log( print_r( debug_backtrace(), true ) );
		$instance = new QueryMonitor( $file );
	}

	return $instance;

}
```

Changing the conditional to explicitly check for `null` doesn't change the outcome.

**Comment by johnbillion** [comment]
Thanks for the report. I'm only seeing once instance created during my testing. Could it be that the page you're loading is firing Ajax requests (to the REST API, admin-ajax.php, etc)? If so, these will be logged at around the same time.

Using `error_log( $_SERVER['REQUEST_URI'] );` will log the path of the page that loads.

**Comment by crstauf** [comment]
You are correct; here's the error log with the request URI:

```
[20-Jun-2023 15:16:42 UTC] /wp-admin/index.php
[20-Jun-2023 15:16:43 UTC] /wp-admin/admin-ajax.php
[20-Jun-2023 15:16:43 UTC] /favicon.ico
```

Turns out what I was seeing is `shutdown` action runs on every request (AJAX, REST), which I was not aware of. I'll try adding [the conditional checks that the `Html` dispatcher does](https://github.com/johnbillion/query-monitor/blob/develop/dispatchers/Html.php#L875), and see if that solves my problem.

**Comment by crstauf** [comment]
Yep, the following prints paths to QM stylesheet only once:

```php
<?php

add_action( 'shutdown', static function () {
	if ( ! QM_Dispatcher_Html::user_can_view() ) {
		return;
	}

	if ( ! QM_Dispatcher_Html::request_supported() ) {
		return;
	}

	if ( is_admin() ) {
		if ( ! did_action( 'admin_init' ) ) {
			return;
		}
	} else {
		if ( ! ( did_action( 'wp' ) || did_action( 'login_init' ) || did_action( 'gp_head' ) ) ) {
			return;
		}
	}

	/** Back-compat filter. Please use `qm/dispatch/html` instead */
	if ( ! apply_filters( 'qm/process', true, is_admin_bar_showing() ) ) {
		return;
	}

	if ( ! did_action( 'wp_footer' ) && ! did_action( 'admin_footer' ) && ! did_action( 'login_footer' ) && ! did_action( 'gp_footer' ) ) {
		return;
	}

	$qm = QueryMonitor::init()->plugin_path( 'assets/query-monitor.css' );

	if ( ! file_exists( $qm ) ) {
		return;
	}

	error_log( $qm );
} );
```

`debug.log`
```
[20-Jun-2023 15:30:56 UTC] /wp-admin/admin-ajax.php
[20-Jun-2023 15:30:57 UTC] /wp-admin/index.php
[20-Jun-2023 15:30:57 UTC] /Volumes/CSSLLC/qm-instance/app/public/wp-content/plugins/query-monitor/assets/query-monitor.css
[20-Jun-2023 15:30:57 UTC] /wp-admin/admin-ajax.php
[20-Jun-2023 15:30:57 UTC] /favicon.ico
```

Sorry to have jumped the gun. 😞
