### ISSUE TITLE
Backtrace(?) error when running AJAX stops AJAX

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#78]
this appears to be a Backtrace error, but I could be wrong... perhaps checking DOING_AJAX might help prevent output, thus keeping the AJAX script working?

![screen shot 2014-09-23 at 1 33 07 pm](https://cloud.githubusercontent.com/assets/4573033/4376893/a8e9029e-4349-11e4-9604-fa182580eeb7.png)

**Comment by ashfame** [comment]
I run into this same issue from time to time, would be great to have this fix :)

**Comment by johnbillion** [comment]
Fixed in d587d7e373ca2fe3195942d83c545ea414a19223 and 53d3bd030782d7a23537791ccfed011dc34910d2
