### ISSUE TITLE
Buggy behavior during update process

### ISSUE THREAD

**Issue by stefanos82** [johnbillion/query-monitor#785]
![image](https://github.com/johnbillion/query-monitor/assets/1777466/62ce049a-474d-4482-9099-141432d8addd)

After I hit refresh on my browser, it behaves as expected.

@johnbillion how can I check whether a file in plugin has been corrupted or got partially configured?

Please advice.

Thank you :+1:

**Comment by johnbillion** [comment]
You might want to delete Query Monitor and install it again, just to be sure. Not sure what could have caused that error message though, it shouldn't be formatted like that.

I'll close this off as I don't think it's anything specific to QM. Hopefully it doesn't happen again!

**Comment by stefanos82** [comment]
It has happened to 4 different websites I have locally that I work on and it's the first time this behavior takes place.

**Comment by mrdarrengriffin** [comment]
Hi @johnbillion, I just wanted to raise that this is happening for us on multiple environments across different sites. One scenario I had just now was that it was 500'ing for the entire site. I had to rename the "query-monitor" plugin directory to disable. Reinstalling it may fix the issue but I can only presume that the update introduces a bug that a fresh install does not. Are you able to investigate?

If I find time, I'll do some digging!

**Comment by mrdarrengriffin** [comment]
@johnbillion - I think it's due the `maybe_prevent_error` function being called too early as it's failing to execute `wp_get_current_user()`
https://github.com/johnbillion/query-monitor/blob/5281b10a8ad87d37cff1d0e9304c17f9b52b145f/collectors/doing_it_wrong.php#L73

**Comment by johnbillion** [comment]
This appears to be caused by the new "Doing it Wrong" collector trying to collect information about an error that's occurring very early on during the loading process of your site. I'll get a fix out for this shortly.

**Comment by stefanos82** [comment]
Problematic behavior has been remedied. Closing the ticket, thank you @johnbillion
