### ISSUE TITLE
PHP warning on http collector (Undefined array key "url")

### ISSUE THREAD

**Issue by pierre-dargham** [johnbillion/query-monitor#788]
Hello John,

The HTTP collector seems to produces a PHP warning when Curl is disabled

Steps to reproduce :

- When running on WordPress 6.2.2
- And query-monitor 3.13.0
- And Curl not installed or not enabled (or commented here: https://github.com/WordPress/WordPress/blob/6.2.2/wp-includes/Requests/src/Requests.php#L142)
- Then Following code :

```
add_action('init', function() {
	wp_remote_get("https://example.com");
});
```
causes following error :

```
Warning	Undefined array key "url"	
wp-content/plugins/query-monitor/collectors/http.php:363
```

It may be related to the recent upgrade of **WpOrg\Requests** http client in core, but I've not tested with older versions.

It seems that **WpOrg\Requests** HTTP transport class fallbacks on **Fsockopen** when Curl is not available, and its response is not the same as Curl's one, and does not contains an "url" entry

**Comment by crstauf** [comment]
@pierre-dargham Provided #789 as fix; will you please confirm?

**Comment by pierre-dargham** [comment]
Hello @crstauf ,

Thanks :+1: 


I confirm https://github.com/johnbillion/query-monitor/pull/789 fixes the PHP warning

However, please note that when **WP_Http** handles a 3xx redirection, QM won't detect it and show it when using Fsockopen transport class. It could be nice to find another way to catch this behavior, and provide same details than when using Curl transport class, if possible. Could be in a future release though, removing the warning seems to be more urgent.

Bests regards,
Pierre

**Comment by crstauf** [comment]
Unfortunately the response does not include a URL, which means the final URL will need to be pulled from elsewhere.

**Comment by crstauf** [comment]
@pierre-dargham This [answer on StackOverflow](https://stackoverflow.com/a/23504786/5490855) indicates that fsockopen doesn't follow redirects. 🤷‍♂️ 

> fsockopen doesn't do redirects. You are confused with fopen that does follow redirects in its quest to fetch the resource, when used with the [http-wrapper](http://nl1.php.net/manual/en/wrappers.http.php), and gives you a (read-only) handler to the body of the resource. When used with the [http-wrapper](http://nl1.php.net/manual/en/wrappers.http.php), the headers encountered on the way are stored in the variable $http_response_header, which can be processed to see the final URL.
>
> fsockopen however just opens a stream to a socket, and therefore does not follow redirects. fsockopen isn't even HTTP aware. It just opens a TCP socket for reading from and writing to.

**Comment by johnbillion** [comment]
Thanks folks, this has been fixed in the latest release.
