### ISSUE TITLE
Add settings page to choose roles

### ISSUE THREAD

**Issue by adisos** [johnbillion/query-monitor#79]
It's awesome plugin! Clean readable code, it's first plugin on WP I saw which code is not terrible ))

Now for test purposes I need to show QM for subscribers. 

It'd be good if your add ability to choose role to whom show QM.

**Comment by johnbillion** [comment]
I'm going to close this ticket as it's not something I plan to add.

You can get Query Monitor to show its output when you're logged in as a different user by using [the Authentication panel at the bottom of its output](https://github.com/johnbillion/query-monitor#authentication).
