### ISSUE TITLE
Identify drop-ins as components

### ISSUE THREAD

**Issue by crstauf** [johnbillion/query-monitor#814]
Is it possible to identify drop-ins (ex: `object-cache.php`) as a component? My host's object cache drop-in has a deprecated warning, and I'm trying to silence it.

**Comment by crstauf** [comment]
Oh, I guess I could set component as `other` and then `wp-content/object-cache.php` as the name. Trying that now.

**Comment by crstauf** [comment]
Yep, that appears to have worked. Would be nice to have drop-ins identified as components still.

**Comment by johnbillion** [comment]
Yeah that should be possible.

**Comment by johnbillion** [comment]
Drop-ins have to live at `WP_CONTENT_DIR/{name}.php` so the path is known.

**Comment by crstauf** [comment]
Hmm, `QM_Util` defines files in `WP_CONTENT_DIR` as `other`. Is changing `other` to `drop-in` all that needs to be done, or some more specific qualifier?

https://github.com/johnbillion/query-monitor/blob/6ca0585108306473bad233f87c570e65a11ceb6f/classes/Util.php#L137

**Comment by johnbillion** [comment]
Good question. A file in the root of that directory is likely to be a drop-in, but not certain. QM could probably use `_get_dropins()` (or a copy of its file list) to be sure.
