### ISSUE TITLE
Fluent query logger - error something is wrong!

### ISSUE THREAD

**Issue by Powsey** [johnbillion/query-monitor#822]
Hello, whenever I try to use the fluent query logger plugin, I get the issue "error something is wrong!"
I have set up the logs for specific plugin logs to retrieve but it does not work at all.

Thank you for your help

**Comment by johnbillion** [comment]
Are you sure you have the right plugin repo? This is the repo for Query Monitor, not Fluent Query Logger.

**Comment by Powsey** [comment]
Well this module (Fluent) is mentioned on this repo’s welcome page + I couldn’t find a dedicated repo for it.

**Comment by johnbillion** [comment]
This is the repo you want: https://github.com/WPManageNinja/fluent-query-logger/ . Best of luck!
