### ISSUE TITLE
Feature Request: Click to Copy for log messages

### ISSUE THREAD

**Issue by MadtownLems** [johnbillion/query-monitor#834]
I often use the logging feature to inspect various things. But when things get really large, it's very annoying to copy and paste them out into an IDE or Google Doc.  (For reference, block_editor_settings_all is clocking in at 2555 lines for us at the moment.)

I'd love an easier way to copy/paste values out of here. Perhaps log messages have a small "click to copy" icon? I could also see conditionally adding it if the log message goes beyond a certain size or number of lines.

Cheers

**Comment by crstauf** [comment]
@johnbillion What do you think about setting `user-select: all;` on cells in Logs table?

**Comment by johnbillion** [comment]
I'd be in favour of a "copy" button in a few places. `user-select: all` might get annoying if you do only want to select a portion.

**Comment by crstauf** [comment]
But you could copy the whole thing into a text editor and easily extract the portion you want.
