### ISSUE TITLE
Link under Profile and Timings 404s

### ISSUE THREAD

**Issue by mikezielonka** [johnbillion/query-monitor#842]
![Screenshot by Dropbox Capture](https://github.com/johnbillion/query-monitor/assets/1565502/d0c562d6-ac74-4b08-819f-96b0303e35ef)

404 link is https://querymonitor.com/blog/2018/07/profiling-and-logging/

**Comment by johnbillion** [comment]
Thanks, I think the redirects that were in place have gone missing.

The new URL is https://querymonitor.com/wordpress-debugging/profiling-and-logging/

**Comment by mikezielonka** [comment]
I know a good redirection plugin if u need one 😉

**Comment by crstauf** [comment]
Note: the output files already have the correct URLs.

**Comment by johnbillion** [comment]
This has been fixed.
