### ISSUE TITLE
AJAX errors in console regarding null post

### ISSUE THREAD

**Issue by Utsav-Ladani** [johnbillion/query-monitor#843]
## Description
- I noticed a console error when an AJAX request was sent by the `Query Monitor` on the settings page '/wp-content.themes.php`
- Here is a screenshot:
	<img width="952" alt="Screenshot 2023-12-21 at 11 38 18 AM" src="https://github.com/johnbillion/query-monitor/assets/55320836/3926ac54-4dcc-46d0-92b7-83f4da09d14c">

## Why?
- The line mentioned in error is: https://github.com/johnbillion/query-monitor/blob/0741b15ea0bc05dc9b6fd71af246cf83cbc45f33/collectors/block_editor.php#L138-L141
- Post is `null`, so no `post_content` such property exists.

## Solution
- Add a check to verify that the post is not null
```php
} elseif ( is_singular() ) {
	// Post editor:
	$post =  get_post( get_queried_object_id() );

	if ( !$post ) {
		return;
	}

	$content = $post->post_content;
} else {
```

**Comment by johnbillion** [comment]
Thanks for the report. If `is_singular()` is true but `get_post()` returns null then something is going wrong on your site. Do you know what the ajax request is doing where that error was triggered?

**Comment by Utsav-Ladani** [comment]
Thanks @johnbillion for quick response. It was due to another plugin (BuddyPress).
