### ISSUE TITLE
WordPress 6.5: Support new `load_translation_file` filter

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/query-monitor#849]
WordPress 6.5 is adding support for PHP translation files. They are preferred over MO files.

A new `load_translation_file` filter can be used to get the file location. The filter works for both MO and PHP files.

A dev note will be published during the 6.5 beta period.

**Comment by dd32** [comment]
Just noting, that the current behaviour is that QM displays the `.mo` as being loaded, even though the `.php` is loaded instead.

**Comment by johnbillion** [comment]
Thanks, I'll take a look.

Dev note: https://make.wordpress.org/core/2024/02/27/i18n-improvements-6-5-performant-translations/
