### ISSUE TITLE
403 Forbidden on self GET wp-admin

### ISSUE THREAD

**Issue by thefrosty** [johnbillion/query-monitor#850]
I've been seeing this 403 Forbidden error in my HTTP API Calls for quite some time, and am looking into it.

It's a URL in which can be hit on any WordPress install with the standard DB Update screen (if they aren't blocking such a request). So internally I would expect no such error.

I can hit the `/wp-admin/upgrade.php?step=1` on my site in a private non-logged in window, so just trying to understand what else I might be missing.

Current server stats:
* PHP: 8.2.15 (was happening on 8.0 too)
* Apache 2.4.58 (behind nginx reverse Proxy)
* Multisite/multinetwork.
* 

<img width="1466" alt="Plugins_‹_Austin_Passy_—_WordPress" src="https://github.com/johnbillion/query-monitor/assets/367897/0c52ea01-342c-4f40-92a7-22a54113b02e">

**Comment by johnbillion** [comment]
That's the standard mechanism that WordPress multisite uses to perform updates on sites within the network. I've no idea why it could return a 403.

This isn't triggered by Query Monitor, despite what the "Component" column says. Sometimes QM will blame itself if it's not sure what triggered the request or if your site uses a non-standard directory structure.

**Comment by thefrosty** [comment]
Thanks, I'll continue my investigation elsewhere.
