### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by TheOldMan2000** [johnbillion/query-monitor#851]
Hi,

Just installed v3.15.0 of your Query Monitor plugin and found there are a few broken links:

Settings -> Logs
Read about logging variables in Query Monitor
https://querymonitor.com/docs/logging-variables/

Settings -> Timings
Read about timing and profiling in Query Monitor 
https://querymonitor.com/blog/2018/07/profiling-and-logging/

**Comment by johnbillion** [comment]
Thanks! These have already been fixed but I haven't released the fixed version yet and the redirects aren't working. Both those URLs should now point to https://querymonitor.com/wordpress-debugging/profiling-and-logging/ .

**Comment by TheOldMan2000** [comment]
Awesome thank you!

**Comment by crstauf** [comment]
Duplicate of #842.
