### ISSUE TITLE
Interference with W3 Total Cache due to "db.php"

### ISSUE THREAD

**Issue by SemoTech** [johnbillion/query-monitor#852]
Hello,

Seems Query-Monitor (latest v3.15.0) creates a file called **db.php** located at:
..._/public_html/wp-content/db.php_
which is actually a simlink to:
..._/public_html/wp-content/plugins/query-monitor/wp-content/db.php_

Now, W3 Total Cache puts up an error about "FTP credentials don't allow to copy to file .../public_html/wp-content/db.php"
It is trying to issue this command which fails since the target file is a symlink:
_cp /public_html/wp-content/plugins/w3-total-cache/wp-content/db.php /public_html/wp-content/db.php_

**Is there any way for Query-Monitor to rename/use a different name, like "QMDB.php", as not to interfere with W3 Total Cache?**

Thank you.

**Comment by johnbillion** [comment]
Unfortunately this is a limitation of WordPress itself. See https://querymonitor.com/help/db-php-symlink/#when-an-existing-db-php-file-is-already-in-place for a little more info.

**Comment by SemoTech** [comment]
Thanks @johnbillion. In my case this actually turned out to be a legacy symlink from InterWorx.  Deleting it fixed the issue with W3 Total Cache!
