### ISSUE TITLE
vulnerability management

### ISSUE THREAD

**Issue by norsedevops** [johnbillion/query-monitor#857]
Hi guys.

It seem like query monitor does not have cve attached. 
And your plugin is not  referenced in the [NATIONAL VULNERABILITY DATABASE](https://nvd.nist.gov/)
How will you manage with vulnerabilities, once you'll have some issues ?

Thank's in advance for your answer.

Stéphane

**Comment by johnbillion** [comment]
https://github.com/johnbillion/query-monitor/security
