### ISSUE TITLE
TwentyFifteen's Left Sidebar Overwrites the Debug Info

### ISSUE THREAD

**Issue by julien731** [johnbillion/query-monitor#86]
In TwentyFifteen is it impossible to see the debug information easily (unless you inspect the source) as the theme's sidebar overwrites the table that shows debug info.

![Query Monitor](http://i.imgur.com/8Trmoqo.png)

**Comment by mathetos** [comment]
Would love to see this resolved. Any update?

**Comment by johnbillion** [comment]
Fixed in d315163cebd2c8d716ba63205665dca2d0fb889c

**Comment by julien731** [comment]
Awesome thanks.
