### ISSUE TITLE
3.16 throws critical error

### ISSUE THREAD

**Issue by c0ball** [johnbillion/query-monitor#862]
After updating to version 3.16 my WordPress installation stopped working due to a critical error.
Enabling the debug mode displays the following error mesage:

`Warning: require(/home/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/../symfony/deprecation-contracts/function.php): failed to open stream: No such file or directory in /home/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/autoload_real.php on line 42`

`Fatal error: require(): Failed opening required '/home/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/../symfony/deprecation-contracts/function.php' (include_path='.:/usr/share/php') in /home/www/wordpress/wp-content/plugins/query-monitor/vendor/composer/autoload_real.php on line 42`

I am using WordPress version 6.5.2 and PHP version 7.4.33.

**Comment by johnbillion** [comment]
Thanks for the report. Moving this to #861.
