### ISSUE TITLE
Fatal Error when running alongside RedisCachePro

### ISSUE THREAD

**Issue by seanford** [johnbillion/query-monitor#863]
NOTICE: PHP message: PHP Fatal error: Declaration of RedisCachePro\Extensions\QueryMonitor\ObjectCacheCollector::get_storage() must be compatible with QM_Collector::get_storage(): QM_Data in /var/www/html/public_html/wp-content/mu-plugins/redis-cache-pro/src/Extensions/QueryMonitor/ObjectCacheCollector.php on line 45

Hosted on Cloudways Autonomous.  Updated to WP 6.5.2 and started getting the fatal error.  Had to disable QM to get site back up.

Anyone else have this same issue?

**Comment by johnbillion** [comment]
It sounds like your site is using an older version of Object Cache Pro. You'll need to manually update it if it's a mu-plugin, or contact Cloudways for advice if it's bundled on the platform.

CC @tillkruss

**Comment by tillkruss** [comment]
This does sound a very old version of Object Cache Pro.

**Comment by seanford** [comment]
Thank you.  I'll report to Cloudways as OCP is provided by them and I cannot update it myself.

**Comment by johnbillion** [comment]
Good luck!
