### ISSUE TITLE
Updating Query Monitor output after SSR with AJAX and REST API calls

### ISSUE THREAD

**Issue by chriszarate** [johnbillion/query-monitor#870]
Hi! Great plugin, big fan. I can see via the documentation how Query Monitory can [enhance the response payload of REST API calls](https://querymonitor.com/wordpress-debugging/rest-api-requests/).

Is there a way to modify the output / panels of QM with this data? The use case here is "friendlier" UI-based debugging that does not require using the browser's debug console to inspect HTTP request responses.

**Comment by johnbillion** [comment]
There's no means of doing this currently, but it's in the works. No ETA yet though. See #823.
