### ISSUE TITLE
PHP8.4 alpha 1 warnings - nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by ipajen** [johnbillion/query-monitor#873]
### Environment
- WordPress: 6.6-RC2
- PHP: 8.4.0alpha1
- Server: Apache/2.4.59 (Win64) PHP/8.4.0alpha1 mod_fcgid/2.3.10-dev
- Database: mysqli (Server: 8.3.0 / Client: mysqlnd 8.4.0alpha1)
- Browser: Edge 126.0.0.0 (Windows 10/11)
- Theme: Twenty Twenty-Four 1.1
- MU-Plugins: None activated
- Plugins: 
  * Query Monitor 3.16.3
  * WordPress Beta Tester 3.5.5

Maybe bit early but PHP 8.4 alpha1 has been released 

[PHP 8.4.0alpha1](https://php.watch/versions/8.4/releases/8.4.0alpha1)

PHP 8.4: Implicitly nullable parameter declarations deprecated
[implicitly-marking-parameter-type-nullable-deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

`__construct(): Implicitly marking parameter $trace as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\query-monitor\classes\Backtrace.php on line 136

Deprecated: QM_Collector_HTTP::action_curl_after_request(): Implicitly marking parameter $info as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\query-monitor\collectors\http.php on line 262

Deprecated: QM_Collector_HTTP::action_fsockopen_after_request(): Implicitly marking parameter $info as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\query-monitor\collectors\http.php on line 271

Deprecated: QM_Collector_Logger::store(): Implicitly marking parameter $prefix as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\query-monitor\collectors\logger.php on line 210

Deprecated: QM_Collector_Logger::interpolate(): Implicitly marking parameter $prefix as nullable is deprecated, the explicit nullable type must be used instead in C:\wamp64\www\wp\wp-content\plugins\query-monitor\collectors\logger.php on line 262`

Thank you!

**Comment by johnbillion** [comment]
Thanks! I'll add testing for 8.4 soon.
