### ISSUE TITLE
Can QM intercept var dumps?

### ISSUE THREAD

**Issue by qwertydude** [johnbillion/query-monitor#876]
Is it possible in PHP for QM to be able to intercept var dumps and then display them nicely in its interface?

If not, is there (can you add) a function in QM that is an alternative to var dump that could do this?

Thanks

**Comment by johnbillion** [comment]
Yep! You can log output to the Logs panel for exactly this. Docs here: https://querymonitor.com/wordpress-debugging/profiling-and-logging/
