### ISSUE TITLE
Tool Presentation Fails when viewing Gravity Forms Entries

### ISSUE THREAD

**Issue by ambrosiawt** [johnbillion/query-monitor#881]
When I am viewing the Gravity Forms Entries page for a form, the top bar menu item simply says "Query Monitor" with a submenu that says "Query Monitor" and the all of the content for all of the views of the Query Monitor are displaying stacked on top of one another on the page below the Entries list and without regard for the leftside menu.  Image attached.

This is on WP 6.6.1, Gravity Forms 2.8.15, and Query Monitor 3.16.4.
![Screenshot 2024-08-02 at 15 45 21](https://github.com/user-attachments/assets/b3ff583c-b1b8-4681-be54-38bdeb9bd453)

**Comment by johnbillion** [comment]
You'll need to contact the authors of Gravity Forms for advice on this. See https://wordpress.org/support/topic/conflict-with-gravityforms-3/.
