### ISSUE TITLE
Replace jQuery with Vanilla JavaScript in Plugin

### ISSUE THREAD

**Issue by Hollyw00d** [johnbillion/query-monitor#897]
I love your plugin! However, on my WordPress portfolio site, I disabled jQuery on the front end of most pages and posts. Now, the plugin's panel won't load correctly (which is expected) on some of my pages when jQuery is disabled.

Would you be interested in checking out a PR from me where I replace jQuery with Vanilla JavaScript (JavaScript without frameworks) for your plugin? 

I wanted to ask before I did a bunch of work in creating a PR.

**Comment by johnbillion** [comment]
Thanks for the offer! I've actually already done this in #837 but that's only been merged into a long-running feature branch that's not ready for release yet.

If your site has jQuery disabled then you can define the `QM_NO_JQUERY` constant as true and QM should work without any errors (although with heavily reduced functionality).

**Comment by Hollyw00d** [comment]
@johnbillion 
Thanks for the tip about adding `define('QM_NO_JQUERY', true)` in my __wp-config.php__ file to make the Query Monitor plugin work without jQuery. Also, I'm happy that you plan to eventually replace jQuery with Vanilla JavaScript in your plugin.

I also discovered that when I'm logged into my WP Admin and click on the __Query Monitor__ button in the WP admin bar when the __Query Monitor__ panel opens up at the bottom, I can still score down to see Query Monitor data (see screenshot below):
![query-monitor-screenshot](https://github.com/user-attachments/assets/d7d3559c-425f-4fca-990d-2ff0447570f1)

Hopefully, this info helps someone else!

**Comment by johnbillion** [comment]
Yeah without jQuery it basically stacks all the panels one on top of each other so you can just scroll through. Glad it still works, it doesn't get tested very often! :D

**Comment by Hollyw00d** [comment]
@johnbillion 
I found a workaround (see PHP below, and it's on my live Wordpress site) to run the WP default jquery-core and jquery-migrate when I'm logged into the WP Admin and NOT run those scripts when I'm not on a single post and NOT logged into the WP Admin.

With this code, I can still use all Query Monitor plugin features, as jQuery runs whenever I'm logged into the WP Admin or on an admin page.

Hopefully, this will help someone else.

```
function conditionally_dequeue_jquery() {
    // Check if not a single post AND not logged into WP Admin
    if ( !is_singular( 'post' ) && !is_user_logged_in() && !is_admin() ) {
        // Dequeue jQuery core & migrate
        wp_dequeue_script('jquery-core');
        wp_deregister_script('jquery-core');

        wp_dequeue_script('jquery-migrate');
        wp_deregister_script('jquery-migrate');
    } else {
        // Enqueue jQuery core & migrate
        wp_enqueue_script('jquery-core');
        wp_enqueue_script('jquery-migrate');
    }
}
add_action('wp_enqueue_scripts', 'conditionally_dequeue_jquery');
```
