### ISSUE TITLE
Moveing classes to a subdir

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#90]
I suggest moving these to a subdirectory.

- Backtrace.php    
- Collector.php    
- Dispatcher.php   
- Output.php       
- Plugin.php       
- Timer.php        
- Util.php         

+1 *WP scans all *.php files in the plugin root.*

**Comment by johnbillion** [comment]
Makes sense. Thanks for the suggestion.

**Comment by szepeviktor** [comment]
You could also use PHP class autoloader.
Are all classes always loaded?
