### ISSUE TITLE
formatting for logging?

### ISSUE THREAD

**Issue by columbian-chris** [johnbillion/query-monitor#904]
Are there any formatting options for logging?  The [documentation](https://querymonitor.com/wordpress-debugging/profiling-and-logging/) doesn't mention anything so I wanted to ask.  It would be nice if I could do some simple formatting like make some of the log message bold. 👍

**Comment by johnbillion** [comment]
Nope, sorry! Like with most other logging mechanisms, the logs could be exported elsewhere so they need to remain as close to plain text as possible. In theory markdown could be supported, but I'd rather not complicate things.

**Comment by columbian-chris** [comment]
Alright, thanks for the answer, @johnbillion.

**Comment by columbian-chris** [comment]
I was going to include a screenshot just for fun so I'll throw it in here even though the ticket has closed.

<img width="465" alt="Screenshot 2024-09-26 at 2 30 14 PM" src="https://github.com/user-attachments/assets/ee23cd2a-8bd6-4e0a-8cf3-2b39060ac366">
