### ISSUE TITLE
PHP 8.4 → `E_STRICT` deprecated

### ISSUE THREAD

**Issue by barryhughes** [johnbillion/query-monitor#910]
Hi!

Bit of a supplement to some [earlier PHP 8.4 compat work](https://github.com/johnbillion/query-monitor/pull/880), it seems that under PHP 8.4 RC1 we get a deprecated constant notice [via this line](https://github.com/johnbillion/query-monitor/blob/3.16.4/collectors/environment.php#L64):

| Level | Message | Location |
| --- | --- | --- |
| Deprecated | Constant E_STRICT is deprecated | wp-content/plugins/query-monitor/collectors/environment.php:64 |

Not critical, but it does add some noise.

**Comment by johnbillion** [comment]
Thanks for the report! It's a bit difficult to identify all the deprecated usage in the automated tests because so many of the packages in the dependencies are emitting deprecated errors too.

**Comment by barryhughes** [comment]
(Thanks!)
