### ISSUE TITLE
Database queries panel shows queries from plugin with same prefix

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/query-monitor#917]
I have two plugins on my test site: `web-stories`, and `web-stories-tester`.

When I filter database queries by the `web-stories` component I see all queries by `web-stories-tester` also. I expect to see those only when explicitly filtering by `web-stories-tester` though.

<img width="1728" alt="Screenshot 2024-11-11 at 20 23 14" src="https://github.com/user-attachments/assets/cfd0b844-dd87-4f9c-96b6-beaf6d770ff2">

**Comment by johnbillion** [comment]
Yeah this has been reported before, see:

* #223
* #726

I'm not planning on fixing this because when I eventually manage to ship version 4 of Query Monitor with client-side rendering then it will no longer be an issue.
