### ISSUE TITLE
Fatal error activating 2.6.9

### ISSUE THREAD

**Issue by lumpysimon** [johnbillion/query-monitor#93]
`Fatal error: Call to undefined method DirectoryIterator::getExtension() in /path/to/wordpress/wp-content/plugins/query-monitor/query-monitor.php on line 65`

I'm guessing it's probably a PHP5.3 issue as it doesn't affect my sites running on 5.5 or 5.6 (I don't have access to a server running 5.4 to test).

**Comment by johnbillion** [comment]
Damn it, `DirectoryIterator::getExtension()` is PHP >5.3.6.

Introduced in #75

**Comment by lumpysimon** [comment]
Ah yes, that server is 5.3.3

**Comment by johnbillion** [comment]
Travis CI was actually telling me this too but I ignored it. https://travis-ci.org/johnbillion/query-monitor/jobs/48122201

**Comment by johnbillion** [comment]
Fixed in a74fc89
