### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by richardsweeney** [johnbillion/query-monitor#94]
After updating yesterday to the latest version I'm getting the following JavaScript error:

```Uncaught TypeError: Cannot read property 'top' of undefined```

on line 65.

I'm using Chrome on Yosemite.

![skarmavbild 2015-01-27 kl 08 37 10](https://cloud.githubusercontent.com/assets/761071/5915003/bfaadc96-a5ff-11e4-8d66-546acfc7766f.png)

**Comment by richardsweeney** [comment]
It's definietely ```qm.menu``` that is undefined. window.qm seems just to be a DOM element.

**Comment by johnbillion** [comment]
Sorry I missed this Richard.

If you take a look at the source code of the page, can you see some JSON-encoded data right at the bottom of the output that belongs to Query Monitor?

Can you see Query Monitor's various `<table>`s near the bottom of the source too?

**Comment by danyj** [comment]
Sorry to dig this one up but I just installed it and have same issue , this is the bug 

http://prntscr.com/agkk20

**Comment by danyj** [comment]
For time being I set this in Backtrace.php on top 

    ini_set('memory_limit', '256M');

**Comment by johnbillion** [comment]
@danyj What do your numbers look like after you've upped the memory limit? Does the page have a particularly high number of database queries, execution time, or memory usage?

**Comment by danyj** [comment]
@johnbillion , yes , I had a strange get term id query in a function https://github.com/ThemeFuse/Unyson/issues/1356#issue-140478019  and everything was slowing down , thus I got your plugin to find the issue  , it let go when I started using ,  

    get_queried_object_id()

instead. So it was query issue that caused the memory bug

**Comment by lkraav** [comment]
I'm also seeing `Backtrace.php` crashing because it's running out of memory. Weird thing is, `php.ini` clearly sets `memory_limit = 512M`, verified by `phpinfo()`. But error_log displays oom at 256M bytecount. What's up with that?

**Comment by lkraav** [comment]
It's probably `WP_MAX_MEMORY_LIMIT`

https://codex.wordpress.org/Editing_wp-config.php#Increasing_memory_allocated_to_PHP
https://github.com/WordPress/WordPress/blob/master/wp-includes/default-constants.php#L30

For any `memory_limit` values higher than `256M`, it looks like we have to set this constant explicitly to for `wp-admin`.

**Comment by johnbillion** [comment]
@lkraav Correct, and you beat me to the Trac link too :)
