### ISSUE TITLE
Fallback when jQuery is unenqueued

### ISSUE THREAD

**Issue by rpkoller** [johnbillion/query-monitor#96]
I've installed Query Monitor for the first time today and I am a bit confused. Inside the admin interface every page is loaded properly and query monitor is returning output as soon as it is activated. But if I go to the front end the only reaction showing, clicking the query monitor button in the admin bar, is that #qm-overview is added to the slug but no further output like in the admin interface shows up. I am logged in as admin user on WordPress 4.1 with Query Monitor 2.6.9 installed. Do I miss something or have I done anything entirely wrong regarding the usage of query monitor in the wp front end? Best regards Ralf

**Comment by johnbillion** [comment]
Nope, output on the front end should work automatically just like in the admin area.

Can you take a look at your browser's JavaScript console? Are there any errors in there?

If you take a look at the source code of the page, can you see some JSON-encoded data right at the bottom of the output that belongs to Query Monitor?

**Comment by johnbillion** [comment]
This might be the same issue as #94

**Comment by rpkoller** [comment]
hi john thanks for the quick reply! 

hmmm the console isn't throwing any errors as far as i can see. and if i take a closer look at the source i have the `div` with the `id` `qm` containing all the query monitor related content and beneath there is the script tag containing the json encoded snippet. 

ahhh but i've compared the html source in the admin area with the source in the front end. 

admin
```html
<div id="qm" class style="display:block">
```

front end
```html
<div id="qm" class>
```

when i've added the inline style manually to the front end source the output was shown too. only the infos in the query monitor widget in the admin bar isn't shown this way. it shows the name all the time. but at least  a way to track the issue down half ways. 

aside i would leave out the class property without any class assigend in the front end as well as in the admin area? 

best regards Ralg

**Comment by rpkoller** [comment]
Ok i've compared the admin bar source too. There it seems the infos aren't parsed in the front end. On the left the admin bar source in the front end on the right the source of the admin bar in the admin area. 

![bildschirmfoto 2015-02-10 um 17 10 16](https://cloud.githubusercontent.com/assets/1665422/6130801/f9a916b2-b147-11e4-9afe-b3d00963ab6e.png)

**Comment by rpkoller** [comment]
And a last maybe related note. In the admin area once the query monitor infos are blended in at the bottom of the page by clicking the query monitor widget in the admin bar you are unable to blend the infos  out again by clicking again ( but unsure if that should be basically possible or not). You have to reload the page that the infos disappear again.

**Comment by rpkoller** [comment]
hm i've updated to version 2.7 today. the frontend still doesn't work but at least an error is shown now instead of simply nothing. maybe that one helps to track down the root cause of the problem :/ 

```
Catchable fatal error: Argument 1 passed to QM_Collector_Assets::get_broken_dependencies() must be an instance of _WP_Dependency, boolean given, called in /Applications/MAMP/htdocs/mypage/wp-content/plugins/query-monitor/collectors/assets.php on line 69 and defined in /Applications/MAMP/htdocs/mypage/wp-content/plugins/query-monitor/collectors/assets.php on line 79
```

**Comment by johnbillion** [comment]
Thanks for the info Ralf.

It sounds like one of the JavaScript or CSS files enqueued on your site has a broken dependency. QM should correctly detect these now, but there's a chance that it's an edge case I've not considered.

Can you try deactivating the plugins on your site one by one and see if the problem disappears?

Failing that, it might be a problem with the scripts and styles enqueued by your theme. Is it a freely available theme? Does the problem disappear if you switch to a default theme such as Twenty Fifteen?

**Comment by rpkoller** [comment]
Ahhhh i think I know the reason. It's jQuery. I have the following snippet in my functions.php

```
function theme_js() {
	if( !is_admin() ){
		wp_deregister_script( 'jquery' );
	}
	wp_enqueue_script( 'overturejs', get_template_directory_uri() . '/js/overture.min.js', array(), null, false);
	wp_enqueue_script( 'mainjs', get_template_directory_uri() . '/js/main.min.js', array(), null, true);
}
add_action('wp_enqueue_scripts', 'theme_js');
```

i've included the jquery file in the main.min.js around other jquery plugins and javascript snippets concatenated into one single file for fewer http requests in the front end. as soon as i've commented out

```
//	if( !is_admin() ){
//		wp_deregister_script( 'jquery' );
//	}
```
everything worked in the frontend too as expected. haven't thought query monitor would depend on jquery therefor i haven't given much thought towards that direction. :/

**Comment by johnbillion** [comment]
Ah yeah that'll be the reason then. QM uses jQuery for a few things such as the dropdown filters.

I should be able to prevent a fatal error occurring in this situation. I'll take a look later this week.
