### ISSUE TITLE
QM_Output_Html_Assets::dependency_rows() fatal error in log

### ISSUE THREAD

**Issue by Rarst** [johnbillion/query-monitor#97]
Updated to 2.6.10 today and noticed errors in log soon after:

> PHP Catchable fatal error: Argument 1 passed to QM_Output_Html_Assets::dependency_rows() must be of the type array, null given, called in .../query-monitor/output/html/assets.php on line 74 and defined in .../query-monitor/output/html/assets.php on line 82

> Argument 1 passed to QM_Output_Html_Assets::dependency_rows() must be of the type array, null given, called in .../query-monitor/output/html/assets.php on line 74 and defined in .../query-monitor/output/html/assets.php on line 82, backtrace: shutdown_action_hook, do_action('shutdown'), call_user_func_array, QueryMonitor->action_shutdown, QM_Dispatcher->output, QM_Output_Html_Assets->output, QM_Output_Html_Assets->dependency_rows

Hadn't seen anything break live, so not sure what caused it and in which context.

**Comment by johnbillion** [comment]
Thanks, I know what this is. I'll get a fix in place.
