### ISSUE TITLE
readme.txt got duplicated changelog lines

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/query-monitor#98]
http://plugins.svn.wordpress.org/query-monitor/trunk/readme.txt

**Comment by johnbillion** [comment]
Fixed.

**Comment by szepeviktor** [comment]
@johnbillion How do you add changelog to readme.txt?
https://plugins.trac.wordpress.org/browser/query-monitor/trunk/readme.txt#L142

**Comment by johnbillion** [comment]
It happens in this action: https://github.com/johnbillion/plugin-infrastructure/blob/d0b9c37d6f8129e7df3e6a1bc6b24aeb53753515/.github/workflows/reusable-deploy-tag.yml#L44-L103

**Comment by szepeviktor** [comment]
Thank you.
