### ISSUE TITLE
Geting "Notice: Trying to get property of non-object" sometimes

### ISSUE THREAD

**Issue by bonny** [johnbillion/query-monitor#99]
I get these errors in my ajax output when using for example (perhaps only when) using plugin [WP Page Widget](https://wordpress.org/plugins/wp-page-widget/).

```
<b>Notice</b>:  Trying to get property of non-object in <b>/public/assets/plugins/query-monitor/output/headers/php_errors.php</b> on line <b>48</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/public/assets/plugins/query-monitor/output/headers/php_errors.php</b> on line <b>48</b><br />
<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/public/assets/plugins/query-monitor/output/headers/php_errors.php</b> on line <b>48</b><br />
```

**Comment by johnbillion** [comment]
Thanks, looks like this is related to the component detection code which I've gradually been making improvements to. I'll take a look at some point.

**Comment by szepeviktor** [comment]
@bonny Temporarly mute it with `@`.

**Comment by johnbillion** [comment]
> Temporarly mute it with @.

Please don't recommend this to people.

**Comment by szepeviktor** [comment]
I am sorry. It seemed better than waiting.

**Comment by pdewouters** [comment]
I just stumbled upon this error too while adding a text widget to a sidebar in the dashboard under Appeareance Widgets

![screen shot 2015-05-14 at 10 24 01](https://cloud.githubusercontent.com/assets/30460/7629329/8d9957dc-fa23-11e4-8957-d6c856e84d22.png)

**Comment by johnbillion** [comment]
Thanks Paul, I'll look into it soon.

**Comment by webdevid** [comment]
i get the same issue.. -_- how to fix this?

**Comment by tjuris** [comment]
Encountered similar issue.
Log file:
* [02-Nov-2015 14:45:27 UTC] PHP Notice:  Undefined index: taxonomy in .../themes/... on line 136
* [02-Nov-2015 14:45:27 UTC] PHP Notice:  Trying to get property of non-object in .../plugins/query-monitor/output/headers/php_errors.php on line 45
On front-end, only the second error was visible. I did a var_dump on $component in php_errors.php, which resulted in NULL. Guessing that was not expected.
Problem disappeared after getting rid of the original notice.

**Comment by johnbillion** [comment]
@tjuris Does the first error come from your theme? If so, is there anything unusual about your theme or your site's configuration? Particularly if you're using symlinks, or your files aren't in the usual place.

**Comment by tjuris** [comment]
Theme, yes, but nothing unusual. No symlinks.
It was missing a check to see if an array key exists during an ajax request.

**Comment by rahularyan** [comment]
Having same issue when I try to hook into admin_init. Those who want simple quick fix simply edit line 45:
`'component' => !empty( $component->name ) ? $component->name : 'not_sure',`

**Comment by johnbillion** [comment]
No reports of this lately, so I'll close it off.
